In [1]:
import pandas as pd
import warnings
from IPython.utils import io
import sys
import numpy as np
import re

warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

stars_dir = '~/GitHub/stars-data-builder/'

## Load SAS pack primary output data

In [2]:
# 2027 -- prognosticated

df_2027 = pd.read_csv(stars_dir + "2027/predictions_From_May_2026/R_CSV_output/Star_2026may.csv")

df_2027['PROVIDER_ID'] = df_2027['PROVIDER_ID'].astype(str)
df_2027 = df_2027.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
df_2027.columns = df_2027.columns.str.strip()

## Replace the imputed 666666 suffixes of VHA hospitals with their original 'F' suffix
prvdrs = []
for p in df_2027['PROVIDER_ID'].tolist():
    p = str(p)
    if '666666' in p:
        p = p[:-6]
        p = p + 'F'
    while len(p) < 6:
        p = '0' + p
    prvdrs.append(p)
    
df_2027['PROVIDER_ID'] = prvdrs

for i in list(df_2027):
    if i == 'cnt_grp':
        df_2027[i] = df_2027[i].astype(str).str[0]
    if i == 'PROVIDER_ID':
        pass
    else:
        df_2027[i] = pd.to_numeric(df_2027[i], errors='coerce')

df_2027['Release year'] = ['2027']*df_2027.shape[0]
df_2027 = df_2027[~df_2027['star'].isin([np.nan, float("NaN")])]
prvdrs_2027 = df_2027['PROVIDER_ID'].unique()

print(len(prvdrs_2027), 'hospitals with stars predictions for 2027')
for star in [1,2,3,4,5]:
    tdf = df_2027[df_2027['star'] == star]
    print(tdf.shape[0], str(star)+'-star hospitals')

df_2027.head()

3206 hospitals with stars predictions for 2027
389 1-star hospitals
693 2-star hospitals
930 3-star hospitals
851 4-star hospitals
343 5-star hospitals

,PROVIDER_ID,Std_Outcomes_Mortality_score,Outcomes_Mortality_cnt,Std_Outcomes_Safety_score,Outcomes_Safety_cnt,Std_Outcomes_Readmission_score,Outcomes_Readmission_cnt,Std_PatientExp_score,Patient_Experience_cnt,Std_Process_score,Process_cnt,std_weight_Mortality,std_weight_Safety,std_weight_Readmission,std_weight_PatientExperience,std_weight_Process,weight_Outcomes_Mortality,weight_Outcomes_Safety,weight_Outcomes_Readmission,weight_PatientExperience,weight_Process,summary_score,Total_measure_group_cnt,MortSafe_Group_cnt,report_indicator,cnt_grp,star,Release year
0,010001,-0.254703,8,0.548349,7,0.328216,11,-0.038263,13,-0.562494,9,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,0.060893,5,2,1,3.0,3.0,2027
1,010005,-0.770213,6,-0.867834,7,1.542859,9,-0.164937,13,-0.513738,9,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.118876,5,2,1,3.0,2.0,2027
2,010006,-1.712634,8,0.474399,8,-0.058293,9,-1.232837,13,-0.280819,9,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.590158,5,2,1,3.0,2.0,2027
3,010007,-2.150146,4,-1.062471,2,-1.215400,5,-0.969839,5,-1.250701,7,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-1.337612,4,1,1,2.0,1.0,2027
4,010011,-0.297572,8,0.092450,7,-0.208704,8,-0.401199,8,-0.001538,6,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.179490,5,2,1,3.0,3.0,2027

In [3]:
# 2026 -- actual

df_2026 = pd.read_csv(stars_dir + '2026/2026-05_Stars_Release/R_CSV_output/Star_2026apr.csv')
df_2026['PROVIDER_ID'] = df_2026['PROVIDER_ID'].astype(str)
df_2026 = df_2026.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
df_2026.columns = df_2026.columns.str.strip()

prvdrs = df_2026['PROVIDER_ID'].astype(str).tolist()
for i, p in enumerate(prvdrs):
    if len(p) < 6:
        prvdrs[i] = '0' + p
df_2026['PROVIDER_ID'] = prvdrs

for i in list(df_2026):
    if i == 'cnt_grp':
        df_2026[i] = df_2026[i].astype(str).str[0]
    if i == 'PROVIDER_ID':
        pass
    else:
        df_2026[i] = pd.to_numeric(df_2026[i], errors='coerce')

df_2026['Release year'] = ['2026']*df_2026.shape[0]
df_2026 = df_2026[~df_2026['star'].isin([np.nan, float("NaN")])]
prvdrs_2026 = df_2026['PROVIDER_ID'].unique()

print(len(prvdrs_2026), 'hospitals with stars predictions for 2026')
df_2026.head()

3203 hospitals with stars predictions for 2026

,PROVIDER_ID,Std_Outcomes_Mortality_score,Outcomes_Mortality_cnt,Std_Outcomes_Safety_score,Outcomes_Safety_cnt,Std_Outcomes_Readmission_score,Outcomes_Readmission_cnt,Std_PatientExp_score,Patient_Experience_cnt,Std_Process_score,Process_cnt,std_weight_Mortality,std_weight_Safety,std_weight_Readmission,std_weight_PatientExperience,std_weight_Process,weight_Outcomes_Mortality,weight_Outcomes_Safety,weight_Outcomes_Readmission,weight_PatientExperience,weight_Process,summary_score,Total_measure_group_cnt,MortSafe_Group_cnt,report_indicator,cnt_grp,star,Release year
0,010001,-0.253894,8,0.574390,7,0.613401,11,0.079690,15,-0.150603,10,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,0.204917,5,2,1,3.0,4.0,2026
1,010005,-0.768920,6,-0.179979,7,0.938422,9,-0.051781,15,-0.770175,10,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.106118,5,2,1,3.0,3.0,2026
2,010006,-1.711257,8,0.604104,8,0.128104,9,-1.092832,15,-0.348938,9,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.497686,5,2,1,3.0,2.0,2026
3,010007,-2.144610,4,-0.542165,2,-1.215442,5,-1.446407,5,-1.885796,7,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-1.402993,4,1,1,2.0,1.0,2026
5,010011,-0.296882,8,-0.444070,7,0.210360,8,-0.460691,10,-0.021926,7,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.220714,5,2,1,3.0,3.0,2026

In [4]:
tdf = df_2026[df_2026['PROVIDER_ID'].isin(['140119', '140063', '140029'])]
tdf.head()

,PROVIDER_ID,Std_Outcomes_Mortality_score,Outcomes_Mortality_cnt,Std_Outcomes_Safety_score,Outcomes_Safety_cnt,Std_Outcomes_Readmission_score,Outcomes_Readmission_cnt,Std_PatientExp_score,Patient_Experience_cnt,Std_Process_score,Process_cnt,std_weight_Mortality,std_weight_Safety,std_weight_Readmission,std_weight_PatientExperience,std_weight_Process,weight_Outcomes_Mortality,weight_Outcomes_Safety,weight_Outcomes_Readmission,weight_PatientExperience,weight_Process,summary_score,Total_measure_group_cnt,MortSafe_Group_cnt,report_indicator,cnt_grp,star,Release year
1094,140029,0.596369,8,0.371937,8,0.196678,11,-0.005704,15,0.698197,10,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,0.338825,5,2,1,3.0,4.0,2026
1109,140063,1.607526,6,-0.397378,5,0.557798,8,-0.569012,15,-0.902249,8,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,0.155495,5,2,1,3.0,4.0,2026
1135,140119,2.215100,8,0.369172,8,0.471158,11,0.214184,15,-1.164413,9,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,0.579586,5,2,1,3.0,5.0,2026

In [5]:
# 2025 -- actual

df_2025 = pd.read_csv(stars_dir + '2025/2025-07 Stars Release/SAS_CSV_output/CMS_Stars_Jul_2025.csv')
df_2025['PROVIDER_ID'] = df_2025['PROVIDER_ID'].astype(str)
df_2025 = df_2025.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
df_2025.columns = df_2025.columns.str.strip()

prvdrs = df_2025['PROVIDER_ID'].astype(str).tolist()
for i, p in enumerate(prvdrs):
    if len(p) < 6:
        prvdrs[i] = '0' + p
df_2025['PROVIDER_ID'] = prvdrs

for i in list(df_2025):
    if i == 'cnt_grp':
        df_2025[i] = df_2025[i].astype(str).str[0]
    if i == 'PROVIDER_ID':
        pass
    else:
        df_2025[i] = pd.to_numeric(df_2025[i], errors='coerce')

df_2025['Release year'] = ['2025']*df_2025.shape[0]
df_2025 = df_2025[~df_2025['star'].isin([np.nan, float("NaN")])]
prvdrs_2025 = df_2025['PROVIDER_ID'].unique()

print(len(prvdrs_2025), 'hospitals with stars predictions for 2025')
df_2025.head()

2891 hospitals with stars predictions for 2025

,PROVIDER_ID,Std_Outcomes_Mortality_score,Std_Outcomes_Readmission_score,Std_Outcomes_Safety_score,Std_PatientExp_score,Std_Process_score,std_weight_PatientExperience,std_weight_Readmission,std_weight_Mortality,std_weight_safety,std_weight_Process,weight_PatientExperience,weight_Outcomes_Readmission,weight_Outcomes_Mortality,weight_Outcomes_Safety,weight_Process,summary_score,Outcomes_Mortality_cnt,Outcomes_safety_cnt,Outcomes_Readmission_cnt,Patient_Experience_cnt,Process_cnt,Total_measure_group_cnt,MortSafe_Group_cnt,report_indicator,cnt_grp,star,Release year
0,010001,0.296110,0.361406,0.344883,0.042072,-0.484678,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,0.171622,7,7,11,8,11,5,2,1,3.0,4.0,2025
1,010005,-0.843034,0.631203,-0.403414,0.125181,-0.352656,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.150133,6,7,9,8,12,5,2,1,3.0,3.0,2025
2,010006,-1.540677,-0.104890,0.685911,-1.301785,-0.458178,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.552498,7,8,9,8,10,5,2,1,3.0,2.0,2025
3,010007,-3.330700,-0.931587,-0.329281,1.298719,-3.269085,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-1.116717,3,3,7,8,7,5,2,1,3.0,1.0,2025
5,010011,-0.554085,-0.590401,0.302812,-0.033641,-1.054047,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.319055,7,7,9,8,8,5,2,1,3.0,2.0,2025

In [6]:
# 2024 -- actual

df_2024 = pd.read_csv(stars_dir + '2024/2024-07 Stars Release/SAS_CSV_output/CMS_Stars_Jul_2024.csv')
df_2024['PROVIDER_ID'] = df_2024['PROVIDER_ID'].astype(str)
df_2024 = df_2024.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
df_2024.columns = df_2024.columns.str.strip()

prvdrs = df_2024['PROVIDER_ID'].astype(str).tolist()
for i, p in enumerate(prvdrs):
    if len(p) < 6:
        prvdrs[i] = '0' + p
df_2024['PROVIDER_ID'] = prvdrs

for i in list(df_2024):
    if i == 'cnt_grp':
        df_2024[i] = df_2024[i].astype(str).str[0]
    if i == 'PROVIDER_ID':
        pass
    else:
        df_2024[i] = pd.to_numeric(df_2024[i], errors='coerce')

df_2024['Release year'] = ['2024']*df_2024.shape[0]
df_2024 = df_2024[~df_2024['star'].isin([np.nan, float("NaN")])]
prvdrs_2024 = df_2024['PROVIDER_ID'].unique()

print(len(prvdrs_2024), 'hospitals with stars predictions for 2024')
df_2024.head()

2847 hospitals with stars predictions for 2024

,PROVIDER_ID,Std_Outcomes_Mortality_score,Std_Outcomes_Readmission_score,Std_Outcomes_Safety_score,Std_PatientExp_score,Std_Process_score,std_weight_PatientExperience,std_weight_Readmission,std_weight_Mortality,std_weight_safety,std_weight_Process,weight_PatientExperience,weight_Outcomes_Readmission,weight_Outcomes_Mortality,weight_Outcomes_Safety,weight_Process,summary_score,Outcomes_Mortality_cnt,Outcomes_safety_cnt,Outcomes_Readmission_cnt,Patient_Experience_cnt,Process_cnt,Total_measure_group_cnt,MortSafe_Group_cnt,report_indicator,cnt_grp,star,Release year
0,010001,0.007071,0.230867,-0.146867,0.137779,-0.677624,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.030968,7,7,11,8,10,5,2,1,3.0,3.0,2024
1,010005,-1.440587,0.720263,-0.087720,-0.255125,-0.489001,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.292577,6,7,9,8,12,5,2,1,3.0,2.0,2024
2,010006,-1.462748,-0.269475,-0.173331,-1.097088,-0.754912,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.751171,7,7,9,8,11,5,2,1,3.0,1.0,2024
3,010007,-3.527615,-0.470903,0.393999,0.199767,-1.804879,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.965631,3,2,7,8,7,4,1,1,2.0,1.0,2024
5,010011,-0.476720,-0.402191,0.346623,-0.030498,-1.046286,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.249367,7,7,9,8,8,5,2,1,3.0,3.0,2024

In [7]:
# 2023 -- actual

df_2023 = pd.read_csv(stars_dir + '2023/2023-07 Stars Release/SAS_CSV_output/CMS_Stars_Jul_2023.csv')
print(df_2023.shape)
df_2023['PROVIDER_ID'] = df_2023['PROVIDER_ID'].astype(str)
df_2023 = df_2023.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
df_2023.columns = df_2023.columns.str.strip()
print(df_2023.shape)

prvdrs = df_2023['PROVIDER_ID'].astype(str).tolist()
for i, p in enumerate(prvdrs):
    if len(p) < 6:
        prvdrs[i] = '0' + p
df_2023['PROVIDER_ID'] = prvdrs

for i in list(df_2023):
    if i == 'cnt_grp':
        df_2023[i] = df_2023[i].astype(str).str[0]
    if i == 'PROVIDER_ID':
        pass
    else:
        df_2023[i] = pd.to_numeric(df_2023[i], errors='coerce')

df_2023['Release year'] = ['2023']*df_2023.shape[0]
df_2023 = df_2023[~df_2023['star'].isin([np.nan, float("NaN")])]
prvdrs_2023 = df_2023['PROVIDER_ID'].unique()

print(len(prvdrs_2023), 'hospitals with a star ratings in 2023')
df_2023.head()

(4654, 27)
(4654, 27)
3076 hospitals with a star ratings in 2023

,PROVIDER_ID,Std_Outcomes_Mortality_score,Std_Outcomes_Readmission_score,Std_Outcomes_Safety_score,Std_PatientExp_score,Std_Process_score,std_weight_PatientExperience,std_weight_Readmission,std_weight_Mortality,std_weight_safety,std_weight_Process,weight_PatientExperience,weight_Outcomes_Readmission,weight_Outcomes_Mortality,weight_Outcomes_Safety,weight_Process,summary_score,Outcomes_Mortality_cnt,Outcomes_safety_cnt,Outcomes_Readmission_cnt,Patient_Experience_cnt,Process_cnt,Total_measure_group_cnt,MortSafe_Group_cnt,report_indicator,cnt_grp,star,Release year
0,010001,-0.647058,0.284081,0.312074,-0.127836,-1.024044,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.162208,7,8,11,8,10,5,2,1,3.0,3.0,2023
1,010005,-1.564103,0.560369,-0.237844,-0.166838,-0.302742,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.346181,6,7,10,8,11,5,2,1,3.0,2.0,2023
2,010006,-1.694318,-0.554988,-0.089526,-1.241108,-0.179350,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.809109,7,7,9,8,11,5,2,1,3.0,1.0,2023
3,010007,-2.407150,-0.488553,0.022657,0.993806,-0.659760,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.492604,3,2,6,8,7,4,1,1,2.0,2.0,2023
5,010011,-0.517349,-0.624302,0.428770,0.134223,-2.385055,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.413511,7,7,9,8,8,5,2,1,3.0,2.0,2023

In [8]:
# 2022 - actual

df_2022 = pd.read_csv(stars_dir + '2022/2022-07 Stars Release/SAS_CSV_output/CMS_Stars_Jul_2022.csv')
df_2022['PROVIDER_ID'] = df_2022['PROVIDER_ID'].astype(int).astype(str)
df_2022 = df_2022.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
df_2022.columns = df_2022.columns.str.strip()

prvdrs = df_2022['PROVIDER_ID'].astype(str).tolist()
for i, p in enumerate(prvdrs):
    if len(p) < 6:
        prvdrs[i] = '0' + p
df_2022['PROVIDER_ID'] = prvdrs

for i in list(df_2022):
    if i == 'cnt_grp':
        df_2022[i] = df_2022[i].astype(str).str[0]
    if i == 'PROVIDER_ID':
        pass
    else:
        df_2022[i] = pd.to_numeric(df_2022[i], errors='coerce')

df_2022['Release year'] = ['2022']*df_2022.shape[0]
df_2022 = df_2022[~df_2022['star'].isin([np.nan, float("NaN")])]
prvdrs_2022 = df_2022['PROVIDER_ID'].unique()

print(len(prvdrs_2022), 'hospitals with a star ratings in 2022')
df_2022.head()

3121 hospitals with a star ratings in 2022

,PROVIDER_ID,Std_Outcomes_Mortality_score,Std_Outcomes_Readmission_score,Std_Outcomes_Safety_score,Std_PatientExp_score,Std_Process_score,std_weight_PatientExperience,std_weight_Readmission,std_weight_Mortality,std_weight_safety,std_weight_Process,weight_PatientExperience,weight_Outcomes_Readmission,weight_Outcomes_Mortality,weight_Outcomes_Safety,weight_Process,summary_score,Outcomes_Mortality_cnt,Outcomes_safety_cnt,Outcomes_Readmission_cnt,Patient_Experience_cnt,Process_cnt,Total_measure_group_cnt,MortSafe_Group_cnt,report_indicator,cnt_grp,star,Release year
0,010001,-0.846744,-0.321758,0.591483,0.072100,-0.320038,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.149487,7,8,11,8,9,5,2,1,3.0,3.0,2022
1,010005,-1.354201,1.419195,-0.145974,0.056106,0.003965,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.004997,6,7,10,8,11,5,2,1,3.0,3.0,2022
2,010006,-1.645507,0.033444,-0.269957,-0.966379,0.026680,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.623446,7,7,9,8,9,5,2,1,3.0,2.0,2022
3,010007,-1.663574,-0.804531,1.163333,0.357169,0.841066,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.107545,3,2,6,8,5,4,1,1,2.0,3.0,2022
5,010011,-1.032452,-1.670115,0.164188,-0.319080,-1.171470,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.769217,7,7,9,8,5,5,2,1,3.0,2.0,2022

In [9]:
# 2021 - actual

df_2021 = pd.read_csv(stars_dir + '2021/2021-04 Stars Release/SAS_CSV_output/CMS_Stars_Apr_2021.csv')
df_2021['PROVIDER_ID'] = df_2021['PROVIDER_ID'].astype(int).astype(str)
df_2021 = df_2021.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
df_2021.columns = df_2021.columns.str.strip()

prvdrs = df_2021['PROVIDER_ID'].astype(str).tolist()
for i, p in enumerate(prvdrs):
    if len(p) < 6:
        prvdrs[i] = '0' + p
df_2021['PROVIDER_ID'] = prvdrs

for i in list(df_2021):
    if i == 'cnt_grp':
        df_2021[i] = df_2021[i].astype(str).str[0]
    if i == 'PROVIDER_ID':
        pass
    else:
        df_2021[i] = pd.to_numeric(df_2021[i], errors='coerce')

df_2021['Release year'] = ['2021']*df_2021.shape[0]
df_2021 = df_2021[~df_2021['star'].isin([np.nan, float("NaN")])]
prvdrs_2021 = df_2021['PROVIDER_ID'].unique()

print(len(prvdrs_2021), 'hospitals with a star ratings in 2021')
df_2021.head()

3355 hospitals with a star ratings in 2021

,PROVIDER_ID,Std_Outcomes_Mortality_score,Std_Outcomes_Readmission_score,Std_Outcomes_Safety_score,Std_PatientExp_score,Std_Process_score,std_weight_PatientExperience,std_weight_Readmission,std_weight_Mortality,std_weight_safety,std_weight_Process,weight_PatientExperience,weight_Outcomes_Readmission,weight_Outcomes_Mortality,weight_Outcomes_Safety,weight_Process,summary_score,Outcomes_Mortality_cnt,Outcomes_safety_cnt,Outcomes_Readmission_cnt,Patient_Experience_cnt,Process_cnt,Total_measure_group_cnt,MortSafe_Group_cnt,report_indicator,cnt_grp,star,Release year
0,010001,-0.752932,-0.070355,0.556127,0.071425,-0.050316,0.22,0.22,0.22,0.22,0.12,0.22,0.220000,0.220000,0.220000,0.120000,-0.049100,7,8,11,8,11,5,2,1,3.0,3.0,2021
1,010005,-2.799407,0.064559,-0.114854,0.055327,-0.071058,0.22,0.22,0.22,0.22,0.12,0.22,0.220000,0.220000,0.220000,0.120000,-0.623290,6,7,10,8,14,5,2,1,3.0,2.0,2021
2,010006,-1.984738,-0.079649,0.302983,-0.966582,-0.462672,0.22,0.22,0.22,0.22,0.12,0.22,0.220000,0.220000,0.220000,0.120000,-0.655678,7,7,9,8,11,5,2,1,3.0,2.0,2021
3,010007,-2.050643,-0.885254,1.200369,0.356272,-0.642649,0.22,0.22,0.22,0.22,0.12,0.22,0.220000,0.220000,0.220000,0.120000,-0.380554,4,2,6,8,7,4,1,1,2.0,2.0,2021
4,010008,-1.612519,0.261221,-0.002780,NaN,-0.867725,0.22,0.22,0.22,0.22,0.12,NaN,0.282051,0.282051,0.282051,0.153846,-0.515416,3,1,4,0,8,3,1,1,1.0,2.0,2021

## Merge 2026 with 2025, 2024, 2023, 2022, and 2021

In [10]:
main_df = df_2027.merge(df_2026, how='outer')
main_df = main_df.merge(df_2025, how='outer')
main_df = main_df.merge(df_2024, how='outer')
main_df = main_df.merge(df_2023, how='outer')
main_df = main_df.merge(df_2022, how='outer')
main_df = main_df.merge(df_2021, how='outer')

print(df_2021.shape)
print(df_2022.shape)
print(df_2023.shape)
print(df_2024.shape)
print(df_2025.shape)
print(df_2026.shape)
print(df_2027.shape)
print('main_df.shape:', main_df.shape)

main_df.sort_values(by=['summary_score', 'cnt_grp', 'star'], inplace=True, ascending=False)
print(list(main_df))

prvdrs = main_df['PROVIDER_ID'].unique()
print(len(prvdrs), 'hospitals in main_df')

main_df.head()

(3355, 28)
(3121, 28)
(3076, 28)
(2847, 28)
(2891, 28)
(3203, 28)
(3206, 28)
main_df.shape: (21699, 30)
['PROVIDER_ID', 'Std_Outcomes_Mortality_score', 'Outcomes_Mortality_cnt', 'Std_Outcomes_Safety_score', 'Outcomes_Safety_cnt', 'Std_Outcomes_Readmission_score', 'Outcomes_Readmission_cnt', 'Std_PatientExp_score', 'Patient_Experience_cnt', 'Std_Process_score', 'Process_cnt', 'std_weight_Mortality', 'std_weight_Safety', 'std_weight_Readmission', 'std_weight_PatientExperience', 'std_weight_Process', 'weight_Outcomes_Mortality', 'weight_Outcomes_Safety', 'weight_Outcomes_Readmission', 'weight_PatientExperience', 'weight_Process', 'summary_score', 'Total_measure_group_cnt', 'MortSafe_Group_cnt', 'report_indicator', 'cnt_grp', 'star', 'Release year', 'std_weight_safety', 'Outcomes_safety_cnt']
3651 hospitals in main_df

,PROVIDER_ID,Std_Outcomes_Mortality_score,Outcomes_Mortality_cnt,Std_Outcomes_Safety_score,Outcomes_Safety_cnt,Std_Outcomes_Readmission_score,Outcomes_Readmission_cnt,Std_PatientExp_score,Patient_Experience_cnt,Std_Process_score,Process_cnt,std_weight_Mortality,std_weight_Safety,std_weight_Readmission,std_weight_PatientExperience,std_weight_Process,weight_Outcomes_Mortality,weight_Outcomes_Safety,weight_Outcomes_Readmission,weight_PatientExperience,weight_Process,summary_score,Total_measure_group_cnt,MortSafe_Group_cnt,report_indicator,cnt_grp,star,Release year,std_weight_safety,Outcomes_safety_cnt
7799,170183,NaN,0,2.032927,NaN,4.290477,3,2.223623,8,0.873621,3,0.22,NaN,0.22,0.22,0.12,NaN,0.282051,0.282051,0.282051,0.153846,2.545103,4,1,1,2.0,5.0,2023,0.22,3.0
13631,330270,0.546448,1,1.162883,NaN,7.145042,3,1.589132,8,1.830755,3,0.22,NaN,0.22,0.22,0.12,0.22,0.220000,0.220000,0.220000,0.120000,2.517262,4,1,1,2.0,5.0,2023,0.22,5.0
13636,330270,2.882665,1,1.454899,NaN,5.122073,3,1.353749,8,0.209030,2,0.22,NaN,0.22,0.22,0.12,0.22,0.220000,0.220000,0.220000,0.120000,2.404028,3,1,1,1.0,5.0,2021,0.22,6.0
15238,360351,NaN,0,1.824891,NaN,3.795795,3,1.475751,8,2.547755,2,0.22,NaN,0.22,0.22,0.12,NaN,0.282051,0.282051,0.282051,0.153846,2.393521,3,1,1,1.0,5.0,2021,0.22,3.0
9540,220088,1.930896,2,0.674193,3.0,5.712029,3,1.139250,13,1.513530,3,0.22,0.22,0.22,0.22,0.12,0.22,0.220000,0.220000,0.220000,0.120000,2.262025,4,1,1,2.0,5.0,2027,NaN,NaN

## Load SAS pack secondary (domain-specific) files
These data files pertain to standardized scores for each component of a particular measure domain.

In [11]:
# 2027 -- predicted

fnames = ['outcome_readmission', 'outcome_safety', 'process', 'ptexp']
f_ext = ['readmission_', 'safety_', 'process_', 'patient_exp_']

with io.capture_output() as captured: 
    df_2027 = pd.read_csv(stars_dir + '2027/predictions_From_May_2026/R_CSV_output/outcome_mortality.csv')
    #df_2027 = df_2027.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
    
    ls = []
    for p in df_2027['PROVIDER_ID'].tolist():
        p = int(p)
        p = str(p)
        if '666666' in p:
            p = p[:-6]
            p = p + 'F'
        while len(p) < 6:
            p = '0' + p
        ls.append(p)
    df_2027['PROVIDER_ID'] = ls
    

    
cols = list(df_2027)
new_cols = []
ind = cols.index('total_cnt')
for i, c in enumerate(cols):
    if i >= ind:
        c = 'mortality_' + c
    new_cols.append(c)
print(new_cols)
df_2027.columns = new_cols

for j, f in enumerate(fnames):
    with io.capture_output() as captured: 
        tdf = pd.read_csv(stars_dir + '2027/predictions_From_May_2026/R_CSV_output/' + f + '.csv')
    #tdf = tdf.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
    
    ls = []
    for p in tdf['PROVIDER_ID'].tolist():
        p = int(p)
        p = str(p)
        if '666666' in p:
            p = p[:-6]
            p = p + 'F'
        while len(p) < 6:
            p = '0' + p
        ls.append(p)
    tdf['PROVIDER_ID'] = ls
    
    cols = list(tdf)
    new_cols = []
    ind = cols.index('total_cnt')
    for i, c in enumerate(cols):
        if i >= ind:
            c = f_ext[j] + c
        new_cols.append(c)
    tdf.columns = new_cols

    df_2027 = df_2027.merge(tdf, on='PROVIDER_ID', how='outer')
    
df_2027['Release year'] = ['2027']*df_2027.shape[0]
df_2027 = df_2027.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
df_2027 = df_2027[df_2027['PROVIDER_ID'].isin(prvdrs_2027)]
prvdrs = df_2027['PROVIDER_ID'].unique()

print(len(prvdrs), 'hospitals in 2027')
df_2027.head()

['PROVIDER_ID', 'std_MORT_30_AMI', 'std_MORT_30_CABG', 'std_MORT_30_COPD', 'std_MORT_30_HF', 'std_MORT_30_PN', 'std_MORT_30_STK', 'std_PSI_4_SURG_COMP', 'std_Hybrid_HWM', 'mortality_total_cnt', 'mortality_measure_wt', 'mortality_score_before_std', 'mortality_grp_score', 'mortality_mean', 'mortality_sd']
3206 hospitals in 2027

,PROVIDER_ID,std_MORT_30_AMI,std_MORT_30_CABG,std_MORT_30_COPD,std_MORT_30_HF,std_MORT_30_PN,std_MORT_30_STK,std_PSI_4_SURG_COMP,std_Hybrid_HWM,mortality_total_cnt,mortality_measure_wt,mortality_score_before_std,mortality_grp_score,mortality_mean,mortality_sd,std_EDAC_30_AMI,std_EDAC_30_HF,std_EDAC_30_PN,std_OP_32,std_OP_35_ADM,std_OP_35_ED,std_OP_36,std_READM_30_CABG,std_READM_30_COPD,std_READM_30_HIP_KNEE,std_Hybrid_HWR,readmission_total_cnt,readmission_measure_wt,readmission_score_before_std,readmission_grp_score,readmission_mean,readmission_sd,std_COMP_HIP_KNEE,std_PSI_90_SAFETY,std_HAI_1,std_HAI_2,std_HAI_3,std_HAI_4,std_HAI_5,std_HAI_6,safety_total_cnt,safety_measure_wt,safety_score_before_std,safety_grp_score,safety_mean,safety_sd,std_IMM_3,std_OP_18B,std_OP_22,std_OP_23,std_OP_29,std_SEP_1,std_SAFE_USE_OF_OPIOIDS,std_OP_13,std_OP_8,std_OP_10,process_total_cnt,process_measure_wt,process_score_before_std,process_grp_score,process_mean,process_sd,std_H_COMP_1_LINEAR_SCORE,std_H_COMP_2_LINEAR_SCORE,std_H_COMP_5_LINEAR_SCORE,std_H_COMP_6_LINEAR_SCORE,std_H_CLEAN_LINEAR_SCORE,std_H_QUIET_LINEAR_SCORE,std_H_HSP_RATING_LINEAR_SCORE,std_H_RECMND_LINEAR_SCORE,std_O-COMP-1,std_O-COMP-2,std_O-COMP-3,std_O-PATIENT-RATE,std_O-PATIENT-REC,patient_exp_total_cnt,patient_exp_measure_wt,patient_exp_score_before_std,patient_exp_grp_score,patient_exp_mean,patient_exp_sd,Release year
0,010001,0.635591,-0.406721,-0.340213,0.630641,-0.741557,-0.154133,-1.254456,-0.504468,8,0.125000,-0.266915,-0.254703,-0.079043,0.737611,0.930229,0.192983,-0.370577,0.362101,0.617873,0.415289,-0.735719,0.523982,0.266961,0.079285,-0.169533,11,0.090909,0.192079,0.328216,0.004851,0.570443,0.570783,0.243115,0.458071,0.598589,0.773824,NaN,0.452642,-0.197022,7,0.142857,0.414286,0.548349,-0.015739,0.784216,0.943032,-1.167354,-0.767933,NaN,-2.527459,0.134799,0.182040,-0.216761,0.793318,0.126387,9,0.111111,-0.277770,-0.562494,0.023422,0.535459,-0.473033,0.497202,0.271748,0.084833,-0.355198,0.998063,0.307109,0.849646,-0.162060,-1.997243,-0.520059,-0.022825,0.440796,13,0.076923,-0.006232,-0.038263,0.026098,0.844962,2027
1,010005,NaN,NaN,-0.016433,-1.157562,-1.755449,0.198482,-0.468572,-0.683426,6,0.166667,-0.647160,-0.770213,-0.079043,0.737611,NaN,-0.216986,0.772701,-0.005217,1.137410,0.831221,0.825819,NaN,1.317316,0.927832,2.374574,9,0.111111,0.884963,1.542859,0.004851,0.570443,0.845110,0.140344,-1.683291,-2.402572,-0.142609,NaN,-1.517609,-0.113528,7,0.142857,-0.696308,-0.867834,-0.015739,0.784216,-0.806146,0.316539,-0.767933,NaN,0.433887,0.630985,0.003759,0.079941,-0.680188,-1.475812,9,0.111111,-0.251663,-0.513738,0.023422,0.535459,-0.473033,0.497202,-0.989744,-0.167678,-0.809988,0.818050,-0.518317,-0.623436,-0.162060,0.437911,0.450205,-0.022825,0.091241,13,0.076923,-0.113267,-0.164937,0.026098,0.844962,2027
2,010006,-2.026062,-3.276741,0.113079,-0.423940,-1.176082,0.492327,-2.683807,-1.757176,8,0.125000,-1.342300,-1.712634,-0.079043,0.737611,1.028397,0.303952,0.234105,2.321131,NaN,NaN,-1.516488,0.035326,-1.016806,-0.344989,-1.300248,9,0.111111,-0.028402,-0.058293,0.004851,0.570443,-1.486671,-0.733202,0.896699,0.575004,1.202077,1.150331,0.505042,0.741065,8,0.125000,0.356293,0.474399,-0.015739,0.784216,-0.548914,0.257964,0.380487,0.611332,-0.717748,-0.113294,0.003759,-0.394782,NaN,-0.621306,9,0.111111,-0.126945,-0.280819,0.023422,0.535459,-0.853471,-1.378230,-1.410242,-0.925213,-1.264779,0.458024,-1.343743,-1.465197,-1.103081,-1.388454,-0.520059,-1.050944,-0.957423,13,0.076923,-1.015601,-1.232837,0.026098,0.844962,2027
3,010007,NaN,NaN,-1.505823,-0.836603,-3.276285,NaN,NaN,-1.041343,4,0.250000,-1.665013,-2.150146,-0.079043,0.737611,NaN,-2.242174,-0.780307,0.606980,NaN,NaN,NaN,NaN,-0.433276,NaN,-0.593551,5,0.200000,-0.688466,-1.215400,0.004851,0.570443,NaN,-0.322121,NaN,NaN,NaN,NaN,NaN,-1.375770,2,0.500000,-0.848946,-1.062471,-0.015739,0.784216,-2.349539,0.570363,0.380487,NaN,-0.470969,-2.656249,0.003759,NaN,NaN,-0.001789,7,0.142857,-0.646277,-1.250701,0.023422,0.535459,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.103081,-0.170878,-0.520059,-1.565003,-0.607869,5,0.200000,-0.793378,-0.969839,0.026098,0.844962,2027
4,010011,-0.480586,0.549952,-0.145945,-1.295116,-1.357134,0.257251,-0.128065,0.211365,8,0.125000,-0.298535,-0.297572,-0.079043,0.737611,1.257456,-0.494409,-0.393707,0.117223,NaN,NaN,-0.735719,-1.235180,0.033549,NaN,0.537163,8,0.125000,-0.114203,-0.208704,0.004851,0.570443,-0.526526,-0.167966,-0.911121,0.382395,1.202077,NaN,0.269241,0.149235,7,0.142857,0.056762,0.092450,-0.015739,0.784216,0.222782,0.023665,NaN,-0.333380,NaN,0.568962,0.360321,NaN,NaN,-0.706757,6,0.166667,0.022599,-0.001538,0.023422,0.535459,-0.473033,0.122116,-0.779496,-0.167678,-1.037383,0.278011,-0.243175,-0.202555,NaN,NaN,NaN,NaN,NaN,8,0.125000,-0.312899,-0.401199,0.026098,0.844962,2027

In [12]:
# For 2026 -- actual

fnames = ['Outcome_readmission', 'Outcome_safety', 'Process', 'PtExp']
f_ext = ['readmission_', 'safety_', 'process_', 'patient_exp_']


with io.capture_output() as captured: 
    df_2026 = pd.read_csv(stars_dir + '2026/2026-05_Stars_Release/R_CSV_output/Outcome_mortality.csv')
    #df_2026 = df_2026.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
    
    ls = []
    for p in df_2026['PROVIDER_ID'].tolist():
        if len(p) < 6: 
            p = '0' + p
        ls.append(p)
    df_2026['PROVIDER_ID'] = ls
    

    
cols = list(df_2026)
new_cols = []
ind = cols.index('total_cnt')
for i, c in enumerate(cols):
    if i >= ind:
        c = 'mortality_' + c
    new_cols.append(c)
print(new_cols)
df_2026.columns = new_cols

for j, f in enumerate(fnames):
    with io.capture_output() as captured: tdf = pd.read_csv(stars_dir + '2026/2026-05_Stars_Release/R_CSV_output/' + f + '.csv')
    #tdf = tdf.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
    
    ls = []
    for p in df_2026['PROVIDER_ID'].tolist():
        if len(p) < 6: 
            p = '0' + p
        ls.append(p)
    df_2026['PROVIDER_ID'] = ls
    
    cols = list(tdf)
    new_cols = []
    ind = cols.index('total_cnt')
    for i, c in enumerate(cols):
        if i >= ind:
            c = f_ext[j] + c
        new_cols.append(c)
    print(new_cols)
    tdf.columns = new_cols

    df_2026 = df_2026.merge(tdf, on='PROVIDER_ID', how='outer')
    
df_2026['Release year'] = ['2026']*df_2026.shape[0]
df_2026 = df_2026.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
df_2026 = df_2026[df_2026['PROVIDER_ID'].isin(prvdrs_2026)]
prvdrs = df_2026['PROVIDER_ID'].unique()

for ext in f_ext+['mortality_']:
    df_2026.rename(columns={ext+"mean": ext+"Mean",
                            ext+"sd": ext+"StdDev",
                           }, 
                   inplace=True)

df_2026.rename(columns={'std_Hybrid_HWM_RSMR': 'std_Hybrid_HWM'}, inplace=True)

print(len(prvdrs), 'hospitals in 2026')
df_2026.head()

['PROVIDER_ID', 'std_Hybrid_HWM_RSMR', 'std_PSI_4_SURG_COMP', 'std_MORT_30_AMI', 'std_MORT_30_CABG', 'std_MORT_30_COPD', 'std_MORT_30_HF', 'std_MORT_30_PN', 'std_MORT_30_STK', 'mortality_total_cnt', 'mortality_measure_wt', 'mortality_score_before_std', 'mortality_grp_score', 'mortality_mean', 'mortality_sd']
['PROVIDER_ID', 'std_EDAC_30_AMI', 'std_EDAC_30_HF', 'std_EDAC_30_PN', 'std_Hybrid_HWR', 'std_OP_32', 'std_OP_35_ADM', 'std_OP_35_ED', 'std_OP_36', 'std_READM_30_CABG', 'std_READM_30_COPD', 'std_READM_30_HIP_KNEE', 'readmission_total_cnt', 'readmission_measure_wt', 'readmission_score_before_std', 'readmission_grp_score', 'readmission_mean', 'readmission_sd']
['PROVIDER_ID', 'std_HAI_1', 'std_HAI_2', 'std_HAI_3', 'std_HAI_4', 'std_HAI_5', 'std_HAI_6', 'std_PSI_90_SAFETY', 'std_COMP_HIP_KNEE', 'safety_total_cnt', 'safety_measure_wt', 'safety_score_before_std', 'safety_grp_score', 'safety_mean', 'safety_sd']
['PROVIDER_ID', 'std_IMM_3', 'std_OP_10', 'std_OP_13', 'std_OP_18B', 'std_OP_22', 'std_OP_23', 'std_OP_29', 'std_OP_8', 'std_SAFE_USE_OF_OPIOIDS', 'std_SEP_1', 'process_total_cnt', 'process_measure_wt', 'process_score_before_std', 'process_grp_score', 'process_mean', 'process_sd']
['PROVIDER_ID', 'std_H_CLEAN_LINEAR_SCORE', 'std_H_COMP_1_LINEAR_SCORE', 'std_H_COMP_2_LINEAR_SCORE', 'std_H_COMP_3_LINEAR_SCORE', 'std_H_COMP_5_LINEAR_SCORE', 'std_H_COMP_6_LINEAR_SCORE', 'std_H_COMP_7_LINEAR_SCORE', 'std_H_HSP_RATING_LINEAR_SCORE', 'std_H_QUIET_LINEAR_SCORE', 'std_H_RECMND_LINEAR_SCORE', 'std_O-COMP-1', 'std_O-COMP-2', 'std_O-COMP-3', 'std_O-PATIENT-RATE', 'std_O-PATIENT-REC', 'patient_exp_total_cnt', 'patient_exp_measure_wt', 'patient_exp_score_before_std', 'patient_exp_grp_score', 'patient_exp_mean', 'patient_exp_sd']
3203 hospitals in 2026

,PROVIDER_ID,std_Hybrid_HWM,std_PSI_4_SURG_COMP,std_MORT_30_AMI,std_MORT_30_CABG,std_MORT_30_COPD,std_MORT_30_HF,std_MORT_30_PN,std_MORT_30_STK,mortality_total_cnt,mortality_measure_wt,mortality_score_before_std,mortality_grp_score,mortality_Mean,mortality_StdDev,std_EDAC_30_AMI,std_EDAC_30_HF,std_EDAC_30_PN,std_Hybrid_HWR,std_OP_32,std_OP_35_ADM,std_OP_35_ED,std_OP_36,std_READM_30_CABG,std_READM_30_COPD,std_READM_30_HIP_KNEE,readmission_total_cnt,readmission_measure_wt,readmission_score_before_std,readmission_grp_score,readmission_Mean,readmission_StdDev,std_HAI_1,std_HAI_2,std_HAI_3,std_HAI_4,std_HAI_5,std_HAI_6,std_PSI_90_SAFETY,std_COMP_HIP_KNEE,safety_total_cnt,safety_measure_wt,safety_score_before_std,safety_grp_score,safety_Mean,safety_StdDev,std_IMM_3,std_OP_10,std_OP_13,std_OP_18B,std_OP_22,std_OP_23,std_OP_29,std_OP_8,std_SAFE_USE_OF_OPIOIDS,std_SEP_1,process_total_cnt,process_measure_wt,process_score_before_std,process_grp_score,process_Mean,process_StdDev,std_H_CLEAN_LINEAR_SCORE,std_H_COMP_1_LINEAR_SCORE,std_H_COMP_2_LINEAR_SCORE,std_H_COMP_3_LINEAR_SCORE,std_H_COMP_5_LINEAR_SCORE,std_H_COMP_6_LINEAR_SCORE,std_H_COMP_7_LINEAR_SCORE,std_H_HSP_RATING_LINEAR_SCORE,std_H_QUIET_LINEAR_SCORE,std_H_RECMND_LINEAR_SCORE,std_O-COMP-1,std_O-COMP-2,std_O-COMP-3,std_O-PATIENT-RATE,std_O-PATIENT-REC,patient_exp_total_cnt,patient_exp_measure_wt,patient_exp_score_before_std,patient_exp_grp_score,patient_exp_Mean,patient_exp_StdDev,Release year
0,010001,-0.502326,-1.255617,0.635861,-0.407503,-0.336903,0.630170,-0.741228,-0.155169,8,0.125000,-0.266590,-0.253894,-0.079177,0.738153,0.930664,0.193207,-0.369507,-0.167496,0.294215,1.577732,-0.191118,0.662844,0.524002,0.266962,0.079849,11,0.090909,0.345578,0.613401,-0.000099,0.563541,0.133423,0.793740,0.544171,NaN,0.843810,0.052726,0.242553,0.570514,7,0.142857,0.454419,0.574390,-0.024332,0.833496,0.944322,0.125806,-0.216523,-1.241708,-1.159470,1.067920,-1.503458,0.793318,0.182926,0.407428,10,0.100000,-0.059944,-0.150603,0.017249,0.51256,-0.378725,-0.445368,0.482251,-0.295815,0.578897,0.176407,0.360451,0.275675,1.082405,0.842665,-0.128381,-1.276518,-0.390364,0.037580,0.490315,15,0.066667,0.094098,0.079690,0.027292,0.838328,2026
1,010005,-0.681152,-0.469844,NaN,NaN,-0.014416,-1.156980,-1.755154,0.196999,6,0.166667,-0.646758,-0.768920,-0.079177,0.738153,NaN,-0.217008,0.774312,2.376687,-1.240167,1.508638,-0.786882,0.096395,NaN,1.318246,0.928441,9,0.111111,0.528740,0.938422,-0.000099,0.563541,-0.145997,-0.845448,0.574237,NaN,-1.496084,-0.291778,0.139697,0.844963,7,0.142857,-0.174344,-0.179979,-0.024332,0.833496,-0.801819,-1.478114,0.080293,0.394333,-0.393707,-2.297500,0.620192,-0.680188,0.004698,0.776697,10,0.100000,-0.377512,-0.770175,0.017249,0.51256,-0.378725,-0.069540,0.859497,-1.294589,-0.854810,0.436585,-0.273442,-0.267715,0.900332,-0.402008,-0.128381,0.514020,0.533043,0.037580,0.146388,15,0.066667,-0.016118,-0.051781,0.027292,0.838328,2026
2,010006,-1.754104,-2.684768,-2.026740,-3.278654,0.114579,-0.423791,-1.175767,0.490473,8,0.125000,-1.342347,-1.711257,-0.079177,0.738153,1.028891,0.304243,0.235461,-1.298244,1.609400,NaN,NaN,0.096395,0.035082,-1.017941,-0.344447,9,0.111111,0.072093,0.128104,-0.000099,0.563541,0.881367,0.947470,1.198461,1.120116,1.148146,0.760355,-0.734572,-1.487857,8,0.125000,0.479186,0.604104,-0.024332,0.833496,-0.545034,-0.622690,-0.394612,0.144115,0.372056,-0.194113,-0.441633,NaN,0.004698,0.222793,9,0.111111,-0.161602,-0.348938,0.017249,0.51256,-1.729061,-0.821197,-1.026735,-1.494343,-1.264441,-1.124482,-1.224281,-1.354496,0.354114,-1.439236,-0.128381,-0.679672,-0.390364,-0.468851,-0.541468,15,0.066667,-0.888860,-1.092832,0.027292,0.838328,2026
3,010007,-1.038803,NaN,NaN,NaN,-1.497857,-0.836210,-3.276042,NaN,4,0.250000,-1.662228,-2.144610,-0.079177,0.738153,NaN,-2.243412,-0.779431,-0.591526,0.623011,NaN,NaN,NaN,NaN,-0.433894,NaN,5,0.200000,-0.685051,-1.215442,-0.000099,0.563541,NaN,NaN,NaN,NaN,NaN,-0.629299,-0.323151,NaN,2,0.500000,-0.476225,-0.542165,-0.024332,0.833496,-2.342532,-0.002507,NaN,0.779284,-0.010825,NaN,-2.034371,NaN,0.004698,-3.039087,7,0.142857,-0.949334,-1.885796,0.017249,0.51256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.059965,-1.873364,-1.313771,-1.481713,-0.197540,5,0.200000,-1.185271,-1.446407,0.027292,0.838328,2026
5,010011,0.212975,-0.129385,-0.480714,0.549548,-0.143411,-1.294453,-1.356826,0.255694,8,0.125000,-0.298321,-0.296882,-0.079177,0.738153,1.258087,-0.494598,-0.392648,0.539222,0.294215,NaN,NaN,0.946068,-1.236110,0.033343,NaN,8,0.125000,0.118447,0.210360,-0.000099,0.563541,-2.543651,0.334338,1.198461,NaN,-1.234987,0.180751,-0.168868,-0.527284,7,0.142857,-0.394463,-0.444070,-0.024332,0.833496,0.225323,-0.708232,NaN,0.067125,-0.010825,NaN,-0.669167,NaN,0.361155,0.776697,7,0.142857,0.006011,-0.021926,0.017249,0.51256,-0.828837,-0.821197,-0.272242,0.103694,-0.649995,-0.604126,-0.590388,-0.267715,0.536187,-0.194563,NaN,NaN,NaN,NaN,NaN,10,0.100000,-0.358918,-0.460691,0.027292,0.838328,2026

In [13]:
# For 2025 -- actual

fnames = ['outcome_readmission', 'outcome_safety', 'process', 'ptexp']
f_ext = ['readmission_', 'safety_', 'process_', 'patient_exp_']

with io.capture_output() as captured: 
    df_2025 = pd.read_sas(stars_dir + 'SAS_Downloaded_Databases/2025/actual/outcome_mortality.sas7bdat')
    #df_2025 = df_2025.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
    
    ls = []
    for p in df_2025['PROVIDER_ID'].tolist():
        if len(p) < 6: 
            p = '0' + p
        ls.append(p)
    df_2025['PROVIDER_ID'] = ls
    

    
cols = list(df_2025)
new_cols = []
ind = cols.index('C1')
for i, c in enumerate(cols):
    if i >= ind:
        c = 'mortality_' + c
    new_cols.append(c)
print(new_cols)
df_2025.columns = new_cols

for j, f in enumerate(fnames):
    with io.capture_output() as captured: tdf = pd.read_sas(stars_dir + 'SAS_Downloaded_Databases/2025/actual/' + f + '.sas7bdat')
    #tdf = tdf.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
    
    ls = []
    for p in df_2025['PROVIDER_ID'].tolist():
        if len(p) < 6: 
            p = '0' + p
        ls.append(p)
    df_2025['PROVIDER_ID'] = ls
    
    cols = list(tdf)
    new_cols = []
    ind = cols.index('C1')
    for i, c in enumerate(cols):
        if i >= ind:
            c = f_ext[j] + c
        new_cols.append(c)
    print(new_cols)
    tdf.columns = new_cols

    df_2025 = df_2025.merge(tdf, on='PROVIDER_ID', how='outer')
    
df_2025['Release year'] = ['2025']*df_2025.shape[0]
df_2025 = df_2025.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
df_2025 = df_2025[df_2025['PROVIDER_ID'].isin(prvdrs_2025)]
prvdrs = df_2025['PROVIDER_ID'].unique()

df_2025 = df_2025.loc[:, ~df_2025.columns.str.contains(r'_C\d+$')]

print(len(prvdrs), 'hospitals in 2025')
df_2025.head()

['PROVIDER_ID', 'std_MORT_30_AMI', 'std_MORT_30_CABG', 'std_MORT_30_COPD', 'std_MORT_30_HF', 'std_MORT_30_PN', 'std_MORT_30_STK', 'std_PSI_4_SURG_COMP', 'mortality_C1', 'mortality_C2', 'mortality_C3', 'mortality_C4', 'mortality_C5', 'mortality_C6', 'mortality_C7', 'mortality_total_cnt', 'mortality_measure_wt', 'mortality_score_before_std', 'mortality_Mean', 'mortality_StdDev', 'mortality_grp_score']
['PROVIDER_ID', 'std_EDAC_30_AMI', 'std_EDAC_30_HF', 'std_EDAC_30_PN', 'std_OP_32', 'std_READM_30_CABG', 'std_READM_30_COPD', 'std_READM_30_HIP_KNEE', 'std_READM_30_HOSP_WIDE', 'std_OP_35_ADM', 'std_OP_35_ED', 'std_OP_36', 'readmission_C1', 'readmission_C2', 'readmission_C3', 'readmission_C4', 'readmission_C5', 'readmission_C6', 'readmission_C7', 'readmission_C8', 'readmission_C9', 'readmission_C10', 'readmission_C11', 'readmission_total_cnt', 'readmission_measure_wt', 'readmission_score_before_std', 'readmission_Mean', 'readmission_StdDev', 'readmission_grp_score']
['PROVIDER_ID', 'std_COMP_HIP_KNEE', 'std_HAI_1', 'std_HAI_2', 'std_HAI_3', 'std_HAI_4', 'std_HAI_5', 'std_HAI_6', 'std_PSI_90_SAFETY', 'safety_C1', 'safety_C2', 'safety_C3', 'safety_C4', 'safety_C5', 'safety_C6', 'safety_C7', 'safety_C8', 'safety_total_cnt', 'safety_measure_wt', 'safety_score_before_std', 'safety_Mean', 'safety_StdDev', 'safety_grp_score']
['PROVIDER_ID', 'std_HCP_COVID_19', 'std_IMM_3', 'std_OP_10', 'std_OP_13', 'std_OP_18B', 'std_OP_22', 'std_OP_23', 'std_OP_29', 'std_OP_8', 'std_PC_01', 'std_SAFE_USE_OF_OPIOIDS', 'std_SEP_1', 'process_C1', 'process_C2', 'process_C3', 'process_C4', 'process_C5', 'process_C6', 'process_C7', 'process_C8', 'process_C9', 'process_C10', 'process_C11', 'process_C12', 'process_total_cnt', 'process_measure_wt', 'process_score_before_std', 'process_Mean', 'process_StdDev', 'process_grp_score']
['PROVIDER_ID', 'std_H_COMP_1_STAR_RATING', 'std_H_COMP_2_STAR_RATING', 'std_H_COMP_3_STAR_RATING', 'std_H_COMP_5_STAR_RATING', 'std_H_COMP_6_STAR_RATING', 'std_H_COMP_7_STAR_RATING', 'std_H_GLOB_STAR_RATING', 'std_H_INDI_STAR_RATING', 'patient_exp_C1', 'patient_exp_C2', 'patient_exp_C3', 'patient_exp_C4', 'patient_exp_C5', 'patient_exp_C6', 'patient_exp_C7', 'patient_exp_C8', 'patient_exp_total_cnt', 'patient_exp_measure_wt', 'patient_exp_score_before_std', 'patient_exp_Mean', 'patient_exp_StdDev', 'patient_exp_grp_score']
2891 hospitals in 2025

,PROVIDER_ID,std_MORT_30_AMI,std_MORT_30_CABG,std_MORT_30_COPD,std_MORT_30_HF,std_MORT_30_PN,std_MORT_30_STK,std_PSI_4_SURG_COMP,mortality_total_cnt,mortality_measure_wt,mortality_score_before_std,mortality_Mean,mortality_StdDev,mortality_grp_score,std_EDAC_30_AMI,std_EDAC_30_HF,std_EDAC_30_PN,std_OP_32,std_READM_30_CABG,std_READM_30_COPD,std_READM_30_HIP_KNEE,std_READM_30_HOSP_WIDE,std_OP_35_ADM,std_OP_35_ED,std_OP_36,readmission_total_cnt,readmission_measure_wt,readmission_score_before_std,readmission_Mean,readmission_StdDev,readmission_grp_score,std_COMP_HIP_KNEE,std_HAI_1,std_HAI_2,std_HAI_3,std_HAI_4,std_HAI_5,std_HAI_6,std_PSI_90_SAFETY,safety_total_cnt,safety_measure_wt,safety_score_before_std,safety_Mean,safety_StdDev,safety_grp_score,std_HCP_COVID_19,std_IMM_3,std_OP_10,std_OP_13,std_OP_18B,std_OP_22,std_OP_23,std_OP_29,std_OP_8,std_PC_01,std_SAFE_USE_OF_OPIOIDS,std_SEP_1,process_total_cnt,process_measure_wt,process_score_before_std,process_Mean,process_StdDev,process_grp_score,std_H_COMP_1_STAR_RATING,std_H_COMP_2_STAR_RATING,std_H_COMP_3_STAR_RATING,std_H_COMP_5_STAR_RATING,std_H_COMP_6_STAR_RATING,std_H_COMP_7_STAR_RATING,std_H_GLOB_STAR_RATING,std_H_INDI_STAR_RATING,patient_exp_total_cnt,patient_exp_measure_wt,patient_exp_score_before_std,patient_exp_Mean,patient_exp_StdDev,patient_exp_grp_score,Release year
0,010001,1.405923,-1.045370,1.011496,0.650904,-0.315375,0.023766,-0.732077,7.0,0.142857,0.142753,-0.073484,0.730255,0.296110,1.024273,-0.368843,-0.448127,0.289973,0.607499,0.859382,0.192452,0.768359,-1.028886,0.627910,-0.257980,11.0,0.090909,0.206001,0.013108,0.53373,0.361406,0.698729,0.303670,0.739078,-0.467783,NaN,0.476446,-0.105703,0.103001,7.0,0.142857,0.249634,-0.01903,0.779001,0.344883,-0.525017,1.044716,0.080291,0.781373,-1.062058,-1.138829,NaN,-3.171398,0.588011,0.140984,0.563049,0.449772,11.0,0.090909,-0.204464,0.028411,0.480473,-0.484678,-1.154064,0.570761,-0.231671,-0.254181,-0.312251,0.933177,0.719371,0.020336,8.0,0.125,0.036435,4.899789e-17,0.866021,0.042072,2025
1,010005,-1.492798,NaN,0.150309,-0.366857,-1.766289,-0.083025,-0.576021,6.0,0.166667,-0.689113,-0.073484,0.730255,-0.843034,NaN,-0.330781,0.548360,-1.035150,NaN,2.448388,1.038374,1.653526,1.891523,-0.071403,-2.992838,9.0,0.111111,0.350000,0.013108,0.53373,0.631203,1.158692,-0.332255,-1.072825,1.149255,NaN,-2.749027,-0.428086,-0.058780,7.0,0.142857,-0.333289,-0.01903,0.779001,-0.403414,-0.396114,-0.264294,-1.615666,0.373993,0.303229,-0.270542,-0.094782,0.334795,-1.162943,0.346333,-0.171693,0.925313,12.0,0.083333,-0.141031,0.028411,0.480473,-0.352656,-0.243473,0.570761,-1.172260,0.768655,0.678414,-0.038195,-0.226012,0.529388,8.0,0.125,0.108410,4.899789e-17,0.866021,0.125181,2025
2,010006,-3.138018,-2.730472,-0.512142,-0.135547,-0.626285,-0.243212,-1.004318,7.0,0.142857,-1.198571,-0.073484,0.730255,-1.540677,-0.541852,0.368600,-0.017926,1.105434,-0.951609,0.859382,0.192452,-0.116807,NaN,NaN,-1.283552,9.0,0.111111,-0.042875,0.013108,0.53373,-0.104890,-0.834482,0.977642,1.028777,1.149255,1.108414,0.595372,0.965067,-0.867684,8.0,0.125000,0.515295,-0.01903,0.779001,0.685911,-0.525017,-0.591547,-1.064480,0.315796,-0.313955,0.597745,NaN,-0.452310,NaN,0.551682,-0.171693,-0.263539,10.0,0.100000,-0.191732,0.028411,0.480473,-0.458178,-1.154064,-1.443055,-1.172260,-1.277016,-1.302916,-1.009567,-1.171395,-0.488716,8.0,0.125,-1.127373,4.899789e-17,0.866021,-1.301785,2025
3,010007,NaN,NaN,-2.698232,-1.014523,-3.804479,NaN,NaN,3.0,0.333333,-2.505745,-0.073484,0.730255,-3.330700,NaN,-0.858886,-0.764193,-0.219690,NaN,-0.431686,0.192452,-0.706918,NaN,NaN,-0.599837,7.0,0.142857,-0.484108,0.013108,0.53373,-0.931587,0.085445,NaN,NaN,NaN,NaN,NaN,-1.284702,0.372636,3.0,0.333333,-0.275540,-0.01903,0.779001,-0.329281,-0.525017,-2.773231,-0.322499,NaN,0.583768,-0.704686,NaN,-4.888717,NaN,NaN,NaN,-2.165701,7.0,0.142857,-1.542298,0.028411,0.480473,-3.269085,1.577707,1.577668,0.708919,1.791491,1.669078,0.933177,0.719371,0.020336,8.0,0.125,1.124718,4.899789e-17,0.866021,1.298719,2025
5,010011,-0.160953,1.000826,-0.777123,-0.968261,-1.559016,0.450931,-1.333151,7.0,0.142857,-0.478107,-0.073484,0.730255,-0.554085,0.943664,-1.291837,-0.096942,0.391906,-1.431334,-0.133747,0.361636,-1.887140,NaN,NaN,0.425734,9.0,0.111111,-0.302007,0.013108,0.53373,-0.590401,-0.527840,-0.033316,0.516233,1.149255,NaN,0.270736,-0.121823,0.264782,7.0,0.142857,0.216861,-0.01903,0.779001,0.302812,-0.485355,NaN,-0.428496,NaN,-0.557089,-1.138829,-1.454347,0.621014,NaN,NaN,-0.355379,-0.025768,8.0,0.125000,-0.478031,0.028411,0.480473,-1.054047,-0.243473,0.570761,-0.231671,-0.254181,0.678414,-0.038195,-0.226012,-0.488716,8.0,0.125,-0.029134,4.899789e-17,0.866021,-0.033641,2025

In [14]:
# For 2024 -- actual

fnames = ['outcome_readmission', 'outcome_safety', 'process', 'ptexp']
f_ext = ['readmission_', 'safety_', 'process_', 'patient_exp_']

with io.capture_output() as captured: 
    df_2024 = pd.read_sas(stars_dir + 'SAS_Downloaded_Databases/2024/actual/outcome_mortality.sas7bdat')
    #df_2024 = df_2024.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
    
    ls = []
    for p in df_2024['PROVIDER_ID'].tolist():
        if len(p) < 6: 
            p = '0' + p
        ls.append(p)
    df_2024['PROVIDER_ID'] = ls
    

    
cols = list(df_2024)
new_cols = []
ind = cols.index('C1')
for i, c in enumerate(cols):
    if i >= ind:
        c = 'mortality_' + c
    new_cols.append(c)
print(new_cols)
df_2024.columns = new_cols

for j, f in enumerate(fnames):
    with io.capture_output() as captured: tdf = pd.read_sas(stars_dir + 'SAS_Downloaded_Databases/2024/actual/' + f + '.sas7bdat')
    #tdf = tdf.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
    
    ls = []
    for p in df_2024['PROVIDER_ID'].tolist():
        if len(p) < 6: 
            p = '0' + p
        ls.append(p)
    df_2024['PROVIDER_ID'] = ls
    
    cols = list(tdf)
    new_cols = []
    ind = cols.index('C1')
    for i, c in enumerate(cols):
        if i >= ind:
            c = f_ext[j] + c
        new_cols.append(c)
    print(new_cols)
    tdf.columns = new_cols

    df_2024 = df_2024.merge(tdf, on='PROVIDER_ID', how='outer')
    
df_2024['Release year'] = ['2024']*df_2024.shape[0]
df_2024 = df_2024.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
df_2024 = df_2024[df_2024['PROVIDER_ID'].isin(prvdrs_2024)]
prvdrs = df_2024['PROVIDER_ID'].unique()

df_2024 = df_2024.loc[:, ~df_2024.columns.str.contains(r'_C\d+$')]

print(len(prvdrs), 'hospitals in 2024')
df_2024.head()

['PROVIDER_ID', 'std_MORT_30_AMI', 'std_MORT_30_CABG', 'std_MORT_30_COPD', 'std_MORT_30_HF', 'std_MORT_30_PN', 'std_MORT_30_STK', 'std_PSI_4_SURG_COMP', 'mortality_C1', 'mortality_C2', 'mortality_C3', 'mortality_C4', 'mortality_C5', 'mortality_C6', 'mortality_C7', 'mortality_total_cnt', 'mortality_measure_wt', 'mortality_score_before_std', 'mortality_Mean', 'mortality_StdDev', 'mortality_grp_score']
['PROVIDER_ID', 'std_EDAC_30_AMI', 'std_EDAC_30_HF', 'std_EDAC_30_PN', 'std_OP_32', 'std_READM_30_CABG', 'std_READM_30_COPD', 'std_READM_30_HIP_KNEE', 'std_READM_30_HOSP_WIDE', 'std_OP_35_ADM', 'std_OP_35_ED', 'std_OP_36', 'readmission_C1', 'readmission_C2', 'readmission_C3', 'readmission_C4', 'readmission_C5', 'readmission_C6', 'readmission_C7', 'readmission_C8', 'readmission_C9', 'readmission_C10', 'readmission_C11', 'readmission_total_cnt', 'readmission_measure_wt', 'readmission_score_before_std', 'readmission_Mean', 'readmission_StdDev', 'readmission_grp_score']
['PROVIDER_ID', 'std_COMP_HIP_KNEE', 'std_HAI_1', 'std_HAI_2', 'std_HAI_3', 'std_HAI_4', 'std_HAI_5', 'std_HAI_6', 'std_PSI_90_SAFETY', 'safety_C1', 'safety_C2', 'safety_C3', 'safety_C4', 'safety_C5', 'safety_C6', 'safety_C7', 'safety_C8', 'safety_total_cnt', 'safety_measure_wt', 'safety_score_before_std', 'safety_Mean', 'safety_StdDev', 'safety_grp_score']
['PROVIDER_ID', 'std_HCP_COVID_19', 'std_IMM_3', 'std_OP_10', 'std_OP_13', 'std_OP_18B', 'std_OP_22', 'std_OP_23', 'std_OP_29', 'std_OP_3B', 'std_OP_8', 'std_PC_01', 'std_SEP_1', 'process_C1', 'process_C2', 'process_C3', 'process_C4', 'process_C5', 'process_C6', 'process_C7', 'process_C8', 'process_C9', 'process_C10', 'process_C11', 'process_C12', 'process_total_cnt', 'process_measure_wt', 'process_score_before_std', 'process_Mean', 'process_StdDev', 'process_grp_score']
['PROVIDER_ID', 'std_H_COMP_1_STAR_RATING', 'std_H_COMP_2_STAR_RATING', 'std_H_COMP_3_STAR_RATING', 'std_H_COMP_5_STAR_RATING', 'std_H_COMP_6_STAR_RATING', 'std_H_COMP_7_STAR_RATING', 'std_H_GLOB_STAR_RATING', 'std_H_INDI_STAR_RATING', 'patient_exp_C1', 'patient_exp_C2', 'patient_exp_C3', 'patient_exp_C4', 'patient_exp_C5', 'patient_exp_C6', 'patient_exp_C7', 'patient_exp_C8', 'patient_exp_total_cnt', 'patient_exp_measure_wt', 'patient_exp_score_before_std', 'patient_exp_Mean', 'patient_exp_StdDev', 'patient_exp_grp_score']
2847 hospitals in 2024

,PROVIDER_ID,std_MORT_30_AMI,std_MORT_30_CABG,std_MORT_30_COPD,std_MORT_30_HF,std_MORT_30_PN,std_MORT_30_STK,std_PSI_4_SURG_COMP,mortality_total_cnt,mortality_measure_wt,mortality_score_before_std,mortality_Mean,mortality_StdDev,mortality_grp_score,std_EDAC_30_AMI,std_EDAC_30_HF,std_EDAC_30_PN,std_OP_32,std_READM_30_CABG,std_READM_30_COPD,std_READM_30_HIP_KNEE,std_READM_30_HOSP_WIDE,std_OP_35_ADM,std_OP_35_ED,std_OP_36,readmission_total_cnt,readmission_measure_wt,readmission_score_before_std,readmission_Mean,readmission_StdDev,readmission_grp_score,std_COMP_HIP_KNEE,std_HAI_1,std_HAI_2,std_HAI_3,std_HAI_4,std_HAI_5,std_HAI_6,std_PSI_90_SAFETY,safety_total_cnt,safety_measure_wt,safety_score_before_std,safety_Mean,safety_StdDev,safety_grp_score,std_HCP_COVID_19,std_IMM_3,std_OP_10,std_OP_13,std_OP_18B,std_OP_22,std_OP_23,std_OP_29,std_OP_3B,std_OP_8,std_PC_01,std_SEP_1,process_total_cnt,process_measure_wt,process_score_before_std,process_Mean,process_StdDev,process_grp_score,std_H_COMP_1_STAR_RATING,std_H_COMP_2_STAR_RATING,std_H_COMP_3_STAR_RATING,std_H_COMP_5_STAR_RATING,std_H_COMP_6_STAR_RATING,std_H_COMP_7_STAR_RATING,std_H_GLOB_STAR_RATING,std_H_INDI_STAR_RATING,patient_exp_total_cnt,patient_exp_measure_wt,patient_exp_score_before_std,patient_exp_Mean,patient_exp_StdDev,patient_exp_grp_score,Release year
0,010001,0.470514,-1.535074,0.282996,1.510467,0.129818,-0.554262,-0.748332,7.0,0.142857,-0.063411,-0.068391,0.704371,0.007071,1.123231,-0.791585,-0.633920,0.292070,0.584835,0.293805,0.886353,0.423838,-1.032330,0.626949,-0.252865,11.0,0.090909,0.138216,0.014038,0.537879,0.230867,0.879845,-0.232451,0.488068,-0.711660,NaN,-0.210159,0.003034,-1.162386,7.0,0.142857,-0.135101,-0.021526,0.773315,-0.146867,-0.431525,0.940083,-0.029295,0.419351,-0.942734,-1.140182,NaN,-3.129707,NaN,0.000412,0.583665,0.371166,10.0,0.100000,-0.335877,0.029039,0.538522,-0.677624,-0.373358,-0.400063,-0.243371,0.124487,0.479704,0.876397,0.133873,0.361496,8.0,0.125,0.119895,1.093644e-15,0.870204,0.137779,2024
1,010005,-0.914388,NaN,-0.524963,-1.584524,-1.953144,-0.829076,-0.692504,6.0,0.166667,-1.083100,-0.068391,0.704371,-1.440587,NaN,-0.736899,0.486741,-1.036890,NaN,2.375902,1.641861,2.033114,1.890125,-0.073504,-2.967381,9.0,0.111111,0.401452,0.014038,0.537879,0.720263,1.609414,-2.431638,-0.539793,0.114598,NaN,0.421669,0.024071,0.176149,7.0,0.142857,-0.089361,-0.021526,0.773315,-0.087720,-0.722505,0.123623,-1.210843,-0.383371,0.310092,-0.273613,-0.621810,0.335930,0.277803,-1.342585,0.090196,0.605497,12.0,0.083333,-0.234299,0.029039,0.538522,-0.489001,-0.373358,0.659449,-1.990779,0.124487,0.479704,-0.124536,-0.390422,-0.160629,8.0,0.125,-0.222011,1.093644e-15,0.870204,-0.255125,2024
2,010006,-3.424522,-0.831956,-0.524963,-0.346527,-0.459700,-1.873369,-0.229927,7.0,0.142857,-1.098709,-0.068391,0.704371,-1.462748,-1.118873,0.390470,0.268626,1.109892,-1.462457,1.508362,-1.946801,1.343425,NaN,NaN,-1.270808,9.0,0.111111,-0.130907,0.014038,0.537879,-0.269475,-2.585604,0.836443,0.496200,1.213392,NaN,-1.028257,0.918161,-0.939297,7.0,0.142857,-0.155566,-0.021526,0.773315,-0.173331,-0.832877,-0.583976,-0.830344,-0.555383,-0.107517,0.592956,0.242409,-0.442070,NaN,-1.134905,-0.403273,-0.097497,11.0,0.090909,-0.377498,0.029039,0.538522,-0.754912,-1.363769,-0.400063,-1.117075,-0.950959,-0.558423,-1.125468,-1.439013,-0.682755,8.0,0.125,-0.954691,1.093644e-15,0.870204,-1.097088,2024
3,010007,NaN,NaN,-3.316094,-0.346527,-3.996805,NaN,NaN,3.0,0.333333,-2.553142,-0.068391,0.704371,-3.527615,NaN,0.272686,0.607081,-0.219069,NaN,-0.573736,0.130845,-1.300386,NaN,NaN,-0.592179,7.0,0.142857,-0.239251,0.014038,0.537879,-0.470903,NaN,NaN,NaN,NaN,NaN,NaN,0.278624,0.287694,2.0,0.500000,0.283159,-0.021526,0.773315,0.393999,-2.789467,-1.346006,0.511414,NaN,0.546132,-0.706898,NaN,-4.827162,NaN,NaN,NaN,2.011485,7.0,0.142857,-0.942929,0.029039,0.538522,-1.804879,-0.373358,1.718961,0.630332,0.124487,-0.558423,-0.124536,0.133873,-0.160629,8.0,0.125,0.173838,1.093644e-15,0.870204,0.199767,2024
5,010011,-0.568162,0.574279,-0.818766,-0.862359,-1.009916,0.819808,-0.964139,7.0,0.142857,-0.404179,-0.068391,0.704371,-0.476720,0.793358,-0.900956,-0.291705,0.394298,-1.677962,-0.313474,0.130845,-0.380799,NaN,NaN,0.425764,9.0,0.111111,-0.202292,0.014038,0.537879,-0.402191,-0.579291,-0.201752,0.219719,0.834150,NaN,0.154930,-0.272556,1.570457,7.0,0.142857,0.246522,-0.021526,0.773315,0.346623,0.100266,0.178053,0.050810,NaN,-0.924578,-1.140182,-2.299412,0.618840,NaN,NaN,NaN,-0.859074,8.0,0.125000,-0.534409,0.029039,0.538522,-1.046286,-0.373358,-0.400063,0.630332,0.124487,0.479704,-0.124536,0.133873,-0.682755,8.0,0.125,-0.026540,1.093644e-15,0.870204,-0.030498,2024

In [15]:
# For 2023

fnames = ['outcome_readmission', 'outcome_safety', 'process', 'ptexp']
f_ext = ['readmission_', 'safety_', 'process_', 'patient_exp_']

with io.capture_output() as captured: 
    df_2023 = pd.read_sas(stars_dir + 'SAS_Downloaded_Databases/2023/actual/outcome_mortality.sas7bdat')
    #df_2023 = df_2023.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
    
    ls = []
    for p in df_2023['PROVIDER_ID'].tolist():
        if len(p) < 6: 
            p = '0' + p
        ls.append(p)
    df_2023['PROVIDER_ID'] = ls
    
    
cols = list(df_2023)
new_cols = []
ind = cols.index('C1')
for i, c in enumerate(cols):
    if i >= ind:
        c = 'mortality_' + c
    new_cols.append(c)
print(new_cols)
df_2023.columns = new_cols

for j, f in enumerate(fnames):
    with io.capture_output() as captured: tdf = pd.read_sas(stars_dir + 'SAS_Downloaded_Databases/2023/actual/' + f + '.sas7bdat')
    #tdf = tdf.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
    
    ls = []
    for p in tdf['PROVIDER_ID'].tolist():
        if len(p) < 6: p = '0' + p
        ls.append(p)
    tdf['PROVIDER_ID'] = ls
    
    cols = list(tdf)
    new_cols = []
    ind = cols.index('C1')
    for i, c in enumerate(cols):
        if i >= ind:
            c = f_ext[j] + c
        new_cols.append(c)
    print(new_cols)
    tdf.columns = new_cols

    df_2023 = df_2023.merge(tdf, on='PROVIDER_ID', how='outer')
    
    
df_2023['Release year'] = ['2023']*df_2023.shape[0]
df_2023 = df_2023.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
df_2023 = df_2023[df_2023['PROVIDER_ID'].isin(prvdrs_2023)]
prvdrs = df_2023['PROVIDER_ID'].unique()

df_2023 = df_2023.loc[:, ~df_2023.columns.str.contains(r'_C\d+$')]

print(len(prvdrs), 'hospitals in 2023')
df_2023.head()

['PROVIDER_ID', 'std_MORT_30_AMI', 'std_MORT_30_CABG', 'std_MORT_30_COPD', 'std_MORT_30_HF', 'std_MORT_30_PN', 'std_MORT_30_STK', 'std_PSI_4_SURG_COMP', 'mortality_C1', 'mortality_C2', 'mortality_C3', 'mortality_C4', 'mortality_C5', 'mortality_C6', 'mortality_C7', 'mortality_total_cnt', 'mortality_measure_wt', 'mortality_score_before_std', 'mortality_Mean', 'mortality_StdDev', 'mortality_grp_score']
['PROVIDER_ID', 'std_EDAC_30_AMI', 'std_EDAC_30_HF', 'std_EDAC_30_PN', 'std_OP_32', 'std_READM_30_CABG', 'std_READM_30_COPD', 'std_READM_30_HIP_KNEE', 'std_READM_30_HOSP_WIDE', 'std_OP_35_ADM', 'std_OP_35_ED', 'std_OP_36', 'readmission_C1', 'readmission_C2', 'readmission_C3', 'readmission_C4', 'readmission_C5', 'readmission_C6', 'readmission_C7', 'readmission_C8', 'readmission_C9', 'readmission_C10', 'readmission_C11', 'readmission_total_cnt', 'readmission_measure_wt', 'readmission_score_before_std', 'readmission_Mean', 'readmission_StdDev', 'readmission_grp_score']
['PROVIDER_ID', 'std_COMP_HIP_KNEE', 'std_HAI_1', 'std_HAI_2', 'std_HAI_3', 'std_HAI_4', 'std_HAI_5', 'std_HAI_6', 'std_PSI_90_SAFETY', 'safety_C1', 'safety_C2', 'safety_C3', 'safety_C4', 'safety_C5', 'safety_C6', 'safety_C7', 'safety_C8', 'safety_total_cnt', 'safety_measure_wt', 'safety_score_before_std', 'safety_Mean', 'safety_StdDev', 'safety_grp_score']
['PROVIDER_ID', 'std_HCP_COVID_19', 'std_IMM_3', 'std_OP_10', 'std_OP_13', 'std_OP_18B', 'std_OP_22', 'std_OP_23', 'std_OP_29', 'std_OP_3B', 'std_OP_8', 'std_PC_01', 'std_SEP_1', 'process_C1', 'process_C2', 'process_C3', 'process_C4', 'process_C5', 'process_C6', 'process_C7', 'process_C8', 'process_C9', 'process_C10', 'process_C11', 'process_C12', 'process_total_cnt', 'process_measure_wt', 'process_score_before_std', 'process_Mean', 'process_StdDev', 'process_grp_score']
['PROVIDER_ID', 'std_H_COMP_1_STAR_RATING', 'std_H_COMP_2_STAR_RATING', 'std_H_COMP_3_STAR_RATING', 'std_H_COMP_5_STAR_RATING', 'std_H_COMP_6_STAR_RATING', 'std_H_COMP_7_STAR_RATING', 'std_H_GLOB_STAR_RATING', 'std_H_INDI_STAR_RATING', 'patient_exp_C1', 'patient_exp_C2', 'patient_exp_C3', 'patient_exp_C4', 'patient_exp_C5', 'patient_exp_C6', 'patient_exp_C7', 'patient_exp_C8', 'patient_exp_total_cnt', 'patient_exp_measure_wt', 'patient_exp_score_before_std', 'patient_exp_Mean', 'patient_exp_StdDev', 'patient_exp_grp_score']
3076 hospitals in 2023

,PROVIDER_ID,std_MORT_30_AMI,std_MORT_30_CABG,std_MORT_30_COPD,std_MORT_30_HF,std_MORT_30_PN,std_MORT_30_STK,std_PSI_4_SURG_COMP,mortality_total_cnt,mortality_measure_wt,mortality_score_before_std,mortality_Mean,mortality_StdDev,mortality_grp_score,std_EDAC_30_AMI,std_EDAC_30_HF,std_EDAC_30_PN,std_OP_32,std_READM_30_CABG,std_READM_30_COPD,std_READM_30_HIP_KNEE,std_READM_30_HOSP_WIDE,std_OP_35_ADM,std_OP_35_ED,std_OP_36,readmission_total_cnt,readmission_measure_wt,readmission_score_before_std,readmission_Mean,readmission_StdDev,readmission_grp_score,std_COMP_HIP_KNEE,std_HAI_1,std_HAI_2,std_HAI_3,std_HAI_4,std_HAI_5,std_HAI_6,std_PSI_90_SAFETY,safety_total_cnt,safety_measure_wt,safety_score_before_std,safety_Mean,safety_StdDev,safety_grp_score,std_HCP_COVID_19,std_IMM_3,std_OP_10,std_OP_13,std_OP_18B,std_OP_22,std_OP_23,std_OP_29,std_OP_3B,std_OP_8,std_PC_01,std_SEP_1,process_total_cnt,process_measure_wt,process_score_before_std,process_Mean,process_StdDev,process_grp_score,std_H_COMP_1_STAR_RATING,std_H_COMP_2_STAR_RATING,std_H_COMP_3_STAR_RATING,std_H_COMP_5_STAR_RATING,std_H_COMP_6_STAR_RATING,std_H_COMP_7_STAR_RATING,std_H_GLOB_STAR_RATING,std_H_INDI_STAR_RATING,patient_exp_total_cnt,patient_exp_measure_wt,patient_exp_score_before_std,patient_exp_Mean,patient_exp_StdDev,patient_exp_grp_score,Release year
0,010001,-0.041613,-2.197810,-0.019543,1.708727,0.366398,-1.543654,-1.741473,7.0,0.142857,-0.495567,-0.05126,0.686658,-0.647058,0.207832,-0.702681,0.286040,0.105508,0.219318,-0.048609,-0.198058,0.924456,0.159253,0.872692,0.062022,11.0,0.090909,0.171616,0.020822,0.530811,0.284081,0.024204,0.444297,0.745807,-0.407579,1.025843,0.314693,-0.315731,-0.212425,8.0,0.125000,0.202389,-0.013939,0.693192,0.312074,-1.039363,0.992908,0.101850,-1.779470,-0.904124,-0.237088,NaN,-0.634479,NaN,0.488322,-1.763346,-0.609958,10.0,0.100000,-0.538475,0.030917,0.556023,-1.024044,-1.07585,-0.175531,-1.051153,0.808598,0.688370,0.037272,-0.445032,0.339427,8.0,0.125,-0.109237,2.611408e-16,0.85451,-0.127836,2023
1,010005,-0.227060,NaN,0.327558,-3.058794,-2.178369,-1.652062,0.037145,6.0,0.166667,-1.125264,-0.05126,0.686658,-1.564103,0.084469,-0.194954,0.138910,-0.342026,NaN,2.081928,0.212564,1.264919,-0.422406,-0.324483,0.683800,10.0,0.100000,0.318272,0.020822,0.530811,0.560369,1.323856,-2.537332,-0.430824,-0.543966,NaN,1.269319,-0.733262,0.400536,7.0,0.142857,-0.178810,-0.013939,0.693192,-0.237844,-0.329039,0.635389,-1.352864,-0.401411,0.265629,-0.237088,0.091268,0.562534,NaN,-1.240294,0.350919,0.143403,11.0,0.090909,-0.137414,0.030917,0.556023,-0.302742,-0.12019,0.826626,-1.051153,-0.306002,-0.421465,0.037272,-0.445032,0.339427,8.0,0.125,-0.142565,2.611408e-16,0.85451,-0.166838,2023
2,010006,-3.843277,-0.631715,0.587885,-0.453288,-0.453103,-2.898752,-0.810482,7.0,0.142857,-1.214676,-0.05126,0.686658,-1.694318,-0.849561,0.276217,-1.455655,1.537615,-2.896632,1.989296,-1.429926,0.924456,NaN,NaN,-0.559756,9.0,0.111111,-0.273772,0.020822,0.530811,-0.554988,-2.141884,0.349265,0.881622,0.601683,NaN,-0.349052,0.890470,-0.764089,7.0,0.142857,-0.075998,-0.013939,0.693192,-0.089526,-1.766600,-0.692541,-0.850000,1.263743,0.305281,0.493077,-0.717089,-0.168974,NaN,0.675589,0.615202,0.085452,11.0,0.090909,-0.068805,0.030917,0.556023,-0.179350,-1.07585,-0.175531,-2.019165,-1.420603,-0.421465,-1.119948,-1.527722,-0.724034,8.0,0.125,-1.060540,2.611408e-16,0.85451,-1.241108,2023
3,010007,NaN,NaN,-1.581501,-1.395705,-2.135237,NaN,NaN,3.0,0.333333,-1.704148,-0.05126,0.686658,-2.407150,NaN,-1.291644,0.727429,-0.968573,NaN,0.136655,NaN,-0.096931,NaN,NaN,0.062022,6.0,0.166667,-0.238507,0.020822,0.530811,-0.488553,NaN,NaN,NaN,NaN,NaN,NaN,0.093366,-0.089833,2.0,0.500000,0.001767,-0.013939,0.693192,0.022657,-2.417730,-0.845764,0.065931,NaN,0.800939,-0.237088,NaN,-1.831492,NaN,NaN,NaN,2.113732,7.0,0.142857,-0.335924,0.030917,0.556023,-0.659760,-0.12019,1.828782,0.884869,0.808598,0.688370,1.194493,0.637658,0.871157,8.0,0.125,0.849217,2.611408e-16,0.85451,0.993806,2023
5,010011,-1.339742,-0.631715,0.240783,-0.453288,-0.151182,-0.893207,0.382842,7.0,0.142857,-0.406501,-0.05126,0.686658,-0.517349,-0.281212,-0.544270,-0.079796,0.553041,-1.458502,-0.697033,-0.198058,0.470506,NaN,NaN,-0.559756,9.0,0.111111,-0.310564,0.020822,0.530811,-0.624302,0.024204,0.483894,-0.046884,1.170201,NaN,-0.369268,-0.231381,0.952201,7.0,0.142857,0.283281,-0.013939,0.693192,0.428770,-0.075352,-0.130725,0.173687,NaN,-0.646382,-0.967252,-2.586416,-4.824023,NaN,NaN,NaN,-1.305368,8.0,0.125000,-1.295229,0.030917,0.556023,-2.385055,-0.12019,-0.175531,0.884869,0.808598,-0.421465,0.037272,0.096313,-0.192304,8.0,0.125,0.114695,2.611408e-16,0.85451,0.134223,2023

In [16]:
# For 2022

fnames = ['outcome_readmission', 'outcome_safety', 'process', 'ptexp']
f_ext = ['readmission_', 'safety_', 'process_', 'patient_exp_']

with io.capture_output() as captured: 
    df_2022 = pd.read_sas(stars_dir + 'SAS_Downloaded_Databases/2022/actual/outcome_mortality.sas7bdat')
    
cols = list(df_2022)
new_cols = []
ind = cols.index('C1')
for i, c in enumerate(cols):
    if i >= ind:
        c = 'mortality_' + c
    new_cols.append(c)
print(new_cols)
df_2022.columns = new_cols

print(df_2022.shape)
for j, f in enumerate(fnames):
    with io.capture_output() as captured: tdf = pd.read_sas(stars_dir + 'SAS_Downloaded_Databases/2022/actual/' + f + '.sas7bdat')
    
    cols = list(tdf)
    new_cols = []
    ind = cols.index('C1')
    for i, c in enumerate(cols):
        if i >= ind:
            c = f_ext[j] + c
        new_cols.append(c)
    print(new_cols)
    tdf.columns = new_cols
    
    print(tdf.shape)
    
    df_2022 = df_2022.merge(tdf, on='PROVIDER_ID', how='outer')
    
print(df_2022.shape)
df_2022['Release year'] = ['2022']*df_2022.shape[0]
print(df_2022.shape)
df_2022 = df_2022.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
print(df_2022.shape)
df_2022 = df_2022[df_2022['PROVIDER_ID'].isin(prvdrs_2022)]
print(df_2022.shape)
prvdrs = df_2022['PROVIDER_ID'].unique()
print(df_2022.shape)

df_2022 = df_2022.loc[:, ~df_2022.columns.str.contains(r'_C\d+$')]

print(len(prvdrs), 'hospitals in 2022')
df_2022.head()

['PROVIDER_ID', 'std_MORT_30_AMI', 'std_MORT_30_CABG', 'std_MORT_30_COPD', 'std_MORT_30_HF', 'std_MORT_30_PN', 'std_MORT_30_STK', 'std_PSI_4_SURG_COMP', 'mortality_C1', 'mortality_C2', 'mortality_C3', 'mortality_C4', 'mortality_C5', 'mortality_C6', 'mortality_C7', 'mortality_total_cnt', 'mortality_measure_wt', 'mortality_score_before_std', 'mortality_Mean', 'mortality_StdDev', 'mortality_grp_score']
(4489, 21)
['PROVIDER_ID', 'std_EDAC_30_AMI', 'std_EDAC_30_HF', 'std_EDAC_30_PN', 'std_OP_32', 'std_READM_30_CABG', 'std_READM_30_COPD', 'std_READM_30_HIP_KNEE', 'std_READM_30_HOSP_WIDE', 'std_OP_35_ADM', 'std_OP_35_ED', 'std_OP_36', 'readmission_C1', 'readmission_C2', 'readmission_C3', 'readmission_C4', 'readmission_C5', 'readmission_C6', 'readmission_C7', 'readmission_C8', 'readmission_C9', 'readmission_C10', 'readmission_C11', 'readmission_total_cnt', 'readmission_measure_wt', 'readmission_score_before_std', 'readmission_Mean', 'readmission_StdDev', 'readmission_grp_score']
(4489, 29)
['PROVIDER_ID', 'std_COMP_HIP_KNEE', 'std_HAI_1', 'std_HAI_2', 'std_HAI_3', 'std_HAI_4', 'std_HAI_5', 'std_HAI_6', 'std_PSI_90_SAFETY', 'safety_C1', 'safety_C2', 'safety_C3', 'safety_C4', 'safety_C5', 'safety_C6', 'safety_C7', 'safety_C8', 'safety_total_cnt', 'safety_measure_wt', 'safety_score_before_std', 'safety_Mean', 'safety_StdDev', 'safety_grp_score']
(4489, 23)
['PROVIDER_ID', 'std_IMM_3', 'std_OP_22', 'std_OP_23', 'std_OP_29', 'std_OP_33', 'std_PC_01', 'std_SEP_1', 'std_OP_3B', 'std_OP_18B', 'std_OP_8', 'std_OP_10', 'std_OP_13', 'process_C1', 'process_C2', 'process_C3', 'process_C4', 'process_C5', 'process_C6', 'process_C7', 'process_C8', 'process_C9', 'process_C10', 'process_C11', 'process_C12', 'process_total_cnt', 'process_measure_wt', 'process_score_before_std', 'process_Mean', 'process_StdDev', 'process_grp_score']
(4489, 31)
['PROVIDER_ID', 'std_H_COMP_1_STAR_RATING', 'std_H_COMP_2_STAR_RATING', 'std_H_COMP_3_STAR_RATING', 'std_H_COMP_5_STAR_RATING', 'std_H_COMP_6_STAR_RATING', 'std_H_COMP_7_STAR_RATING', 'std_H_GLOB_STAR_RATING', 'std_H_INDI_STAR_RATING', 'patient_exp_C1', 'patient_exp_C2', 'patient_exp_C3', 'patient_exp_C4', 'patient_exp_C5', 'patient_exp_C6', 'patient_exp_C7', 'patient_exp_C8', 'patient_exp_total_cnt', 'patient_exp_measure_wt', 'patient_exp_score_before_std', 'patient_exp_Mean', 'patient_exp_StdDev', 'patient_exp_grp_score']
(4489, 23)
(4489, 123)
(4489, 124)
(4489, 124)
(3121, 124)
(3121, 124)
3121 hospitals in 2022

,PROVIDER_ID,std_MORT_30_AMI,std_MORT_30_CABG,std_MORT_30_COPD,std_MORT_30_HF,std_MORT_30_PN,std_MORT_30_STK,std_PSI_4_SURG_COMP,mortality_total_cnt,mortality_measure_wt,mortality_score_before_std,mortality_Mean,mortality_StdDev,mortality_grp_score,std_EDAC_30_AMI,std_EDAC_30_HF,std_EDAC_30_PN,std_OP_32,std_READM_30_CABG,std_READM_30_COPD,std_READM_30_HIP_KNEE,std_READM_30_HOSP_WIDE,std_OP_35_ADM,std_OP_35_ED,std_OP_36,readmission_total_cnt,readmission_measure_wt,readmission_score_before_std,readmission_Mean,readmission_StdDev,readmission_grp_score,std_COMP_HIP_KNEE,std_HAI_1,std_HAI_2,std_HAI_3,std_HAI_4,std_HAI_5,std_HAI_6,std_PSI_90_SAFETY,safety_total_cnt,safety_measure_wt,safety_score_before_std,safety_Mean,safety_StdDev,safety_grp_score,std_IMM_3,std_OP_22,std_OP_23,std_OP_29,std_OP_33,std_PC_01,std_SEP_1,std_OP_3B,std_OP_18B,std_OP_8,std_OP_10,std_OP_13,process_total_cnt,process_measure_wt,process_score_before_std,process_Mean,process_StdDev,process_grp_score,std_H_COMP_1_STAR_RATING,std_H_COMP_2_STAR_RATING,std_H_COMP_3_STAR_RATING,std_H_COMP_5_STAR_RATING,std_H_COMP_6_STAR_RATING,std_H_COMP_7_STAR_RATING,std_H_GLOB_STAR_RATING,std_H_INDI_STAR_RATING,patient_exp_total_cnt,patient_exp_measure_wt,patient_exp_score_before_std,patient_exp_Mean,patient_exp_StdDev,patient_exp_grp_score,Release year
0,010001,0.703271,-1.054647,-0.072635,1.355101,0.507204,-3.873239,-1.364075,7.0,0.142857,-0.542717,0.000879,0.641984,-0.846744,0.012064,-0.457136,0.497621,1.664542,-0.606328,-1.470080,-1.684933,-0.053004,0.602150,-0.703618,0.623486,11.0,0.090909,-0.143203,0.027686,0.531111,-0.321758,-0.427377,0.325583,0.722043,0.295950,1.045465,0.077072,-0.002603,1.040003,8.0,0.125000,0.384517,0.002796,0.645363,0.591483,0.643289,-0.863287,NaN,0.009932,NaN,0.442175,-0.264434,NaN,-0.906488,-0.897899,0.376713,-0.520081,9.0,0.111111,-0.220009,0.040971,0.815466,-0.320038,-0.536306,-0.084743,-0.269007,-0.072623,0.801375,-0.116805,0.284308,0.481635,8.0,0.125,0.060979,-5.363828e-17,0.84576,0.072100,2022
1,010005,-0.113897,NaN,-0.359269,-3.038802,-1.230466,-1.234330,0.765784,6.0,0.166667,-0.868497,0.000879,0.641984,-1.354201,1.031113,-0.432991,-0.296054,1.172588,NaN,1.650104,0.258268,1.220694,1.951595,0.635548,0.623486,10.0,0.100000,0.781435,0.027686,0.531111,1.419195,0.866214,0.354127,-0.227217,0.485385,NaN,-0.692282,-0.320719,-1.105376,7.0,0.142857,-0.091410,0.002796,0.645363,-0.145974,0.125136,-0.329809,-0.478581,0.434506,0.689565,-0.218358,0.264906,NaN,0.478618,-0.249889,-1.577127,1.347285,11.0,0.090909,0.044205,0.040971,0.815466,0.003965,-0.536306,0.876653,-0.269007,-0.072623,0.801375,-0.116805,-0.254812,-0.048857,8.0,0.125,0.047452,-5.363828e-17,0.84576,0.056106,2022
2,010006,-3.484718,-0.531852,0.405087,-0.616522,-0.386455,-0.927480,-1.846630,7.0,0.142857,-1.055510,0.000879,0.641984,-1.645507,0.284947,0.516707,-1.339736,2.015937,-0.816654,1.549453,-1.490613,-0.371429,NaN,NaN,0.060418,9.0,0.111111,0.045448,0.027686,0.531111,0.033444,-1.720968,0.341894,0.587157,0.587502,NaN,-0.326058,0.435881,-1.105376,7.0,0.142857,-0.171424,0.002796,0.645363,-0.269957,0.297854,0.203668,NaN,0.131239,NaN,0.442175,-1.558378,NaN,-0.634008,1.753052,-1.738453,1.667405,9.0,0.111111,0.062728,0.040971,0.815466,0.026680,-0.536306,-0.084743,-2.195088,-1.068170,-1.291935,-1.058688,-0.254812,-0.048857,8.0,0.125,-0.817325,-5.363828e-17,0.84576,-0.966379,2022
3,010007,NaN,NaN,-0.645902,-0.729187,-1.826238,NaN,NaN,3.0,0.333333,-1.067109,0.000879,0.641984,-1.663574,NaN,-0.131181,-0.335737,-1.357461,NaN,-0.262267,NaN,-0.371429,NaN,NaN,0.060418,6.0,0.166667,-0.399609,0.027686,0.531111,-0.804531,NaN,NaN,NaN,NaN,NaN,NaN,1.201078,0.306057,2.0,0.500000,0.753568,0.002796,0.645363,1.163333,NaN,-0.329809,NaN,0.131239,NaN,NaN,2.382268,NaN,0.751098,NaN,0.699366,NaN,5.0,0.200000,0.726832,0.040971,0.815466,0.841066,-0.536306,-0.084743,-0.269007,0.922923,0.801375,0.825078,-0.254812,1.012127,8.0,0.125,0.302079,-5.363828e-17,0.84576,0.357169,2022
5,010011,-2.054673,-1.446744,-0.645902,0.172127,-0.287159,-0.252410,-0.118808,7.0,0.142857,-0.661939,0.000879,0.641984,-1.032452,-1.134900,-2.416895,-0.871468,-0.092437,-1.868286,0.240989,-0.324692,-1.326703,NaN,NaN,0.060418,9.0,0.111111,-0.859330,0.027686,0.531111,-1.670115,-0.211778,0.411215,0.217907,-0.272356,NaN,0.328319,0.659421,-0.371431,7.0,0.142857,0.108757,0.002796,0.645363,0.164188,NaN,-0.863287,NaN,NaN,-1.087459,NaN,-1.499562,NaN,-0.906488,NaN,-0.214816,NaN,5.0,0.200000,-0.914322,0.040971,0.815466,-1.171470,-0.536306,-0.084743,-0.269007,-0.072623,-0.245280,-0.116805,-0.254812,-0.579349,8.0,0.125,-0.269866,-5.363828e-17,0.84576,-0.319080,2022

In [17]:
# For 2021

fnames = ['outcome_readmission', 'outcome_safety', 'process', 'ptexp']
f_ext = ['readmission_', 'safety_', 'process_', 'patient_exp_']

with io.capture_output() as captured: 
    df_2021 = pd.read_sas(stars_dir + 'SAS_Downloaded_Databases/2021/actual/outcome_mortality.sas7bdat')
    
cols = list(df_2021)
new_cols = []
ind = cols.index('C1')
for i, c in enumerate(cols):
    if i >= ind:
        c = 'mortality_' + c
    new_cols.append(c)
print(new_cols)
df_2021.columns = new_cols

for j, f in enumerate(fnames):
    with io.capture_output() as captured: tdf = pd.read_sas(stars_dir + 'SAS_Downloaded_Databases/2021/actual/' + f + '.sas7bdat')
    
    cols = list(tdf)
    new_cols = []
    ind = cols.index('C1')
    for i, c in enumerate(cols):
        if i >= ind:
            c = f_ext[j] + c
        new_cols.append(c)
    print(new_cols)
    tdf.columns = new_cols

    df_2021 = df_2021.merge(tdf, on='PROVIDER_ID', how='outer')
    
    
df_2021['Release year'] = ['2021']*df_2021.shape[0]
df_2021 = df_2021.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
df_2021 = df_2021[df_2021['PROVIDER_ID'].isin(prvdrs_2021)]
prvdrs = df_2021['PROVIDER_ID'].unique()

df_2021 = df_2021.loc[:, ~df_2021.columns.str.contains(r'_C\d+$')]

print(len(prvdrs), 'hospitals in 2021')
df_2021.head()

['PROVIDER_ID', 'std_MORT_30_AMI', 'std_MORT_30_CABG', 'std_MORT_30_COPD', 'std_MORT_30_HF', 'std_MORT_30_PN', 'std_MORT_30_STK', 'std_PSI_4_SURG_COMP', 'mortality_C1', 'mortality_C2', 'mortality_C3', 'mortality_C4', 'mortality_C5', 'mortality_C6', 'mortality_C7', 'mortality_total_cnt', 'mortality_measure_wt', 'mortality_score_before_std', 'mortality_Mean', 'mortality_StdDev', 'mortality_grp_score']
['PROVIDER_ID', 'std_EDAC_30_AMI', 'std_EDAC_30_HF', 'std_EDAC_30_PN', 'std_OP_32', 'std_READM_30_CABG', 'std_READM_30_COPD', 'std_READM_30_HIP_KNEE', 'std_READM_30_HOSP_WIDE', 'std_OP_35_ADM', 'std_OP_35_ED', 'std_OP_36', 'readmission_C1', 'readmission_C2', 'readmission_C3', 'readmission_C4', 'readmission_C5', 'readmission_C6', 'readmission_C7', 'readmission_C8', 'readmission_C9', 'readmission_C10', 'readmission_C11', 'readmission_total_cnt', 'readmission_measure_wt', 'readmission_score_before_std', 'readmission_Mean', 'readmission_StdDev', 'readmission_grp_score']
['PROVIDER_ID', 'std_COMP_HIP_KNEE', 'std_HAI_1', 'std_HAI_2', 'std_HAI_3', 'std_HAI_4', 'std_HAI_5', 'std_HAI_6', 'std_PSI_90_SAFETY', 'safety_C1', 'safety_C2', 'safety_C3', 'safety_C4', 'safety_C5', 'safety_C6', 'safety_C7', 'safety_C8', 'safety_total_cnt', 'safety_measure_wt', 'safety_score_before_std', 'safety_Mean', 'safety_StdDev', 'safety_grp_score']
['PROVIDER_ID', 'std_IMM_3', 'std_OP_22', 'std_OP_23', 'std_OP_29', 'std_OP_30', 'std_OP_33', 'std_PC_01', 'std_SEP_1', 'std_OP_3B', 'std_OP_18B', 'std_ED_2B', 'std_OP_8', 'std_OP_10', 'std_OP_13', 'process_C1', 'process_C2', 'process_C3', 'process_C4', 'process_C5', 'process_C6', 'process_C7', 'process_C8', 'process_C9', 'process_C10', 'process_C11', 'process_C12', 'process_C13', 'process_C14', 'process_total_cnt', 'process_measure_wt', 'process_score_before_std', 'process_Mean', 'process_StdDev', 'process_grp_score']
['PROVIDER_ID', 'std_H_COMP_1_STAR_RATING', 'std_H_COMP_2_STAR_RATING', 'std_H_COMP_3_STAR_RATING', 'std_H_COMP_5_STAR_RATING', 'std_H_COMP_6_STAR_RATING', 'std_H_COMP_7_STAR_RATING', 'std_H_GLOB_STAR_RATING', 'std_H_INDI_STAR_RATING', 'patient_exp_C1', 'patient_exp_C2', 'patient_exp_C3', 'patient_exp_C4', 'patient_exp_C5', 'patient_exp_C6', 'patient_exp_C7', 'patient_exp_C8', 'patient_exp_total_cnt', 'patient_exp_measure_wt', 'patient_exp_score_before_std', 'patient_exp_Mean', 'patient_exp_StdDev', 'patient_exp_grp_score']
3355 hospitals in 2021

,PROVIDER_ID,std_MORT_30_AMI,std_MORT_30_CABG,std_MORT_30_COPD,std_MORT_30_HF,std_MORT_30_PN,std_MORT_30_STK,std_PSI_4_SURG_COMP,mortality_total_cnt,mortality_measure_wt,mortality_score_before_std,mortality_Mean,mortality_StdDev,mortality_grp_score,std_EDAC_30_AMI,std_EDAC_30_HF,std_EDAC_30_PN,std_OP_32,std_READM_30_CABG,std_READM_30_COPD,std_READM_30_HIP_KNEE,std_READM_30_HOSP_WIDE,std_OP_35_ADM,std_OP_35_ED,std_OP_36,readmission_total_cnt,readmission_measure_wt,readmission_score_before_std,readmission_Mean,readmission_StdDev,readmission_grp_score,std_COMP_HIP_KNEE,std_HAI_1,std_HAI_2,std_HAI_3,std_HAI_4,std_HAI_5,std_HAI_6,std_PSI_90_SAFETY,safety_total_cnt,safety_measure_wt,safety_score_before_std,safety_Mean,safety_StdDev,safety_grp_score,std_IMM_3,std_OP_22,std_OP_23,std_OP_29,std_OP_30,std_OP_33,std_PC_01,std_SEP_1,std_OP_3B,std_OP_18B,std_ED_2B,std_OP_8,std_OP_10,std_OP_13,process_total_cnt,process_measure_wt,process_score_before_std,process_Mean,process_StdDev,process_grp_score,std_H_COMP_1_STAR_RATING,std_H_COMP_2_STAR_RATING,std_H_COMP_3_STAR_RATING,std_H_COMP_5_STAR_RATING,std_H_COMP_6_STAR_RATING,std_H_COMP_7_STAR_RATING,std_H_GLOB_STAR_RATING,std_H_INDI_STAR_RATING,patient_exp_total_cnt,patient_exp_measure_wt,patient_exp_score_before_std,patient_exp_Mean,patient_exp_StdDev,patient_exp_grp_score,Release year
0,010001,0.730853,-2.055159,0.069106,0.103403,-0.022557,-1.941449,-0.327016,7.0,0.142857,-0.491831,-0.004941,0.64666,-0.752932,-0.027028,-0.705673,1.039984,2.185101,-1.542989,-1.037529,-1.164917,-0.070634,1.182600,-1.185780,1.207127,11.0,0.090909,-0.010885,0.027901,0.551294,-0.070355,0.303431,-0.078888,0.680925,0.244905,1.037183,0.403644,0.098335,0.319230,8.0,0.125000,0.376096,0.009921,0.658437,0.556127,0.644574,-0.979501,NaN,-0.459111,0.466001,NaN,0.473469,0.031191,NaN,-0.761776,-0.054072,0.140655,-0.102729,0.684379,11.0,0.090909,0.007553,0.037755,0.600242,-0.050316,-0.537213,-0.085263,-0.269656,-0.073296,0.801144,-0.115323,0.284361,0.478432,8.0,0.125,0.060398,-1.104271e-16,0.845613,0.071425,2021
1,010005,-1.095515,NaN,-1.273727,-3.077512,-1.846949,-2.261620,-1.335906,6.0,0.166667,-1.815205,-0.004941,0.64666,-2.799407,0.539823,-0.244350,-0.744184,0.119295,NaN,0.896062,0.210441,-0.420048,0.989506,-0.195267,-0.516355,10.0,0.100000,0.063492,0.027901,0.551294,0.064559,0.303431,1.102714,-0.609029,0.459400,NaN,-1.712026,0.039355,-0.043766,7.0,0.142857,-0.065703,0.009921,0.658437,-0.114854,0.126670,-0.346365,-0.150232,-0.401490,0.144736,0.716782,-0.340110,0.504799,0.076084,0.572659,0.228145,-0.410303,-1.202673,0.412738,14.0,0.071429,-0.004897,0.037755,0.600242,-0.071058,-0.537213,0.874962,-0.269656,-0.073296,0.801144,-0.115323,-0.254265,-0.052073,8.0,0.125,0.046785,-1.104271e-16,0.845613,0.055327,2021
2,010006,-2.921882,-1.298828,-0.915638,-0.590615,-1.318836,0.683952,-2.656890,7.0,0.142857,-1.288391,-0.004941,0.64666,-1.984738,0.479089,0.888725,-0.932855,0.048060,-0.333820,0.992741,-1.164917,0.395251,NaN,NaN,-0.516355,9.0,0.111111,-0.016009,0.027901,0.551294,-0.079649,-0.649202,1.102714,0.856593,-0.011884,NaN,0.242305,0.332149,-0.406762,7.0,0.142857,0.209416,0.009921,0.658437,0.302983,0.299305,0.286770,NaN,-0.459111,-0.417479,NaN,0.473469,-1.567236,NaN,-0.211057,-0.148144,-0.439300,-1.249813,0.793035,11.0,0.090909,-0.239960,0.037755,0.600242,-0.462672,-0.537213,-0.085263,-2.193860,-1.067899,-1.292453,-1.055803,-0.254265,-0.052073,8.0,0.125,-0.817354,-1.104271e-16,0.845613,-0.966582,2021
3,010007,NaN,NaN,-0.468027,-1.515972,-2.231032,-1.109004,NaN,4.0,0.250000,-1.331009,-0.004941,0.64666,-2.050643,NaN,-1.009175,-0.498092,-0.877991,NaN,0.219305,NaN,-0.652991,NaN,NaN,0.058139,6.0,0.166667,-0.460134,0.027901,0.551294,-0.885254,NaN,NaN,NaN,NaN,NaN,NaN,1.229489,0.371087,2.0,0.500000,0.800288,0.009921,0.658437,1.200369,NaN,-0.979501,NaN,-4.377296,-0.176530,NaN,NaN,2.280829,NaN,0.720929,0.496922,NaN,-0.401285,NaN,7.0,0.142857,-0.347990,0.037755,0.600242,-0.642649,-0.537213,-0.085263,-0.269656,0.921307,0.801144,0.825157,-0.254265,1.008938,8.0,0.125,0.301269,-1.104271e-16,0.845613,0.356272,2021
4,010008,NaN,NaN,-1.810860,-0.301441,-1.030774,NaN,NaN,3.0,0.333333,-1.047692,-0.004941,0.64666,-1.612519,NaN,NaN,0.342723,-0.735521,NaN,0.219305,NaN,0.861136,NaN,NaN,NaN,4.0,0.250000,0.171911,0.027901,0.551294,0.261221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.008091,1.0,1.000000,0.008091,0.009921,0.658437,-0.002780,-3.584977,0.286770,NaN,-1.726759,0.385685,NaN,NaN,-0.975226,NaN,1.081015,0.174389,NaN,0.494383,NaN,8.0,0.125000,-0.483090,0.037755,0.600242,-0.867725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,-1.104271e-16,0.845613,NaN,2021

In [18]:
print(df_2027.shape)
print(df_2026.shape)
print(df_2025.shape)
print(df_2024.shape)
print(df_2023.shape)
print(df_2022.shape)
print(df_2021.shape)

(3206, 82)
(3203, 84)
(2891, 78)
(2847, 78)
(3076, 78)
(3121, 78)
(3355, 80)

In [19]:
ls = np.setdiff1d(list(df_2027), list(df_2026)) # in 2027, not in 2026
print(ls, 'in 2027, not in 2026')

ls = np.setdiff1d(list(df_2026), list(df_2025)) # in 2026, not in 2025
print(ls, 'in 2026, not in 2025')

ls = np.setdiff1d(list(df_2025), list(df_2024)) # in 2025, not in 2024
print(ls, 'in 2025, not in 2024')

ls = np.setdiff1d(list(df_2024), list(df_2023)) # in 2024, not in 2023
print(ls, 'in 2024, not in 2023')

ls = np.setdiff1d(list(df_2023), list(df_2022)) # in 2023, not in 2022
print(ls, 'in 2023, not in 2022')

ls = np.setdiff1d(list(df_2022), list(df_2021)) # in 2022, not in 2021
print(ls, 'in 2022, not in 2021')


tdf = df_2027.merge(df_2026, how='outer')
tdf = tdf.merge(df_2025, how='outer')
tdf = tdf.merge(df_2024, how='outer')
tdf = tdf.merge(df_2023, how='outer')
tdf = tdf.merge(df_2022, how='outer')
tdf = tdf.merge(df_2021, how='outer')
main_df = main_df.merge(tdf, how='outer', on=['PROVIDER_ID', 'Release year'])

print(main_df.shape)

print(len(main_df['PROVIDER_ID'].unique()))
main_df.sort_values(by=['PROVIDER_ID'], ascending=True, inplace=True)

ls = main_df['PROVIDER_ID'].unique().tolist()

print(ls[:10])

main_df.head()

['mortality_mean' 'mortality_sd' 'patient_exp_mean' 'patient_exp_sd'
 'process_mean' 'process_sd' 'readmission_mean' 'readmission_sd'
 'safety_mean' 'safety_sd'] in 2027, not in 2026
['std_H_CLEAN_LINEAR_SCORE' 'std_H_COMP_1_LINEAR_SCORE'
 'std_H_COMP_2_LINEAR_SCORE' 'std_H_COMP_3_LINEAR_SCORE'
 'std_H_COMP_5_LINEAR_SCORE' 'std_H_COMP_6_LINEAR_SCORE'
 'std_H_COMP_7_LINEAR_SCORE' 'std_H_HSP_RATING_LINEAR_SCORE'
 'std_H_QUIET_LINEAR_SCORE' 'std_H_RECMND_LINEAR_SCORE' 'std_Hybrid_HWM'
 'std_Hybrid_HWR' 'std_O-COMP-1' 'std_O-COMP-2' 'std_O-COMP-3'
 'std_O-PATIENT-RATE' 'std_O-PATIENT-REC'] in 2026, not in 2025
['std_SAFE_USE_OF_OPIOIDS'] in 2025, not in 2024
[] in 2024, not in 2023
['std_HCP_COVID_19'] in 2023, not in 2022
[] in 2022, not in 2021
(21699, 137)
3651
['010001', '010005', '010006', '010007', '010008', '010011', '010012', '010016', '010019', '010021']

,PROVIDER_ID,Std_Outcomes_Mortality_score,Outcomes_Mortality_cnt,Std_Outcomes_Safety_score,Outcomes_Safety_cnt,Std_Outcomes_Readmission_score,Outcomes_Readmission_cnt,Std_PatientExp_score,Patient_Experience_cnt,Std_Process_score,Process_cnt,std_weight_Mortality,std_weight_Safety,std_weight_Readmission,std_weight_PatientExperience,std_weight_Process,weight_Outcomes_Mortality,weight_Outcomes_Safety,weight_Outcomes_Readmission,weight_PatientExperience,weight_Process,summary_score,Total_measure_group_cnt,MortSafe_Group_cnt,report_indicator,cnt_grp,star,Release year,std_weight_safety,Outcomes_safety_cnt,std_MORT_30_AMI,std_MORT_30_CABG,std_MORT_30_COPD,std_MORT_30_HF,std_MORT_30_PN,std_MORT_30_STK,std_PSI_4_SURG_COMP,std_Hybrid_HWM,mortality_total_cnt,mortality_measure_wt,mortality_score_before_std,mortality_grp_score,mortality_mean,mortality_sd,std_EDAC_30_AMI,std_EDAC_30_HF,std_EDAC_30_PN,std_OP_32,std_OP_35_ADM,std_OP_35_ED,std_OP_36,std_READM_30_CABG,std_READM_30_COPD,std_READM_30_HIP_KNEE,std_Hybrid_HWR,readmission_total_cnt,readmission_measure_wt,readmission_score_before_std,readmission_grp_score,readmission_mean,readmission_sd,std_COMP_HIP_KNEE,std_PSI_90_SAFETY,std_HAI_1,std_HAI_2,std_HAI_3,std_HAI_4,std_HAI_5,std_HAI_6,safety_total_cnt,safety_measure_wt,safety_score_before_std,safety_grp_score,safety_mean,safety_sd,std_IMM_3,std_OP_18B,std_OP_22,std_OP_23,std_OP_29,std_SEP_1,std_SAFE_USE_OF_OPIOIDS,std_OP_13,std_OP_8,std_OP_10,process_total_cnt,process_measure_wt,process_score_before_std,process_grp_score,process_mean,process_sd,std_H_COMP_1_LINEAR_SCORE,std_H_COMP_2_LINEAR_SCORE,std_H_COMP_5_LINEAR_SCORE,std_H_COMP_6_LINEAR_SCORE,std_H_CLEAN_LINEAR_SCORE,std_H_QUIET_LINEAR_SCORE,std_H_HSP_RATING_LINEAR_SCORE,std_H_RECMND_LINEAR_SCORE,std_O-COMP-1,std_O-COMP-2,std_O-COMP-3,std_O-PATIENT-RATE,std_O-PATIENT-REC,patient_exp_total_cnt,patient_exp_measure_wt,patient_exp_score_before_std,patient_exp_grp_score,patient_exp_mean,patient_exp_sd,mortality_Mean,mortality_StdDev,readmission_Mean,readmission_StdDev,safety_Mean,safety_StdDev,process_Mean,process_StdDev,std_H_COMP_3_LINEAR_SCORE,std_H_COMP_7_LINEAR_SCORE,patient_exp_Mean,patient_exp_StdDev,std_READM_30_HOSP_WIDE,std_HCP_COVID_19,std_PC_01,std_H_COMP_1_STAR_RATING,std_H_COMP_2_STAR_RATING,std_H_COMP_3_STAR_RATING,std_H_COMP_5_STAR_RATING,std_H_COMP_6_STAR_RATING,std_H_COMP_7_STAR_RATING,std_H_GLOB_STAR_RATING,std_H_INDI_STAR_RATING,std_OP_3B,std_OP_33,std_OP_30,std_ED_2B
0,010001,-0.752932,7,0.556127,NaN,-0.070355,11,0.071425,8,-0.050316,11,0.22,NaN,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.049100,5,2,1,3.0,3.0,2021,0.22,8.0,0.730853,-2.055159,0.069106,0.103403,-0.022557,-1.941449,-0.327016,NaN,7.0,0.142857,-0.491831,-0.752932,NaN,NaN,-0.027028,-0.705673,1.039984,2.185101,1.182600,-1.185780,1.207127,-1.542989,-1.037529,-1.164917,NaN,11.0,0.090909,-0.010885,-0.070355,NaN,NaN,0.303431,0.319230,-0.078888,0.680925,0.244905,1.037183,0.403644,0.098335,8.0,0.125000,0.376096,0.556127,NaN,NaN,0.644574,-0.761776,-0.979501,NaN,-0.459111,0.031191,NaN,0.684379,0.140655,-0.102729,11.0,0.090909,0.007553,-0.050316,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,0.125,0.060398,0.071425,NaN,NaN,-0.004941,0.646660,0.027901,0.551294,0.009921,0.658437,0.037755,0.600242,NaN,NaN,-1.104271e-16,0.845613,-0.070634,NaN,0.473469,-0.537213,-0.085263,-0.269656,-0.073296,0.801144,-0.115323,0.284361,0.478432,NaN,NaN,0.466001,-0.054072
1,010001,-0.846744,7,0.591483,NaN,-0.321758,11,0.072100,8,-0.320038,9,0.22,NaN,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.149487,5,2,1,3.0,3.0,2022,0.22,8.0,0.703271,-1.054647,-0.072635,1.355101,0.507204,-3.873239,-1.364075,NaN,7.0,0.142857,-0.542717,-0.846744,NaN,NaN,0.012064,-0.457136,0.497621,1.664542,0.602150,-0.703618,0.623486,-0.606328,-1.470080,-1.684933,NaN,11.0,0.090909,-0.143203,-0.321758,NaN,NaN,-0.427377,1.040003,0.325583,0.722043,0.295950,1.045465,0.077072,-0.002603,8.0,0.125000,0.384517,0.591483,NaN,NaN,0.643289,-0.906488,-0.863287,NaN,0.009932,-0.264434,NaN,-0.520081,-0.897899,0.376713,9.0,0.111111,-0.220009,-0.320038,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,0.125,0.060979,0.072100,NaN,NaN,0.000879,0.641984,0.027686,0.531111,0.002796,0.645363,0.040971,0.815466,NaN,NaN,-5.363828e-17,0.845760,-0.053004,NaN,0.442175,-0.536306,-0.084743,-0.269007,-0.072623,0.801375,-0.116805,0.284308,0.481635,NaN,NaN,NaN,NaN
2,010001,-0.647058,7,0.312074,NaN,0.284081,11,-0.127836,8,-1.024044,10,0.22,NaN,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.162208,5,2,1,3.0,3.0,2023,0.22,8.0,-0.041613,-2.197810,-0.019543,1.708727,0.366398,-1.543654,-1.741473,NaN,7.0,0.142857,-0.495567,-0.647058,NaN,NaN,0.207832,-0.702681,0.286040,0.105508,0.159253,0.872692,0.062022,0.219318,-0.048609,-0.198058,NaN,11.0,0.090909,0.171616,0.284081,NaN,NaN,0.024204,-0.212425,0.444297,0.745807,-0.407579,1.025843,0.314693,-0.315731,8.0,0.125000,0.202389,0.312074,NaN,NaN,0.992908,-0.904124,-0.237088,NaN,-0.634479,-0.609958,NaN,-1.779470,0.488322,0.101850,10.0,0.100000,-0.538475,-1.024044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,0.125,-0.109237,-0.127836,NaN,NaN,-0.051260,0.686658,0.020822,0.530811,-0.013939,0.693192,0.030917,0.556023,NaN,NaN,2.611408e-16,0.854510,0.924456,-1.039363,-1.763346,-1.075850,-0.175531,-1.051153,0.808598,0.688370,0.037272,-0.445032,0.339427,NaN,NaN,NaN,NaN
3,010001,0.007071,7,-0.146867,NaN,0.230867,11,0.137779,8,-0.677624,10,0.22,NaN,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.030968,5,2,1,3.0,3.0,2024,0.22,7.0,0.470514,-1.535074,0.282996,1.510467,0.129818,-0.554262,-0.748332,NaN,7.0,0.142857,-0.063411,0.007071,NaN,NaN,1.123231,-0.791585,-0.633920,0.292070,-1.032330,0.626949,-0.252865,0.584835,0.293805,0.886353,NaN,11.0,0.090909,0.138216,0.230867,NaN,NaN,0.879845,-1.162386,-0.232451,0.488068,-0.711660,NaN,-0.210159,0.003034,7.0,0.142857,-0.135101,-0.146867,NaN,NaN,0.940083,-0.942734,-1.140182,NaN,-3.129707,0.371166,NaN,0.419351,0.000412,-0.029295,10.0,0.100000,-0.335877,-0.677624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,0.125,0.119895,0.137779,NaN,NaN,-0.068391,0.704371,0.014038,0.537879,-0.021526,0.773315,0.029039,0.538522,NaN,NaN,1.093644e-15,0.870204,0.423838,-0.431525,0.583665,-0.373358,-0.400063,-0.243371,0.124487,0.479704,0.876397,0.133873,0.361496,NaN,NaN,NaN,NaN
4,010001,0.296110,7,0.344883,NaN,0.361406,11,0.042072,8,-0.484678,11,0.22,NaN,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,0.171622,5,2,1,3.0,4.0,2025,0.22,7.0,1.405923,-1.045370,1.011496,0.650904,-0.315375,0.023766,-0.732077,NaN,7.0,0.142857,0.142753,0.296110,NaN,NaN,1.024273,-0.368843,-0.448127,0.289973,-1.028886,0.627910,-0.257980,0.607499,0.859382,0.192452,NaN,11.0,0.090909,0.206001,0.361406,NaN,NaN,0.698729,0.103001,0.303670,0.739078,-0.467783,NaN,0.476446,-0.105703,7.0,0.142857,0.249634,0.344883,NaN,NaN,1.044716,-1.062058,-1.138829,NaN,-3.171398,0.449772,0.563049,0.781373,0.588011,0.080291,11.0,0.090909,-0.204464,-0.484678,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,0.125,0.036435,0.042072,NaN,NaN,-0.073484,0.730255,0.013108,0.533730,-0.019030,0.779001,0.028411,0.480473,NaN,NaN,4.899789e-17,0.866021,0.768359,-0.525017,0.140984,-1.154064,0.570761,-0.231671,-0.254181,-0.312251,0.933177,0.719371,0.020336,NaN,NaN,NaN,NaN

## Load SAS pack input files
These data originate from Care Compare

In [20]:
df_2027 = pd.read_csv(stars_dir + "2027/predictions_From_May_2026/data_for_2027_predictions_from_May2026.csv")
df_2027['Release year'] = ['2027']*df_2027.shape[0]
df_2027 = df_2027.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)

ls = []
for p in df_2027['PROVIDER_ID'].tolist():
    p = int(p)
    p = str(p)
    if '666666' in p:
        p = p[:-6]
        p = p + 'F'
    while len(p) < 6:
        p = '0' + p
    ls.append(p)

df_2027['PROVIDER_ID'] = ls
df_2027 = df_2027[df_2027['PROVIDER_ID'].isin(prvdrs_2027)]

print(df_2027.shape)
prvdrs = df_2027['PROVIDER_ID'].unique()
print(len(prvdrs), 'hospitals in 2027 prognostications')

df_2027.head()

(3206, 152)
3206 hospitals in 2027 prognostications

,PROVIDER_ID,IMM_3,IMM_3_DEN,OP_18B,OP_18B_DEN,OP_22,OP_22_DEN,OP_23,OP_23_DEN,OP_29,OP_29_DEN,SEP_1,SEP_1_DEN,SAFE_USE_OF_OPIOIDS,SAFE_USE_OF_OPIOIDS_DEN,MORT_30_AMI,MORT_30_AMI_DEN,MORT_30_CABG,MORT_30_CABG_DEN,MORT_30_COPD,MORT_30_COPD_DEN,MORT_30_HF,MORT_30_HF_DEN,MORT_30_PN,MORT_30_PN_DEN,MORT_30_STK,MORT_30_STK_DEN,PSI_4_SURG_COMP,PSI_4_SURG_COMP_DEN,COMP_HIP_KNEE,COMP_HIP_KNEE_DEN,PSI_90_SAFETY,PSI_90_SAFETY_DEN,Hybrid_HWM,Hybrid_HWM_DEN,H_COMP_1_A_P,H_COMP_1_SN_P,H_COMP_1_U_P,H_COMP_1_LINEAR_SCORE,H_COMP_1_STAR_RATING,H_NURSE_RESPECT_A_P,H_NURSE_RESPECT_SN_P,H_NURSE_RESPECT_U_P,H_NURSE_LISTEN_A_P,H_NURSE_LISTEN_SN_P,H_NURSE_LISTEN_U_P,H_NURSE_EXPLAIN_A_P,H_NURSE_EXPLAIN_SN_P,H_NURSE_EXPLAIN_U_P,H_COMP_2_A_P,H_COMP_2_SN_P,H_COMP_2_U_P,H_COMP_2_LINEAR_SCORE,H_COMP_2_STAR_RATING,H_DOCTOR_RESPECT_A_P,H_DOCTOR_RESPECT_SN_P,H_DOCTOR_RESPECT_U_P,H_DOCTOR_LISTEN_A_P,H_DOCTOR_LISTEN_SN_P,H_DOCTOR_LISTEN_U_P,H_DOCTOR_EXPLAIN_A_P,H_DOCTOR_EXPLAIN_SN_P,H_DOCTOR_EXPLAIN_U_P,H_COMP_5_A_P,H_COMP_5_SN_P,H_COMP_5_U_P,H_COMP_5_LINEAR_SCORE,H_COMP_5_STAR_RATING,H_MED_FOR_A_P,H_MED_FOR_SN_P,H_MED_FOR_U_P,H_SIDE_EFFECTS_A_P,H_SIDE_EFFECTS_SN_P,H_SIDE_EFFECTS_U_P,H_COMP_6_N_P,H_COMP_6_Y_P,H_COMP_6_LINEAR_SCORE,H_COMP_6_STAR_RATING,H_DISCH_HELP_N_P,H_DISCH_HELP_Y_P,H_SYMPTOMS_N_P,H_SYMPTOMS_Y_P,H_CLEAN_HSP_A_P,H_CLEAN_HSP_SN_P,H_CLEAN_HSP_U_P,H_CLEAN_LINEAR_SCORE,H_CLEAN_STAR_RATING,H_QUIET_HSP_A_P,H_QUIET_HSP_SN_P,H_QUIET_HSP_U_P,H_QUIET_LINEAR_SCORE,H_QUIET_STAR_RATING,H_HSP_RATING_0_6,H_HSP_RATING_7_8,H_HSP_RATING_9_10,H_HSP_RATING_LINEAR_SCORE,H_HSP_RATING_STAR_RATING,H_RECMND_DN,H_RECMND_DY,H_RECMND_PY,H_RECMND_LINEAR_SCORE,H_RECMND_STAR_RATING,H_STAR_RATING,O-COMP-1,O-COMP-2,O-COMP-3,O-PATIENT-RATE,O-PATIENT-REC,EDAC_30_AMI,EDAC_30_AMI_DEN,EDAC_30_HF,EDAC_30_HF_DEN,EDAC_30_PN,EDAC_30_PN_DEN,OP_32,OP_32_DEN,OP_35_ADM,OP_35_ADM_DEN,OP_35_ED,OP_35_ED_DEN,OP_36,OP_36_DEN,READM_30_CABG,READM_30_CABG_DEN,READM_30_COPD,READM_30_COPD_DEN,READM_30_HIP_KNEE,READM_30_HIP_KNEE_DEN,Hybrid_HWR,Hybrid_HWR_DEN,HAI_1_DEN_PRED,HAI_1_DEN_VOL,HAI_1,HAI_2_DEN_PRED,HAI_2_DEN_VOL,HAI_2,HAI_3_DEN_PRED,HAI_3_DEN_VOL,HAI_3,HAI_4_DEN_PRED,HAI_4_DEN_VOL,HAI_4,HAI_5_DEN_PRED,HAI_5_DEN_VOL,HAI_5,HAI_6_DEN_PRED,HAI_6_DEN_VOL,HAI_6,OP_13,OP_8,OP_10,Release year
0,010001,0.93,4625.0,217.0,395.0,0.03,62163.0,NaN,NaN,0.62,39.0,0.65,141.0,0.14,4583.0,0.114,270.0,0.030,144.0,0.094,112.0,0.102,583.0,0.184,517.0,0.135,395.0,203.00,118.0,0.032,27.0,0.95,NaN,0.045,1835.0,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.0,NaN,NaN,NaN,NaN,87.0,NaN,NaN,NaN,NaN,89.0,NaN,NaN,NaN,NaN,91.0,NaN,NaN,98.0,92.0,97.0,94.0,94.0,-15.6,273.0,-1.1,652.0,17.4,507.0,12.7,234.0,10.0,302.0,5.1,302.0,1.1,651.0,0.101,137.0,0.180,122.0,0.048,25.0,0.151,2824.0,10.399,9871.0,0.288,25.693,18164.0,0.195,6.830,238.0,0.293,0.871,91.0,NaN,9.613,114863.0,0.416,71.953,113805.0,0.459,0.038,0.308,0.053,2027
1,010005,0.59,2856.0,141.0,1165.0,0.03,60663.0,NaN,NaN,0.98,301.0,0.73,293.0,0.15,1859.0,NaN,NaN,NaN,NaN,0.089,126.0,0.141,158.0,0.212,285.0,0.129,89.0,184.79,27.0,0.030,104.0,0.97,NaN,0.046,698.0,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.0,NaN,NaN,NaN,NaN,86.0,NaN,NaN,NaN,NaN,86.0,NaN,NaN,NaN,NaN,84.0,NaN,NaN,98.0,96.0,98.0,94.0,93.0,NaN,NaN,12.2,164.0,-17.2,292.0,13.0,917.0,9.3,84.0,4.8,84.0,0.9,389.0,NaN,NaN,0.171,132.0,0.042,81.0,0.133,986.0,2.952,4837.0,1.694,2.904,6302.0,1.722,2.175,85.0,0.920,0.517,49.0,NaN,1.295,37659.0,1.544,9.407,35960.0,0.425,0.033,0.422,0.128,2027
2,010006,0.64,2565.0,144.0,320.0,0.01,46884.0,0.82,17.0,0.84,67.0,0.61,137.0,0.15,4350.0,0.145,266.0,0.054,79.0,0.087,160.0,0.125,413.0,0.196,659.0,0.124,258.0,236.12,91.0,0.047,49.0,1.14,NaN,0.052,1583.0,NaN,NaN,NaN,89.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81.0,NaN,NaN,NaN,NaN,84.0,NaN,NaN,NaN,NaN,83.0,NaN,NaN,NaN,NaN,80.0,NaN,NaN,97.0,93.0,97.0,92.0,90.0,-18.0,285.0,-4.7,461.0,-0.9,679.0,11.1,1619.0,NaN,NaN,NaN,NaN,1.2,458.0,0.106,71.0,0.191,174.0,0.051,56.0,0.159,2494.0,4.451,4028.0,0.000,9.659,7485.0,0.207,2.466,90.0,0.000,2.182,228.0,0.0,5.177,68737.0,0.386,39.023,65840.0,0.077,0.041,NaN,0.088,2027
3,010007,0.29,358.0,128.0,1048.0,0.01,11011.0,NaN,NaN,0.87,136.0,0.20,15.0,0.15,212.0,NaN,NaN,NaN,NaN,0.112,34.0,0.134,34.0,0.254,98.0,NaN,NaN,NaN,NaN,NaN,NaN,1.06,NaN,0.048,125.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.0,95.0,97.0,91.0,91.0,NaN,NaN,77.9,39.0,29.8,84.0,12.5,108.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.186,32.0,NaN,NaN,0.154,189.0,0.181,293.0,NaN,0.701,1282.0,NaN,0.026,1.0,NaN,NaN,NaN,NaN,0.081,3745.0,NaN,1.065,3745.0,0.939,NaN,NaN,0.059,2027
4,010011,0.79,2317.0,156.0,254.0,NaN,NaN,0.64,11.0,NaN,NaN,0.72,129.0,0.13,727.0,0.127,109.0,0.022,64.0,0.091,53.0,0.144,235.0,0.201,268.0,0.128,66.0,176.90,43.0,0.040,25.0,1.03,NaN,0.041,582.0,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82.0,NaN,NaN,NaN,NaN,83.0,NaN,NaN,NaN,NaN,87.0,NaN,NaN,NaN,NaN,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-23.6,118.0,21.2,266.0,18.1,281.0,12.9,79.0,NaN,NaN,NaN,NaN,1.1,52.0,0.119,63.0,0.182,57.0,NaN,NaN,0.146,902.0,7.581,7040.0,1.187,9.837,7651.0,0.305,2.897,105.0,0.000,0.009,1.0,NaN,5.758,58552.0,0.521,28.306,58552.0,0.318,NaN,NaN,0.092,2027

In [21]:
with io.capture_output() as captured: 
    df_2026 = pd.read_csv(stars_dir + '2026/2026-05_Stars_Release/stars_alldata_2026apr.csv')
df_2026['Release year'] = ['2026']*df_2026.shape[0]
df_2026 = df_2026.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
df_2026 = df_2026[df_2026['PROVIDER_ID'].isin(prvdrs_2026)]

df_2026.rename(columns={'Hybrid_HWM_RSMR': 'Hybrid_HWM'}, inplace=True)

print(df_2026.shape)
prvdrs = df_2026['PROVIDER_ID'].unique()
print(len(prvdrs), 'hospitals in 2026')

df_2026.head()

(3203, 100)
3203 hospitals in 2026

,PROVIDER_ID,COMP_HIP_KNEE_DEN,EDAC_30_AMI,EDAC_30_AMI_DEN,EDAC_30_HF,EDAC_30_HF_DEN,EDAC_30_PN,EDAC_30_PN_DEN,HAI_1_DEN_VOL,HAI_1_DEN_PRED,HAI_1,HAI_2_DEN_VOL,HAI_2_DEN_PRED,HAI_2,HAI_3_DEN_VOL,HAI_3_DEN_PRED,HAI_3,HAI_4_DEN_VOL,HAI_4_DEN_PRED,HAI_4,HAI_5_DEN_VOL,HAI_5_DEN_PRED,HAI_5,HAI_6_DEN_VOL,HAI_6_DEN_PRED,HAI_6,H_CLEAN_LINEAR_SCORE,H_COMP_1_LINEAR_SCORE,H_COMP_2_LINEAR_SCORE,H_COMP_3_LINEAR_SCORE,H_COMP_5_LINEAR_SCORE,H_COMP_6_LINEAR_SCORE,H_COMP_7_LINEAR_SCORE,H_HSP_RATING_LINEAR_SCORE,H_NUMB_COMP,H_QUIET_LINEAR_SCORE,H_RECMND_LINEAR_SCORE,H_RESP_RATE_P,Hybrid_HWM_DEN,Hybrid_HWM,Hybrid_HWR_DEN,Hybrid_HWR,IMM_3,IMM_3_DEN,MORT_30_AMI_DEN,MORT_30_CABG_DEN,MORT_30_COPD_DEN,MORT_30_HF_DEN,MORT_30_PN_DEN,MORT_30_STK_DEN,OP_10_DEN,OP_10,OP_13_DEN,OP_13,OP_18B_DEN,OP_18B,OP_22_DEN,OP_22,OP_23_DEN,OP_23,OP_29_DEN,OP_29,OP_32_DEN,OP_35_ADM_DEN,OP_35_ED_DEN,OP_36_DEN,OP-37_NUMB_COMP,O-COMP-1,O-COMP-2,O-COMP-3,O-PATIENT-RATE,O-PATIENT-REC,OP_8_DEN,OP_8,PSI_4_SURG_COMP_DEN,PSI_4_SURG_COMP,PSI_90_SAFETY_DEN,PSI_90_SAFETY,READM_30_CABG_DEN,READM_30_COPD_DEN,READM_30_HIP_KNEE_DEN,COMP_HIP_KNEE,OP_32,OP_35_ADM,OP_35_ED,OP_36,MORT_30_AMI,MORT_30_CABG,MORT_30_COPD,MORT_30_HF,MORT_30_PN,MORT_30_STK,READM_30_CABG,READM_30_COPD,READM_30_HIP_KNEE,SAFE_USE_OF_OPIOIDS_DEN,SAFE_USE_OF_OPIOIDS,SEP_1_DEN,SEP_1,Release year
0,010001,27.0,-15.6,273.0,-1.1,652.0,17.4,507.0,8935.0,9.440,0.530,16255.0,23.350,0.086,229.0,6.562,0.457,NaN,NaN,NaN,109019.0,10.937,0.183,109019.0,68.076,0.382,85.0,90.0,92.0,82.0,79.0,87.0,82.0,89.0,627.0,88.0,91.0,17.0,1835.0,0.045,2824.0,0.151,0.93,4625.0,270.0,144.0,112.0,583.0,517.0,395.0,1517.0,0.053,365.0,0.038,387.0,222.0,57084.0,0.05,11.0,0.91,29.0,0.72,218.0,261.0,261.0,647.0,185.0,98.0,93.0,97.0,94.0,94.0,52.0,0.308,118.0,203.00,NaN,0.95,137.0,122.0,25.0,0.032,12.8,8.5,5.7,0.8,0.114,0.030,0.094,0.102,0.184,0.135,0.101,0.180,0.048,4583.0,0.14,150.0,0.69,2026
1,010005,104.0,NaN,NaN,12.2,164.0,-17.2,292.0,4514.0,2.746,0.728,6567.0,2.991,1.003,90.0,2.291,0.436,NaN,NaN,NaN,37163.0,1.258,1.590,35488.0,9.436,0.530,85.0,91.0,93.0,77.0,72.0,88.0,80.0,87.0,586.0,87.0,85.0,14.0,698.0,0.046,986.0,0.133,0.59,2856.0,NaN,NaN,126.0,158.0,285.0,89.0,828.0,0.128,153.0,0.033,1120.0,137.0,58624.0,0.03,11.0,0.27,210.0,1.00,897.0,99.0,99.0,396.0,752.0,98.0,96.0,98.0,94.0,93.0,83.0,0.422,27.0,184.79,NaN,0.97,NaN,132.0,81.0,0.030,14.2,8.6,6.2,1.0,NaN,NaN,0.089,0.141,0.212,0.129,NaN,0.171,0.042,1859.0,0.15,289.0,0.75,2026
2,010006,49.0,-18.0,285.0,-4.7,461.0,-0.9,679.0,3915.0,4.335,0.000,7561.0,9.758,0.000,92.0,2.448,0.000,225.0,2.183,0.0,69033.0,4.733,0.000,66038.0,38.671,0.078,79.0,89.0,88.0,76.0,70.0,82.0,77.0,83.0,1724.0,84.0,80.0,17.0,1583.0,0.052,2494.0,0.159,0.64,2565.0,266.0,79.0,160.0,413.0,659.0,258.0,898.0,0.088,221.0,0.041,336.0,150.0,44924.0,0.01,15.0,0.67,85.0,0.86,1618.0,NaN,NaN,502.0,326.0,98.0,94.0,97.0,93.0,91.0,NaN,NaN,91.0,236.12,NaN,1.14,71.0,174.0,56.0,0.047,11.6,NaN,NaN,1.0,0.145,0.054,0.087,0.125,0.196,0.124,0.106,0.191,0.051,4350.0,0.15,137.0,0.66,2026
3,010007,NaN,NaN,NaN,77.9,39.0,29.8,84.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4132.0,1.481,0.675,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125.0,0.048,189.0,0.154,0.29,358.0,NaN,NaN,34.0,34.0,98.0,NaN,135.0,0.059,NaN,NaN,1107.0,117.0,12667.0,0.02,NaN,NaN,52.0,0.65,117.0,NaN,NaN,NaN,180.0,97.0,92.0,96.0,91.0,92.0,NaN,NaN,NaN,NaN,NaN,1.06,NaN,32.0,NaN,NaN,12.5,NaN,NaN,NaN,NaN,NaN,0.112,0.134,0.254,NaN,NaN,0.186,NaN,212.0,0.15,15.0,0.13,2026
5,010011,25.0,-23.6,118.0,21.2,266.0,18.1,281.0,2304.0,2.472,2.427,2269.0,2.917,0.343,41.0,1.112,0.000,NaN,NaN,NaN,18473.0,1.396,1.433,18473.0,9.183,0.327,83.0,89.0,90.0,84.0,73.0,84.0,79.0,87.0,314.0,85.0,86.0,18.0,582.0,0.041,902.0,0.146,0.79,2317.0,109.0,64.0,53.0,235.0,268.0,66.0,217.0,0.092,NaN,NaN,85.0,154.0,42419.0,0.02,NaN,NaN,42.0,0.83,125.0,NaN,NaN,270.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.0,176.90,NaN,1.03,63.0,57.0,NaN,0.040,12.8,NaN,NaN,0.7,0.127,0.022,0.091,0.144,0.201,0.128,0.119,0.182,NaN,727.0,0.13,51.0,0.75,2026

In [22]:
with io.capture_output() as captured: 
    df_2025 = pd.read_sas(stars_dir + '2025/2025-07 Stars Release/alldata_2025jul.sas7bdat')
df_2025['Release year'] = ['2025']*df_2025.shape[0]
df_2025 = df_2025.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
df_2025 = df_2025[df_2025['PROVIDER_ID'].isin(prvdrs_2025)]

print(df_2025.shape)
prvdrs = df_2025['PROVIDER_ID'].unique()
print(len(prvdrs), 'hospitals in 2025')

df_2025.head()

(2891, 94)
2891 hospitals in 2025

,PROVIDER_ID,COMP_HIP_KNEE,IMM_3_DEN,EDAC_30_AMI,EDAC_30_AMI_DEN,READM_30_HOSP_WIDE_DEN,HAI_3,EDAC_30_HF_DEN,OP_18B_DEN,HAI_6,OP_29,OP_23_DEN,SAFE_USE_OF_OPIOIDS,MORT_30_COPD_DEN,HAI_3_DEN_VOL,HAI_5_DEN_PRED,OP_35_ED,OP_13_DEN,READM_30_CABG,HAI_5_DEN_VOL,OP_22,HAI_1_DEN_VOL,OP_36,MORT_30_STK,READM_30_COPD,READM_30_HIP_KNEE_DEN,H_NUMB_COMP,HAI_6_DEN_VOL,MORT_30_PN,OP_35_ADM,PC_01,MORT_30_HF_DEN,OP_32,PC_01_DEN,SAFE_USE_OF_OPIOIDS_DEN,H_COMP_7_STAR_RATING,READM_30_HIP_KNEE,HCP_COVID_19,READM_30_COPD_DEN,H_COMP_5_STAR_RATING,OP_10_DEN,COMP_HIP_KNEE_DEN,HAI_2_DEN_PRED,MORT_30_CABG,OP_29_DEN,OP_22_DEN,SEP_1,OP_23,MORT_30_AMI_DEN,H_COMP_6_STAR_RATING,OP_18B,MORT_30_AMI,MORT_30_PN_DEN,READM_30_HOSP_WIDE,EDAC_30_PN,OP_36_DEN,MORT_30_CABG_DEN,HAI_1_DEN_PRED,HAI_6_DEN_PRED,MORT_30_COPD,OP_13,PSI_90_SAFETY,MORT_30_HF,H_RESP_RATE_P,HCP_COVID_19_DEN,H_COMP_1_STAR_RATING,READM_30_CABG_DEN,PSI_90_SAFETY_DEN,IMM_3,HAI_3_DEN_PRED,H_COMP_3_STAR_RATING,OP_8_DEN,MORT_30_STK_DEN,OP_8,PSI_4_SURG_COMP_DEN,OP_10,EDAC_30_HF,HAI_2_DEN_VOL,OP_32_DEN,OP_35_ED_DEN,HAI_2,H_COMP_2_STAR_RATING,HAI_1,PSI_4_SURG_COMP,OP_35_ADM_DEN,SEP_1_DEN,EDAC_30_PN_DEN,HAI_5,HAI_4,HAI_4_DEN_VOL,HAI_4_DEN_PRED,H_INDI_STAR_RATING,H_GLOB_STAR_RATING,Release year
0,010001,0.030,4115.0,-13.8,296.0,2924.0,1.209,679.0,345.0,0.491,0.47,NaN,0.12,122.0,240.0,11.232,4.9,193.0,0.102,103195.0,0.05,9538.0,1.1,0.137,0.177,34.0,643.0,103195.0,0.189,11.9,0.02,610.0,12.9,46.0,4303.0,4.0,0.044,0.000,130.0,3.0,1478.0,32.0,23.712,0.038,17.0,52960.0,0.68,NaN,291.0,3.0,217.0,0.108,489.0,0.141,14.3,668.0,157.0,10.082,65.234,0.079,0.021,0.98,0.105,17.0,2712.0,2.0,151.0,NaN,0.96,6.618,3.0,66.0,414.0,0.333,125.0,0.054,10.6,16332.0,170.0,202.0,0.169,4.0,0.496,194.78,202.0,131.0,490.0,0.445,NaN,NaN,NaN,3.0,4.0,2025
1,010005,0.027,2407.0,NaN,NaN,1056.0,0.000,176.0,1154.0,0.631,0.96,13.0,0.16,133.0,102.0,1.631,5.5,177.0,NaN,35424.0,0.03,3410.0,1.9,0.139,0.161,144.0,714.0,33872.0,0.231,7.9,0.01,162.0,14.2,193.0,2244.0,3.0,0.039,0.026,143.0,4.0,850.0,138.0,3.262,NaN,180.0,56820.0,0.76,0.69,28.0,4.0,144.0,0.145,301.0,0.135,-8.4,406.0,NaN,2.074,9.503,0.092,0.028,1.01,0.127,17.0,2431.0,3.0,NaN,NaN,0.72,2.867,2.0,109.0,97.0,0.459,43.0,0.134,9.8,7200.0,739.0,107.0,1.226,4.0,0.964,191.14,107.0,288.0,305.0,2.452,NaN,NaN,NaN,3.5,3.0,2025
2,010006,0.040,2560.0,13.4,315.0,2560.0,0.000,508.0,349.0,0.026,0.85,NaN,0.16,141.0,73.0,5.397,NaN,243.0,0.115,68020.0,0.01,4826.0,1.4,0.142,0.177,90.0,1620.0,64728.0,0.198,NaN,0.00,455.0,12.1,22.0,3521.0,2.0,0.044,0.000,154.0,2.0,973.0,84.0,11.164,0.052,82.0,42286.0,0.56,NaN,292.0,2.0,177.0,0.166,616.0,0.147,4.5,484.0,102.0,5.279,37.771,0.102,0.029,1.16,0.122,18.0,2095.0,2.0,91.0,NaN,0.66,1.935,2.0,NaN,271.0,NaN,102.0,0.108,-4.9,8700.0,1355.0,NaN,0.000,2.0,0.000,201.13,NaN,162.0,621.0,0.371,0.0,116.0,1.086,2.5,2.0,2025
3,010007,0.034,345.0,NaN,NaN,234.0,NaN,35.0,594.0,1.003,0.23,NaN,NaN,42.0,NaN,NaN,NaN,NaN,NaN,NaN,0.04,NaN,1.2,NaN,0.190,33.0,175.0,5267.0,0.290,NaN,NaN,33.0,13.4,NaN,NaN,4.0,0.044,0.000,41.0,5.0,151.0,33.0,NaN,NaN,111.0,11202.0,0.24,NaN,NaN,5.0,129.0,NaN,101.0,0.151,21.5,59.0,NaN,NaN,1.994,0.135,NaN,0.93,0.141,24.0,245.0,5.0,NaN,NaN,0.26,NaN,4.0,NaN,NaN,NaN,NaN,0.073,20.9,NaN,109.0,NaN,NaN,5.0,NaN,NaN,NaN,21.0,85.0,NaN,NaN,NaN,NaN,3.0,4.0,2025
5,010011,0.038,NaN,-12.4,148.0,1636.0,0.000,294.0,333.0,0.498,1.00,23.0,0.17,55.0,117.0,8.719,NaN,NaN,0.119,80106.0,0.05,9905.0,0.9,0.129,0.187,32.0,1334.0,80106.0,0.225,NaN,NaN,258.0,12.8,NaN,3360.0,3.0,0.043,0.008,58.0,3.0,383.0,28.0,13.381,0.021,24.0,41057.0,0.60,0.43,136.0,4.0,190.0,0.128,336.0,0.159,6.3,249.0,70.0,10.751,42.140,0.106,NaN,0.95,0.140,26.0,1402.0,3.0,70.0,NaN,NaN,3.261,3.0,NaN,86.0,NaN,67.0,0.078,30.0,10399.0,68.0,NaN,0.299,4.0,0.744,208.80,NaN,205.0,344.0,0.573,NaN,NaN,NaN,2.5,3.0,2025

In [23]:
with io.capture_output() as captured: 
    df_2024 = pd.read_sas(stars_dir + '2024/2024-07 Stars Release/alldata_2024jul.sas7bdat')
df_2024['Release year'] = ['2024']*df_2024.shape[0]
df_2024 = df_2024.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
df_2024 = df_2024[df_2024['PROVIDER_ID'].isin(prvdrs_2024)]

print(df_2024.shape)
prvdrs = df_2024['PROVIDER_ID'].unique()
print(len(prvdrs), 'hospitals in 2024')

df_2024.head()

(2847, 96)
2847 hospitals in 2024

,PROVIDER_ID,HAI_1_DEN_VOL,HAI_2_DEN_VOL,HAI_3_DEN_VOL,HAI_4_DEN_VOL,HAI_5_DEN_VOL,HAI_6_DEN_VOL,HAI_1_DEN_PRED,HAI_2_DEN_PRED,HAI_3_DEN_PRED,HAI_4_DEN_PRED,HAI_5_DEN_PRED,HAI_6_DEN_PRED,HAI_1,HAI_2,HAI_3,HAI_4,HAI_5,HAI_6,READM_30_HOSP_WIDE,READM_30_HIP_KNEE,EDAC_30_HF,READM_30_COPD,EDAC_30_AMI,EDAC_30_PN,MORT_30_STK,MORT_30_PN,MORT_30_HF,MORT_30_COPD,MORT_30_AMI,COMP_HIP_KNEE,READM_30_HOSP_WIDE_DEN,READM_30_HIP_KNEE_DEN,EDAC_30_HF_DEN,READM_30_COPD_DEN,EDAC_30_AMI_DEN,EDAC_30_PN_DEN,MORT_30_STK_DEN,MORT_30_PN_DEN,MORT_30_HF_DEN,MORT_30_COPD_DEN,MORT_30_AMI_DEN,COMP_HIP_KNEE_DEN,OP_2,OP_2_DEN,OP_3B,OP_3B_DEN,OP_8,OP_8_DEN,OP_10,OP_10_DEN,OP_13,OP_13_DEN,OP_18B,OP_18B_DEN,OP_22,OP_22_DEN,OP_23,OP_23_DEN,OP_29,OP_29_DEN,PSI_4_SURG_COMP,PSI_4_SURG_COMP_DEN,PSI_90_SAFETY,IMM_3_DEN,IMM_3,HCP_COVID_19_DEN,HCP_COVID_19,PC_01,PC_01_DEN,SEP_1,SEP_1_DEN,H_RESP_RATE_P,H_COMP_1_STAR_RATING,H_COMP_2_STAR_RATING,H_COMP_3_STAR_RATING,H_COMP_5_STAR_RATING,H_COMP_6_STAR_RATING,H_COMP_7_STAR_RATING,H_GLOB_STAR_RATING,H_INDI_STAR_RATING,H_NUMB_COMP,PSI_90_SAFETY_DEN,MORT_30_CABG,MORT_30_CABG_DEN,READM_30_CABG,READM_30_CABG_DEN,OP_32,OP_32_DEN,OP_35_ADM,OP_35_ADM_DEN,OP_35_ED,OP_35_ED_DEN,OP_36,OP_36_DEN,Release year
0,010001,9149.0,17310.0,214.0,NaN,104733.0,104733.0,9.597,24.766,5.994,NaN,11.400,67.066,0.938,0.363,1.335,NaN,0.965,0.507,0.142,0.038,23.4,0.190,-15.4,23.6,0.148,0.180,0.089,0.088,0.120,0.027,2912.0,49.0,614.0,117.0,274.0,403.0,398.0,400.0,549.0,107.0,278.0,49.0,NaN,NaN,NaN,NaN,0.380,79.0,0.061,1410.0,0.028,178.0,214.0,348.0,0.05,52960.0,NaN,NaN,0.47,17.0,184.68,134.0,1.21,3905.0,0.95,2496.0,0.836,0.00,32.0,0.65,127.0,15.0,3.0,3.0,3.0,3.0,4.0,4.0,3.5,3.5,544.0,2542.038500,0.041,132.0,0.105,126.0,12.9,170.0,11.9,202.0,4.9,202.0,1.1,668.0,2024
1,010005,3194.0,8277.0,96.0,NaN,36794.0,34887.0,1.989,4.019,2.626,NaN,1.847,10.066,2.514,0.995,0.762,NaN,0.541,0.497,0.128,0.034,22.1,0.166,NaN,-6.2,0.153,0.233,0.149,0.099,0.136,0.023,1052.0,172.0,129.0,136.0,NaN,285.0,81.0,289.0,121.0,126.0,27.0,155.0,NaN,NaN,57.0,16.0,0.477,130.0,0.120,1057.0,0.042,189.0,145.0,1074.0,0.03,56820.0,0.58,12.0,0.96,180.0,183.49,43.0,0.97,2700.0,0.80,2552.0,0.807,0.02,200.0,0.69,252.0,18.0,3.0,4.0,1.0,3.0,4.0,3.0,3.0,3.0,824.0,978.028994,NaN,NaN,NaN,NaN,14.2,739.0,7.9,107.0,5.5,107.0,1.9,406.0,2024
2,010006,5343.0,8715.0,111.0,NaN,63727.0,60304.0,5.801,11.166,2.950,NaN,5.283,27.805,0.172,0.358,0.000,NaN,1.514,0.072,0.134,0.053,-4.7,0.176,28.1,-0.4,0.172,0.195,0.125,0.099,0.165,0.046,2310.0,138.0,441.0,158.0,273.0,472.0,227.0,469.0,388.0,148.0,254.0,145.0,NaN,NaN,NaN,NaN,0.462,39.0,0.101,978.0,0.045,221.0,168.0,360.0,0.01,42286.0,0.75,16.0,0.85,82.0,173.63,96.0,1.17,2536.0,0.67,1882.0,0.796,0.04,28.0,0.57,126.0,19.0,2.0,3.0,2.0,2.0,3.0,2.0,2.0,2.5,1503.0,1753.979899,0.036,95.0,0.124,89.0,12.1,1355.0,NaN,NaN,NaN,NaN,1.4,484.0,2024
3,010007,NaN,NaN,NaN,NaN,NaN,5511.0,NaN,NaN,NaN,NaN,NaN,2.660,NaN,NaN,NaN,NaN,NaN,0.376,0.157,0.042,-1.9,0.200,NaN,-9.4,NaN,0.285,0.125,0.137,NaN,NaN,258.0,26.0,31.0,34.0,NaN,72.0,NaN,88.0,26.0,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.034,146.0,NaN,NaN,132.0,1275.0,0.04,11202.0,NaN,NaN,0.23,111.0,NaN,NaN,0.95,350.0,0.53,252.0,0.601,NaN,NaN,0.93,43.0,24.0,3.0,5.0,4.0,3.0,3.0,3.0,3.5,3.0,189.0,228.286193,NaN,NaN,NaN,NaN,13.4,109.0,NaN,NaN,NaN,NaN,1.2,59.0,2024
5,010011,12136.0,11795.0,142.0,NaN,83101.0,83101.0,13.096,15.144,3.798,NaN,6.946,59.529,0.916,0.528,0.263,NaN,0.720,0.638,0.149,0.042,26.0,0.197,-9.0,14.5,0.123,0.209,0.135,0.103,0.132,0.035,1366.0,27.0,251.0,47.0,127.0,309.0,86.0,304.0,225.0,43.0,121.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,0.057,332.0,NaN,NaN,213.0,341.0,0.05,41057.0,0.25,16.0,1.00,24.0,189.28,83.0,0.72,2377.0,0.81,1487.0,0.889,NaN,NaN,0.44,201.0,33.0,3.0,3.0,4.0,3.0,4.0,3.0,3.5,2.5,2023.0,1293.230115,0.026,65.0,0.126,64.0,12.8,68.0,NaN,NaN,NaN,NaN,0.9,249.0,2024

In [24]:
with io.capture_output() as captured: 
    df_2023 = pd.read_sas(stars_dir + '2023/2023-07 Stars Release/alldata_2023jul.sas7bdat')
df_2023['Release year'] = ['2023']*df_2023.shape[0]
df_2023 = df_2023.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
df_2023 = df_2023[df_2023['PROVIDER_ID'].isin(prvdrs_2023)]

print(df_2023.shape)
prvdrs = df_2023['PROVIDER_ID'].unique()
print(len(prvdrs), 'hospitals in 2023')

df_2023.head()

(3076, 96)
3076 hospitals in 2023

,PROVIDER_ID,HAI_1_DEN_VOL,HAI_2_DEN_VOL,HAI_3_DEN_VOL,HAI_4_DEN_VOL,HAI_5_DEN_VOL,HAI_6_DEN_VOL,HAI_1_DEN_PRED,HAI_2_DEN_PRED,HAI_3_DEN_PRED,HAI_4_DEN_PRED,HAI_5_DEN_PRED,HAI_6_DEN_PRED,HAI_1,HAI_2,HAI_3,HAI_4,HAI_5,HAI_6,READM_30_HOSP_WIDE,READM_30_HIP_KNEE,EDAC_30_HF,READM_30_COPD,EDAC_30_AMI,EDAC_30_PN,MORT_30_STK,MORT_30_PN,MORT_30_HF,MORT_30_COPD,MORT_30_AMI,COMP_HIP_KNEE,READM_30_HOSP_WIDE_DEN,READM_30_HIP_KNEE_DEN,EDAC_30_HF_DEN,READM_30_COPD_DEN,EDAC_30_AMI_DEN,EDAC_30_PN_DEN,MORT_30_STK_DEN,MORT_30_PN_DEN,MORT_30_HF_DEN,MORT_30_COPD_DEN,MORT_30_AMI_DEN,COMP_HIP_KNEE_DEN,OP_2,OP_2_DEN,OP_3B,OP_3B_DEN,OP_8,OP_8_DEN,OP_10,OP_10_DEN,OP_13,OP_13_DEN,OP_18B,OP_18B_DEN,OP_22,OP_22_DEN,OP_23,OP_23_DEN,OP_29,OP_29_DEN,PSI_4_SURG_COMP,PSI_4_SURG_COMP_DEN,PSI_90_SAFETY,IMM_3_DEN,IMM_3,HCP_COVID_19_DEN,HCP_COVID_19,PC_01,PC_01_DEN,SEP_1,SEP_1_DEN,H_RESP_RATE_P,H_COMP_1_STAR_RATING,H_COMP_2_STAR_RATING,H_COMP_3_STAR_RATING,H_COMP_5_STAR_RATING,H_COMP_6_STAR_RATING,H_COMP_7_STAR_RATING,H_GLOB_STAR_RATING,H_INDI_STAR_RATING,H_NUMB_COMP,PSI_90_SAFETY_DEN,MORT_30_CABG,MORT_30_CABG_DEN,READM_30_CABG,READM_30_CABG_DEN,OP_32,OP_32_DEN,OP_35_ADM,OP_35_ADM_DEN,OP_35_ED,OP_35_ED_DEN,OP_36,OP_36_DEN,Release year
0,010001,10024.0,17731.0,154.0,200.0,101908.0,101451.0,10.597,26.630,4.548,1.845,9.412,72.686,0.661,0.300,1.099,0.0,0.850,0.660,0.142,0.042,21.8,0.199,1.9,-1.5,0.164,0.159,0.083,0.085,0.124,0.024,3058.0,98.0,755.0,202.0,319.0,436.0,489.0,407.0,630.0,182.0,317.0,102.0,NaN,NaN,NaN,NaN,0.425,146.0,0.057,1488.0,0.067,208.0,205.0,323.0,0.03,51079.0,NaN,NaN,0.81,16.0,173.39,120.0,1.01,3795.0,0.97,2323.0,0.737,0.09,34.0,0.46,146.0,15.0,2.0,3.0,2.0,4.0,4.0,3.0,3.0,3.5,434.0,2046.895485,0.047,172.0,0.117,165.0,14.1,254.0,10.2,214.0,4.7,214.0,1.0,688.0,2023
1,010005,3713.0,8670.0,88.0,NaN,38413.0,35686.0,2.450,4.995,2.512,NaN,1.999,10.484,3.673,1.201,1.194,NaN,0.000,0.858,0.139,0.040,9.3,0.176,4.7,2.2,0.166,0.218,0.169,0.081,0.126,0.018,1258.0,178.0,157.0,234.0,38.0,361.0,100.0,369.0,153.0,195.0,52.0,134.0,NaN,NaN,NaN,NaN,0.545,191.0,0.138,1214.0,0.043,208.0,146.0,1003.0,0.03,54503.0,0.73,15.0,0.99,108.0,142.88,35.0,0.91,2593.0,0.90,2026.0,0.821,0.01,194.0,0.59,242.0,16.0,3.0,4.0,2.0,3.0,3.0,3.0,3.0,3.5,717.0,819.043002,NaN,NaN,NaN,NaN,14.6,850.0,11.1,108.0,5.7,108.0,0.9,362.0,2023
2,010006,7318.0,11755.0,91.0,NaN,62709.0,54159.0,7.924,15.296,2.523,NaN,4.164,22.618,0.757,0.196,0.396,NaN,1.441,0.088,0.142,0.048,-2.3,0.177,25.9,42.3,0.189,0.178,0.122,0.078,0.165,0.034,2555.0,246.0,550.0,235.0,312.0,538.0,261.0,528.0,468.0,209.0,295.0,234.0,NaN,NaN,NaN,NaN,0.412,97.0,0.110,1168.0,0.014,217.0,144.0,363.0,0.01,41137.0,0.57,14.0,0.88,75.0,157.42,84.0,1.10,2292.0,0.64,2694.0,0.651,0.00,37.0,0.58,142.0,17.0,2.0,3.0,1.0,2.0,3.0,2.0,2.0,2.5,1358.0,1487.163359,0.035,117.0,0.156,109.0,12.5,1505.0,NaN,NaN,NaN,NaN,1.1,468.0,2023
3,010007,NaN,NaN,NaN,NaN,NaN,5413.0,NaN,NaN,NaN,NaN,NaN,2.148,NaN,NaN,NaN,NaN,NaN,0.466,0.151,NaN,36.3,0.197,NaN,-12.6,NaN,0.217,0.139,0.103,NaN,NaN,272.0,NaN,51.0,72.0,NaN,99.0,NaN,106.0,45.0,63.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.059,169.0,NaN,NaN,119.0,1202.0,0.03,11120.0,NaN,NaN,0.63,68.0,NaN,NaN,0.99,318.0,0.61,277.0,0.574,NaN,NaN,0.93,55.0,23.0,3.0,5.0,4.0,4.0,4.0,4.0,4.0,4.0,173.0,142.073902,NaN,NaN,NaN,NaN,15.3,118.0,NaN,NaN,NaN,NaN,1.0,56.0,2023
5,010011,11886.0,11988.0,154.0,NaN,81837.0,81837.0,12.884,15.434,4.069,NaN,8.226,56.451,0.621,0.907,0.000,NaN,1.459,0.620,0.146,0.042,17.9,0.206,13.0,7.7,0.152,0.171,0.122,0.082,0.138,0.024,1524.0,36.0,298.0,101.0,139.0,346.0,101.0,330.0,265.0,90.0,127.0,35.0,NaN,NaN,NaN,NaN,NaN,NaN,0.053,361.0,NaN,NaN,192.0,339.0,0.05,42062.0,0.20,15.0,0.18,83.0,136.95,76.0,0.82,1944.0,0.75,1476.0,0.851,NaN,NaN,0.34,242.0,29.0,3.0,3.0,4.0,4.0,3.0,3.0,3.5,3.0,1949.0,1034.277124,0.035,64.0,0.138,61.0,13.6,72.0,NaN,NaN,NaN,NaN,1.1,131.0,2023

In [25]:
with io.capture_output() as captured: 
    df_2022 = pd.read_sas(stars_dir + '2022/2022-07 Stars Release/all_data_2022jul.sas7bdat')
df_2022['Release year'] = ['2022']*df_2022.shape[0]
df_2022 = df_2022.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
df_2022 = df_2022[df_2022['PROVIDER_ID'].isin(prvdrs_2022)]

prvdrs = df_2022['PROVIDER_ID'].unique()
print(len(prvdrs), 'hospitals in 2022')

df_2022.head()

3121 hospitals in 2022

,PROVIDER_ID,HAI_1_DEN_VOL,HAI_2_DEN_VOL,HAI_3_DEN_VOL,HAI_4_DEN_VOL,HAI_5_DEN_VOL,HAI_6_DEN_VOL,HAI_1_DEN_PRED,HAI_2_DEN_PRED,HAI_3_DEN_PRED,HAI_4_DEN_PRED,HAI_5_DEN_PRED,HAI_6_DEN_PRED,HAI_1,HAI_2,HAI_3,HAI_4,HAI_5,HAI_6,READM_30_HOSP_WIDE,READM_30_HIP_KNEE,EDAC_30_HF,READM_30_COPD,EDAC_30_AMI,EDAC_30_PN,MORT_30_STK,MORT_30_PN,MORT_30_HF,MORT_30_COPD,MORT_30_AMI,COMP_HIP_KNEE,READM_30_HOSP_WIDE_DEN,READM_30_HIP_KNEE_DEN,EDAC_30_HF_DEN,READM_30_COPD_DEN,EDAC_30_AMI_DEN,EDAC_30_PN_DEN,MORT_30_STK_DEN,MORT_30_PN_DEN,MORT_30_HF_DEN,MORT_30_COPD_DEN,MORT_30_AMI_DEN,COMP_HIP_KNEE_DEN,OP_2,OP_2_DEN,OP_3B,OP_3B_DEN,OP_8,OP_8_DEN,OP_10,OP_10_DEN,OP_13,OP_13_DEN,OP_18B,OP_18B_DEN,OP_22,OP_22_DEN,OP_23,OP_23_DEN,OP_29,OP_29_DEN,PSI_4_SURG_COMP,PSI_4_SURG_COMP_DEN,PSI_90_SAFETY,IMM_3_DEN,IMM_3,PC_01,PC_01_DEN,SEP_1,SEP_1_DEN,H_RESP_RATE_P,H_COMP_1_STAR_RATING,H_COMP_2_STAR_RATING,H_COMP_3_STAR_RATING,H_COMP_5_STAR_RATING,H_COMP_6_STAR_RATING,H_COMP_7_STAR_RATING,H_GLOB_STAR_RATING,H_INDI_STAR_RATING,H_NUMB_COMP,PSI_90_SAFETY_DEN,MORT_30_CABG,MORT_30_CABG_DEN,READM_30_CABG,READM_30_CABG_DEN,OP_32,OP_32_DEN,OP_33,OP_33_DEN,OP_35_ADM,OP_35_ADM_DEN,OP_35_ED,OP_35_ED_DEN,OP_36,OP_36_DEN,Release year
0,010001,8391.0,13866.0,171.0,229.0,102470.0,102470.0,8.711,19.223,4.938,2.025,7.631,78.514,0.574,0.312,0.608,0.0,0.786,0.560,0.155,0.049,16.1,0.212,6.5,-7.1,0.198,0.145,0.089,0.083,0.116,0.026,1805.0,165.0,904.0,310.0,424.0,503.0,533.0,474.0,725.0,270.0,412.0,175.0,NaN,NaN,NaN,NaN,0.459,122.0,0.040,925.0,0.048,147.0,183.0,176.0,0.03,59762.0,NaN,NaN,0.90,52.0,184.28,115.0,0.81,4817.0,0.97,0.00,18.0,0.55,56.0,21.0,3.0,3.0,3.0,3.0,4.0,3.0,3.5,3.5,507.0,2828.228824,0.038,200.0,0.135,193.0,14.1,511.0,NaN,NaN,11.3,192.0,6.7,192.0,0.9,1003.0,2022
1,010005,2864.0,8199.0,79.0,NaN,37761.0,35442.0,1.808,4.570,2.084,NaN,1.506,11.292,0.553,0.875,0.480,NaN,1.328,0.708,0.147,0.039,15.5,0.181,-17.4,12.9,0.155,0.180,0.167,0.086,0.124,0.020,764.0,168.0,223.0,378.0,36.0,468.0,122.0,477.0,213.0,314.0,57.0,166.0,NaN,NaN,NaN,NaN,0.415,94.0,0.149,739.0,0.013,154.0,122.0,588.0,0.02,68296.0,0.67,12.0,0.97,180.0,145.66,40.0,1.19,1915.0,0.91,0.03,105.0,0.64,145.0,30.0,3.0,4.0,3.0,3.0,4.0,3.0,3.0,3.0,568.0,1106.469176,NaN,NaN,NaN,NaN,14.8,1086.0,1.00,21.0,9.5,120.0,5.4,120.0,0.9,514.0,2022
2,010006,6011.0,10398.0,92.0,NaN,63658.0,62016.0,5.334,10.217,2.432,NaN,4.672,28.079,0.562,0.392,0.411,NaN,1.070,0.356,0.157,0.048,-8.1,0.182,0.1,39.2,0.150,0.163,0.124,0.078,0.157,0.032,1563.0,306.0,615.0,381.0,363.0,663.0,286.0,634.0,528.0,331.0,344.0,306.0,NaN,NaN,NaN,NaN,0.279,61.0,0.158,728.0,0.007,152.0,171.0,183.0,0.01,47004.0,NaN,NaN,0.92,89.0,193.03,87.0,1.19,2456.0,0.93,0.00,15.0,0.33,54.0,23.0,3.0,3.0,1.0,2.0,2.0,2.0,3.0,3.0,1136.0,2131.116508,0.034,127.0,0.138,120.0,13.6,1908.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,502.0,2022
3,010007,NaN,NaN,NaN,NaN,NaN,5230.0,NaN,NaN,NaN,NaN,NaN,2.033,NaN,NaN,NaN,NaN,NaN,0.000,0.157,NaN,8.0,0.200,NaN,13.9,NaN,0.192,0.126,0.089,NaN,NaN,144.0,NaN,70.0,103.0,NaN,147.0,NaN,152.0,67.0,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.022,90.0,NaN,NaN,110.0,586.0,0.02,12514.0,NaN,NaN,0.92,169.0,NaN,NaN,0.94,NaN,NaN,NaN,NaN,1.00,32.0,27.0,3.0,3.0,3.0,4.0,4.0,4.0,3.0,4.0,179.0,188.206619,NaN,NaN,NaN,NaN,18.4,184.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,31.0,2022
5,010011,10861.0,11435.0,151.0,NaN,81783.0,81783.0,11.733,14.720,4.032,NaN,8.211,95.085,0.511,0.611,0.992,NaN,0.609,0.252,0.163,0.042,64.8,0.195,33.4,27.4,0.139,0.161,0.110,0.089,0.143,0.025,918.0,43.0,351.0,166.0,126.0,349.0,104.0,331.0,305.0,150.0,123.0,49.0,NaN,NaN,NaN,NaN,NaN,NaN,0.073,259.0,NaN,NaN,183.0,87.0,0.03,52482.0,NaN,NaN,NaN,NaN,161.70,82.0,1.06,NaN,NaN,NaN,NaN,0.34,47.0,31.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.5,2139.0,1327.131542,0.041,69.0,0.153,64.0,16.6,96.0,0.75,40.0,NaN,NaN,NaN,NaN,1.0,248.0,2022

In [26]:
with io.capture_output() as captured: 
    df_2021 = pd.read_sas(stars_dir + '2021/2021-04 Stars Release/all_data_2021apr.sas7bdat')
df_2021['Release year'] = ['2021']*df_2021.shape[0]
df_2021 = df_2021.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
df_2021 = df_2021[df_2021['PROVIDER_ID'].isin(prvdrs_2021)]

print(df_2021.shape)
prvdrs = df_2021['PROVIDER_ID'].unique()
print(len(prvdrs), 'hospitals in 2021')
df_2021.head()

(3355, 100)
3355 hospitals in 2021

,PROVIDER_ID,HAI_1_DEN_VOL,HAI_2_DEN_VOL,HAI_3_DEN_VOL,HAI_4_DEN_VOL,HAI_5_DEN_VOL,HAI_6_DEN_VOL,HAI_1_DEN_PRED,HAI_2_DEN_PRED,HAI_3_DEN_PRED,HAI_4_DEN_PRED,HAI_5_DEN_PRED,HAI_6_DEN_PRED,HAI_1,HAI_2,HAI_3,HAI_4,HAI_5,HAI_6,READM_30_HOSP_WIDE,READM_30_HIP_KNEE,EDAC_30_HF,READM_30_COPD,EDAC_30_AMI,EDAC_30_PN,MORT_30_STK,MORT_30_PN,MORT_30_HF,MORT_30_COPD,MORT_30_AMI,COMP_HIP_KNEE,READM_30_HOSP_WIDE_DEN,READM_30_HIP_KNEE_DEN,EDAC_30_HF_DEN,READM_30_COPD_DEN,EDAC_30_AMI_DEN,EDAC_30_PN_DEN,MORT_30_STK_DEN,MORT_30_PN_DEN,MORT_30_HF_DEN,MORT_30_COPD_DEN,MORT_30_AMI_DEN,COMP_HIP_KNEE_DEN,OP_2,OP_2_DEN,OP_3B,OP_3B_DEN,OP_8,OP_8_DEN,OP_10,OP_10_DEN,OP_13,OP_13_DEN,OP_18B,OP_18B_DEN,OP_22,OP_22_DEN,OP_23,OP_23_DEN,OP_29,OP_29_DEN,OP_30,OP_30_DEN,PSI_4_SURG_COMP,PSI_4_SURG_COMP_DEN,PSI_90_SAFETY,IMM_3_DEN,IMM_3,PC_01,PC_01_DEN,SEP_1,SEP_1_DEN,ED_2B,ED_2B_DEN,H_RESP_RATE_P,H_COMP_1_STAR_RATING,H_COMP_2_STAR_RATING,H_COMP_3_STAR_RATING,H_COMP_5_STAR_RATING,H_COMP_6_STAR_RATING,H_COMP_7_STAR_RATING,H_GLOB_STAR_RATING,H_INDI_STAR_RATING,H_NUMB_COMP,PSI_90_SAFETY_DEN,MORT_30_CABG,MORT_30_CABG_DEN,READM_30_CABG,READM_30_CABG_DEN,OP_32,OP_32_DEN,OP_33,OP_33_DEN,OP_35_ADM,OP_35_ADM_DEN,OP_35_ED,OP_35_ED_DEN,OP_36,OP_36_DEN,Release year
0,010001,7846.0,13268.0,165.0,216.0,102765.0,102765.0,8.086,18.498,4.615,1.884,7.305,76.294,0.742,0.324,0.650,0.0,0.548,0.537,0.156,0.046,21.6,0.207,7.0,-20.6,0.166,0.157,0.113,0.084,0.119,0.023,4474.0,258.0,1106.0,443.0,620.0,594.0,644.0,554.0,858.0,374.0,586.0,250.0,NaN,NaN,NaN,NaN,0.389,211.0,0.072,2117.0,0.028,211.0,178.0,349.0,0.03,57844.0,NaN,NaN,0.81,64.0,0.98,162.0,170.87,165.0,0.93,4817.0,0.97,0.00,24.0,0.60,102.0,103.0,655.0,21.0,3.0,3.0,3.0,3.0,4.0,3.0,3.5,3.5,507.0,3896.300852,0.047,281.0,0.149,268.0,13.4,606.0,NaN,NaN,10.8,190.0,7.1,190.0,0.8,993.0,2021
1,010005,3088.0,7928.0,74.0,NaN,40143.0,37697.0,1.988,4.660,1.970,NaN,1.548,12.386,0.000,1.073,0.508,NaN,1.938,0.565,0.159,0.039,10.2,0.187,-7.0,22.9,0.171,0.195,0.168,0.099,0.138,0.023,2018.0,221.0,304.0,591.0,52.0,625.0,169.0,637.0,291.0,502.0,80.0,213.0,NaN,NaN,62.0,18.0,0.427,246.0,0.142,1504.0,0.033,273.0,115.0,1408.0,0.02,71631.0,0.71,24.0,0.82,204.0,0.94,413.0,190.88,51.0,1.00,1915.0,0.91,0.03,193.0,0.68,330.0,82.0,1034.0,30.0,3.0,4.0,3.0,3.0,4.0,3.0,3.0,3.0,568.0,1538.334998,NaN,NaN,NaN,NaN,16.3,1150.0,1.0,12.0,11.1,121.0,6.2,121.0,1.1,483.0,2021
2,010006,5874.0,10270.0,90.0,NaN,64819.0,62418.0,4.781,8.992,2.439,NaN,4.588,28.161,0.000,0.222,0.820,NaN,0.654,0.426,0.152,0.046,-17.8,0.186,-5.5,27.5,0.125,0.184,0.125,0.095,0.157,0.028,3620.0,392.0,771.0,565.0,443.0,763.0,362.0,738.0,659.0,489.0,422.0,363.0,NaN,NaN,NaN,NaN,0.429,119.0,0.145,1386.0,0.026,265.0,152.0,362.0,0.01,41321.0,NaN,NaN,0.81,94.0,0.87,125.0,217.08,109.0,1.07,2456.0,0.93,0.00,35.0,0.33,105.0,110.0,552.0,23.0,3.0,3.0,1.0,2.0,2.0,2.0,3.0,3.0,1136.0,2816.123681,0.041,139.0,0.132,130.0,16.4,1948.0,NaN,NaN,NaN,NaN,NaN,NaN,1.1,454.0,2021
3,010007,NaN,NaN,NaN,NaN,NaN,4783.0,NaN,NaN,NaN,NaN,NaN,1.840,NaN,NaN,NaN,NaN,NaN,0.000,0.161,NaN,29.1,0.194,NaN,16.9,0.153,0.203,0.141,0.090,NaN,NaN,443.0,NaN,83.0,136.0,NaN,200.0,29.0,205.0,78.0,116.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.091,208.0,NaN,NaN,108.0,1295.0,0.03,1116.0,NaN,NaN,0.13,82.0,0.90,40.0,NaN,NaN,0.92,NaN,NaN,NaN,NaN,0.98,52.0,62.0,525.0,27.0,3.0,3.0,3.0,4.0,4.0,4.0,3.0,4.0,179.0,277.574249,NaN,NaN,NaN,NaN,17.7,213.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,76.0,2021
4,010008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.148,NaN,NaN,0.194,NaN,-3.6,NaN,0.178,0.120,0.105,NaN,NaN,127.0,NaN,NaN,30.0,NaN,39.0,NaN,43.0,27.0,32.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.034,148.0,NaN,NaN,91.0,335.0,0.01,7012.0,NaN,NaN,0.59,34.0,0.97,30.0,NaN,NaN,0.99,189.0,0.48,NaN,NaN,0.43,14.0,86.0,396.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.903206,NaN,NaN,NaN,NaN,17.5,77.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021

## Merge SAS pack output data with the input data

In [27]:
input_df = df_2027.merge(df_2026, how='outer')
input_df = input_df.merge(df_2025, how='outer')
input_df = input_df.merge(df_2024, how='outer')
input_df = input_df.merge(df_2023, how='outer')
input_df = input_df.merge(df_2022, how='outer')
input_df = input_df.merge(df_2021, how='outer')

print(input_df.shape)
prvdrs = input_df['PROVIDER_ID'].unique()
print(len(prvdrs), 'hospitals in input df')
input_df.head()

(21699, 180)
3651 hospitals in input df

,PROVIDER_ID,IMM_3,IMM_3_DEN,OP_18B,OP_18B_DEN,OP_22,OP_22_DEN,OP_23,OP_23_DEN,OP_29,OP_29_DEN,SEP_1,SEP_1_DEN,SAFE_USE_OF_OPIOIDS,SAFE_USE_OF_OPIOIDS_DEN,MORT_30_AMI,MORT_30_AMI_DEN,MORT_30_CABG,MORT_30_CABG_DEN,MORT_30_COPD,MORT_30_COPD_DEN,MORT_30_HF,MORT_30_HF_DEN,MORT_30_PN,MORT_30_PN_DEN,MORT_30_STK,MORT_30_STK_DEN,PSI_4_SURG_COMP,PSI_4_SURG_COMP_DEN,COMP_HIP_KNEE,COMP_HIP_KNEE_DEN,PSI_90_SAFETY,PSI_90_SAFETY_DEN,Hybrid_HWM,Hybrid_HWM_DEN,H_COMP_1_A_P,H_COMP_1_SN_P,H_COMP_1_U_P,H_COMP_1_LINEAR_SCORE,H_COMP_1_STAR_RATING,H_NURSE_RESPECT_A_P,H_NURSE_RESPECT_SN_P,H_NURSE_RESPECT_U_P,H_NURSE_LISTEN_A_P,H_NURSE_LISTEN_SN_P,H_NURSE_LISTEN_U_P,H_NURSE_EXPLAIN_A_P,H_NURSE_EXPLAIN_SN_P,H_NURSE_EXPLAIN_U_P,H_COMP_2_A_P,H_COMP_2_SN_P,H_COMP_2_U_P,H_COMP_2_LINEAR_SCORE,H_COMP_2_STAR_RATING,H_DOCTOR_RESPECT_A_P,H_DOCTOR_RESPECT_SN_P,H_DOCTOR_RESPECT_U_P,H_DOCTOR_LISTEN_A_P,H_DOCTOR_LISTEN_SN_P,H_DOCTOR_LISTEN_U_P,H_DOCTOR_EXPLAIN_A_P,H_DOCTOR_EXPLAIN_SN_P,H_DOCTOR_EXPLAIN_U_P,H_COMP_5_A_P,H_COMP_5_SN_P,H_COMP_5_U_P,H_COMP_5_LINEAR_SCORE,H_COMP_5_STAR_RATING,H_MED_FOR_A_P,H_MED_FOR_SN_P,H_MED_FOR_U_P,H_SIDE_EFFECTS_A_P,H_SIDE_EFFECTS_SN_P,H_SIDE_EFFECTS_U_P,H_COMP_6_N_P,H_COMP_6_Y_P,H_COMP_6_LINEAR_SCORE,H_COMP_6_STAR_RATING,H_DISCH_HELP_N_P,H_DISCH_HELP_Y_P,H_SYMPTOMS_N_P,H_SYMPTOMS_Y_P,H_CLEAN_HSP_A_P,H_CLEAN_HSP_SN_P,H_CLEAN_HSP_U_P,H_CLEAN_LINEAR_SCORE,H_CLEAN_STAR_RATING,H_QUIET_HSP_A_P,H_QUIET_HSP_SN_P,H_QUIET_HSP_U_P,H_QUIET_LINEAR_SCORE,H_QUIET_STAR_RATING,H_HSP_RATING_0_6,H_HSP_RATING_7_8,H_HSP_RATING_9_10,H_HSP_RATING_LINEAR_SCORE,H_HSP_RATING_STAR_RATING,H_RECMND_DN,H_RECMND_DY,H_RECMND_PY,H_RECMND_LINEAR_SCORE,H_RECMND_STAR_RATING,H_STAR_RATING,O-COMP-1,O-COMP-2,O-COMP-3,O-PATIENT-RATE,O-PATIENT-REC,EDAC_30_AMI,EDAC_30_AMI_DEN,EDAC_30_HF,EDAC_30_HF_DEN,EDAC_30_PN,EDAC_30_PN_DEN,OP_32,OP_32_DEN,OP_35_ADM,OP_35_ADM_DEN,OP_35_ED,OP_35_ED_DEN,OP_36,OP_36_DEN,READM_30_CABG,READM_30_CABG_DEN,READM_30_COPD,READM_30_COPD_DEN,READM_30_HIP_KNEE,READM_30_HIP_KNEE_DEN,Hybrid_HWR,Hybrid_HWR_DEN,HAI_1_DEN_PRED,HAI_1_DEN_VOL,HAI_1,HAI_2_DEN_PRED,HAI_2_DEN_VOL,HAI_2,HAI_3_DEN_PRED,HAI_3_DEN_VOL,HAI_3,HAI_4_DEN_PRED,HAI_4_DEN_VOL,HAI_4,HAI_5_DEN_PRED,HAI_5_DEN_VOL,HAI_5,HAI_6_DEN_PRED,HAI_6_DEN_VOL,HAI_6,OP_13,OP_8,OP_10,Release year,H_COMP_3_LINEAR_SCORE,H_COMP_7_LINEAR_SCORE,H_NUMB_COMP,H_RESP_RATE_P,OP_10_DEN,OP_13_DEN,OP-37_NUMB_COMP,OP_8_DEN,READM_30_HOSP_WIDE_DEN,PC_01,PC_01_DEN,H_COMP_7_STAR_RATING,HCP_COVID_19,READM_30_HOSP_WIDE,HCP_COVID_19_DEN,H_COMP_3_STAR_RATING,H_INDI_STAR_RATING,H_GLOB_STAR_RATING,OP_2,OP_2_DEN,OP_3B,OP_3B_DEN,OP_33,OP_33_DEN,OP_30,OP_30_DEN,ED_2B,ED_2B_DEN
0,010001,0.93,4625.0,217.0,395.0,0.03,62163.0,NaN,NaN,0.62,39.0,0.65,141.0,0.14,4583.0,0.114,270.0,0.030,144.0,0.094,112.0,0.102,583.0,0.184,517.0,0.135,395.0,203.00,118.0,0.032,27.0,0.95,NaN,0.045,1835.0,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.0,NaN,NaN,NaN,NaN,87.0,NaN,NaN,NaN,NaN,89.0,NaN,NaN,NaN,NaN,91.0,NaN,NaN,98.0,92.0,97.0,94.0,94.0,-15.6,273.0,-1.1,652.0,17.4,507.0,12.7,234.0,10.0,302.0,5.1,302.0,1.1,651.0,0.101,137.0,0.180,122.0,0.048,25.0,0.151,2824.0,10.399,9871.0,0.288,25.693,18164.0,0.195,6.830,238.0,0.293,0.871,91.0,NaN,9.613,114863.0,0.416,71.953,113805.0,0.459,0.038,0.308,0.053,2027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,010001,0.93,4625.0,222.0,387.0,0.05,57084.0,0.91,11.0,0.72,29.0,0.69,150.0,0.14,4583.0,0.114,270.0,0.030,144.0,0.094,112.0,0.102,583.0,0.184,517.0,0.135,395.0,203.00,118.0,0.032,27.0,0.95,NaN,0.045,1835.0,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.0,NaN,NaN,NaN,NaN,88.0,NaN,NaN,NaN,NaN,89.0,NaN,NaN,NaN,NaN,91.0,NaN,NaN,98.0,93.0,97.0,94.0,94.0,-15.6,273.0,-1.1,652.0,17.4,507.0,12.8,218.0,8.5,261.0,5.7,261.0,0.8,647.0,0.101,137.0,0.180,122.0,0.048,25.0,0.151,2824.0,9.440,8935.0,0.530,23.350,16255.0,0.086,6.562,229.0,0.457,NaN,NaN,NaN,10.937,109019.0,0.183,68.076,109019.0,0.382,0.038,0.308,0.053,2026,82.0,82.0,627.0,17.0,1517.0,365.0,185.0,52.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,010001,0.95,3905.0,214.0,348.0,0.05,52960.0,NaN,NaN,0.47,17.0,0.65,127.0,NaN,NaN,0.120,278.0,0.041,132.0,0.088,107.0,0.089,549.0,0.180,400.0,0.148,398.0,184.68,134.0,0.027,49.0,1.21,2542.038500,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15.4,274.0,23.4,614.0,23.6,403.0,12.9,170.0,11.9,202.0,4.9,202.0,1.1,668.0,0.105,126.0,0.190,117.0,0.038,49.0,NaN,NaN,9.597,9149.0,0.938,24.766,17310.0,0.363,5.994,214.0,1.335,NaN,NaN,NaN,11.400,104733.0,0.965,67.066,104733.0,0.507,0.028,0.380,0.061,2024,NaN,NaN,544.0,15.0,1410.0,178.0,NaN,79.0,2912.0,0.00,32.0,4.0,0.836,0.142,2496.0,3.0,3.5,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,010001,0.96,4115.0,217.0,345.0,0.05,52960.0,NaN,NaN,0.47,17.0,0.68,131.0,0.12,4303.0,0.108,291.0,0.038,157.0,0.079,122.0,0.105,610.0,0.189,489.0,0.137,414.0,194.78,125.0,0.030,32.0,0.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13.8,296.0,10.6,679.0,14.3,490.0,12.9,170.0,11.9,202.0,4.9,202.0,1.1,668.0,0.102,151.0,0.177,130.0,0.044,34.0,NaN,NaN,10.082,9538.0,0.496,23.712,16332.0,0.169,6.618,240.0,1.209,NaN,NaN,NaN,11.232,103195.0,0.445,65.234,103195.0,0.491,0.021,0.333,0.054,2025,NaN,NaN,643.0,17.0,1478.0,193.0,NaN,66.0,2924.0,0.02,46.0,4.0,0.000,0.141,2712.0,3.0,3.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,010001,0.97,3795.0,205.0,323.0,0.03,51079.0,NaN,NaN,0.81,16.0,0.46,146.0,NaN,NaN,0.124,317.0,0.047,172.0,0.085,182.0,0.083,630.0,0.159,407.0,0.164,489.0,173.39,120.0,0.024,102.0,1.01,2046.895485,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.9,319.0,21.8,755.0,-1.5,436.0,14.1,254.0,10.2,214.0,4.7,214.0,1.0,688.0,0.117,165.0,0.199,202.0,0.042,98.0,NaN,NaN,10.597,10024.0,0.661,26.630,17731.0,0.300,4.548,154.0,1.099,1.845,200.0,0.0,9.412,101908.0,0.850,72.686,101451.0,0.660,0.067,0.425,0.057,2023,NaN,NaN,434.0,15.0,1488.0,208.0,NaN,146.0,3058.0,0.09,34.0,3.0,0.737,0.142,2323.0,2.0,3.5,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
main_df = main_df.merge(input_df, how='outer', on=['PROVIDER_ID', 'Release year'])
print(main_df.shape)

main_df.rename(columns={'PROVIDER_ID': 'Facility ID'}, inplace=True)

prvdrs = main_df['Facility ID'].unique()
print(len(prvdrs), 'hospitals in main_df')
print(main_df['Release year'].unique())

main_df.head()

(21699, 315)
3651 hospitals in main_df
['2021' '2022' '2023' '2024' '2025' '2026' '2027']

,Facility ID,Std_Outcomes_Mortality_score,Outcomes_Mortality_cnt,Std_Outcomes_Safety_score,Outcomes_Safety_cnt,Std_Outcomes_Readmission_score,Outcomes_Readmission_cnt,Std_PatientExp_score,Patient_Experience_cnt,Std_Process_score,Process_cnt,std_weight_Mortality,std_weight_Safety,std_weight_Readmission,std_weight_PatientExperience,std_weight_Process,weight_Outcomes_Mortality,weight_Outcomes_Safety,weight_Outcomes_Readmission,weight_PatientExperience,weight_Process,summary_score,Total_measure_group_cnt,MortSafe_Group_cnt,report_indicator,cnt_grp,star,Release year,std_weight_safety,Outcomes_safety_cnt,std_MORT_30_AMI,std_MORT_30_CABG,std_MORT_30_COPD,std_MORT_30_HF,std_MORT_30_PN,std_MORT_30_STK,std_PSI_4_SURG_COMP,std_Hybrid_HWM,mortality_total_cnt,mortality_measure_wt,mortality_score_before_std,mortality_grp_score,mortality_mean,mortality_sd,std_EDAC_30_AMI,std_EDAC_30_HF,std_EDAC_30_PN,std_OP_32,std_OP_35_ADM,std_OP_35_ED,std_OP_36,std_READM_30_CABG,std_READM_30_COPD,std_READM_30_HIP_KNEE,std_Hybrid_HWR,readmission_total_cnt,readmission_measure_wt,readmission_score_before_std,readmission_grp_score,readmission_mean,readmission_sd,std_COMP_HIP_KNEE,std_PSI_90_SAFETY,std_HAI_1,std_HAI_2,std_HAI_3,std_HAI_4,std_HAI_5,std_HAI_6,safety_total_cnt,safety_measure_wt,safety_score_before_std,safety_grp_score,safety_mean,safety_sd,std_IMM_3,std_OP_18B,std_OP_22,std_OP_23,std_OP_29,std_SEP_1,std_SAFE_USE_OF_OPIOIDS,std_OP_13,std_OP_8,std_OP_10,process_total_cnt,process_measure_wt,process_score_before_std,process_grp_score,process_mean,process_sd,std_H_COMP_1_LINEAR_SCORE,std_H_COMP_2_LINEAR_SCORE,std_H_COMP_5_LINEAR_SCORE,std_H_COMP_6_LINEAR_SCORE,std_H_CLEAN_LINEAR_SCORE,std_H_QUIET_LINEAR_SCORE,std_H_HSP_RATING_LINEAR_SCORE,std_H_RECMND_LINEAR_SCORE,std_O-COMP-1,std_O-COMP-2,std_O-COMP-3,std_O-PATIENT-RATE,std_O-PATIENT-REC,patient_exp_total_cnt,patient_exp_measure_wt,patient_exp_score_before_std,patient_exp_grp_score,patient_exp_mean,patient_exp_sd,mortality_Mean,mortality_StdDev,readmission_Mean,readmission_StdDev,safety_Mean,safety_StdDev,process_Mean,process_StdDev,std_H_COMP_3_LINEAR_SCORE,std_H_COMP_7_LINEAR_SCORE,patient_exp_Mean,patient_exp_StdDev,std_READM_30_HOSP_WIDE,std_HCP_COVID_19,std_PC_01,std_H_COMP_1_STAR_RATING,std_H_COMP_2_STAR_RATING,std_H_COMP_3_STAR_RATING,std_H_COMP_5_STAR_RATING,std_H_COMP_6_STAR_RATING,std_H_COMP_7_STAR_RATING,std_H_GLOB_STAR_RATING,std_H_INDI_STAR_RATING,std_OP_3B,std_OP_33,std_OP_30,std_ED_2B,IMM_3,IMM_3_DEN,OP_18B,OP_18B_DEN,OP_22,OP_22_DEN,OP_23,OP_23_DEN,OP_29,OP_29_DEN,SEP_1,SEP_1_DEN,SAFE_USE_OF_OPIOIDS,SAFE_USE_OF_OPIOIDS_DEN,MORT_30_AMI,MORT_30_AMI_DEN,MORT_30_CABG,MORT_30_CABG_DEN,MORT_30_COPD,MORT_30_COPD_DEN,MORT_30_HF,MORT_30_HF_DEN,MORT_30_PN,MORT_30_PN_DEN,MORT_30_STK,MORT_30_STK_DEN,PSI_4_SURG_COMP,PSI_4_SURG_COMP_DEN,COMP_HIP_KNEE,COMP_HIP_KNEE_DEN,PSI_90_SAFETY,PSI_90_SAFETY_DEN,Hybrid_HWM,Hybrid_HWM_DEN,H_COMP_1_A_P,H_COMP_1_SN_P,H_COMP_1_U_P,H_COMP_1_LINEAR_SCORE,H_COMP_1_STAR_RATING,H_NURSE_RESPECT_A_P,H_NURSE_RESPECT_SN_P,H_NURSE_RESPECT_U_P,H_NURSE_LISTEN_A_P,H_NURSE_LISTEN_SN_P,H_NURSE_LISTEN_U_P,H_NURSE_EXPLAIN_A_P,H_NURSE_EXPLAIN_SN_P,H_NURSE_EXPLAIN_U_P,H_COMP_2_A_P,H_COMP_2_SN_P,H_COMP_2_U_P,H_COMP_2_LINEAR_SCORE,H_COMP_2_STAR_RATING,H_DOCTOR_RESPECT_A_P,H_DOCTOR_RESPECT_SN_P,H_DOCTOR_RESPECT_U_P,H_DOCTOR_LISTEN_A_P,H_DOCTOR_LISTEN_SN_P,H_DOCTOR_LISTEN_U_P,H_DOCTOR_EXPLAIN_A_P,H_DOCTOR_EXPLAIN_SN_P,H_DOCTOR_EXPLAIN_U_P,H_COMP_5_A_P,H_COMP_5_SN_P,H_COMP_5_U_P,H_COMP_5_LINEAR_SCORE,H_COMP_5_STAR_RATING,H_MED_FOR_A_P,H_MED_FOR_SN_P,H_MED_FOR_U_P,H_SIDE_EFFECTS_A_P,H_SIDE_EFFECTS_SN_P,H_SIDE_EFFECTS_U_P,H_COMP_6_N_P,H_COMP_6_Y_P,H_COMP_6_LINEAR_SCORE,H_COMP_6_STAR_RATING,H_DISCH_HELP_N_P,H_DISCH_HELP_Y_P,H_SYMPTOMS_N_P,H_SYMPTOMS_Y_P,H_CLEAN_HSP_A_P,H_CLEAN_HSP_SN_P,H_CLEAN_HSP_U_P,H_CLEAN_LINEAR_SCORE,H_CLEAN_STAR_RATING,H_QUIET_HSP_A_P,H_QUIET_HSP_SN_P,H_QUIET_HSP_U_P,H_QUIET_LINEAR_SCORE,H_QUIET_STAR_RATING,H_HSP_RATING_0_6,H_HSP_RATING_7_8,H_HSP_RATING_9_10,H_HSP_RATING_LINEAR_SCORE,H_HSP_RATING_STAR_RATING,H_RECMND_DN,H_RECMND_DY,H_RECMND_PY,H_RECMND_LINEAR_SCORE,H_RECMND_STAR_RATING,H_STAR_RATING,O-COMP-1,O-COMP-2,O-COMP-3,O-PATIENT-RATE,O-PATIENT-REC,EDAC_30_AMI,EDAC_30_AMI_DEN,EDAC_30_HF,EDAC_30_HF_DEN,EDAC_30_PN,EDAC_30_PN_DEN,OP_32,OP_32_DEN,OP_35_ADM,OP_35_ADM_DEN,OP_35_ED,OP_35_ED_DEN,OP_36,OP_36_DEN,READM_30_CABG,READM_30_CABG_DEN,READM_30_COPD,READM_30_COPD_DEN,READM_30_HIP_KNEE,READM_30_HIP_KNEE_DEN,Hybrid_HWR,Hybrid_HWR_DEN,HAI_1_DEN_PRED,HAI_1_DEN_VOL,HAI_1,HAI_2_DEN_PRED,HAI_2_DEN_VOL,HAI_2,HAI_3_DEN_PRED,HAI_3_DEN_VOL,HAI_3,HAI_4_DEN_PRED,HAI_4_DEN_VOL,HAI_4,HAI_5_DEN_PRED,HAI_5_DEN_VOL,HAI_5,HAI_6_DEN_PRED,HAI_6_DEN_VOL,HAI_6,OP_13,OP_8,OP_10,H_COMP_3_LINEAR_SCORE,H_COMP_7_LINEAR_SCORE,H_NUMB_COMP,H_RESP_RATE_P,OP_10_DEN,OP_13_DEN,OP-37_NUMB_COMP,OP_8_DEN,READM_30_HOSP_WIDE_DEN,PC_01,PC_01_DEN,H_COMP_7_STAR_RATING,HCP_COVID_19,READM_30_HOSP_WIDE,HCP_COVID_19_DEN,H_COMP_3_STAR_RATING,H_INDI_STAR_RATING,H_GLOB_STAR_RATING,OP_2,OP_2_DEN,OP_3B,OP_3B_DEN,OP_33,OP_33_DEN,OP_30,OP_30_DEN,ED_2B,ED_2B_DEN
0,010001,-0.752932,7,0.556127,NaN,-0.070355,11,0.071425,8,-0.050316,11,0.22,NaN,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.049100,5,2,1,3.0,3.0,2021,0.22,8.0,0.730853,-2.055159,0.069106,0.103403,-0.022557,-1.941449,-0.327016,NaN,7.0,0.142857,-0.491831,-0.752932,NaN,NaN,-0.027028,-0.705673,1.039984,2.185101,1.182600,-1.185780,1.207127,-1.542989,-1.037529,-1.164917,NaN,11.0,0.090909,-0.010885,-0.070355,NaN,NaN,0.303431,0.319230,-0.078888,0.680925,0.244905,1.037183,0.403644,0.098335,8.0,0.125000,0.376096,0.556127,NaN,NaN,0.644574,-0.761776,-0.979501,NaN,-0.459111,0.031191,NaN,0.684379,0.140655,-0.102729,11.0,0.090909,0.007553,-0.050316,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,0.125,0.060398,0.071425,NaN,NaN,-0.004941,0.646660,0.027901,0.551294,0.009921,0.658437,0.037755,0.600242,NaN,NaN,-1.104271e-16,0.845613,-0.070634,NaN,0.473469,-0.537213,-0.085263,-0.269656,-0.073296,0.801144,-0.115323,0.284361,0.478432,NaN,NaN,0.466001,-0.054072,0.97,4817.0,178.0,349.0,0.03,57844.0,NaN,NaN,0.81,64.0,0.60,102.0,NaN,NaN,0.119,586.0,0.047,281.0,0.084,374.0,0.113,858.0,0.157,554.0,0.166,644.0,170.87,165.0,0.023,250.0,0.93,3896.300852,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,620.0,21.6,1106.0,-20.6,594.0,13.4,606.0,10.8,190.0,7.1,190.0,0.8,993.0,0.149,268.0,0.207,443.0,0.046,258.0,NaN,NaN,8.086,7846.0,0.742,18.498,13268.0,0.324,4.615,165.0,0.650,1.884,216.0,0.0,7.305,102765.0,0.548,76.294,102765.0,0.537,0.028,0.389,0.072,NaN,NaN,507.0,21.0,2117.0,211.0,NaN,211.0,4474.0,0.00,24.0,3.0,NaN,0.156,NaN,3.0,3.5,3.5,NaN,NaN,NaN,NaN,NaN,NaN,0.98,162.0,103.0,655.0
1,010001,-0.846744,7,0.591483,NaN,-0.321758,11,0.072100,8,-0.320038,9,0.22,NaN,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.149487,5,2,1,3.0,3.0,2022,0.22,8.0,0.703271,-1.054647,-0.072635,1.355101,0.507204,-3.873239,-1.364075,NaN,7.0,0.142857,-0.542717,-0.846744,NaN,NaN,0.012064,-0.457136,0.497621,1.664542,0.602150,-0.703618,0.623486,-0.606328,-1.470080,-1.684933,NaN,11.0,0.090909,-0.143203,-0.321758,NaN,NaN,-0.427377,1.040003,0.325583,0.722043,0.295950,1.045465,0.077072,-0.002603,8.0,0.125000,0.384517,0.591483,NaN,NaN,0.643289,-0.906488,-0.863287,NaN,0.009932,-0.264434,NaN,-0.520081,-0.897899,0.376713,9.0,0.111111,-0.220009,-0.320038,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,0.125,0.060979,0.072100,NaN,NaN,0.000879,0.641984,0.027686,0.531111,0.002796,0.645363,0.040971,0.815466,NaN,NaN,-5.363828e-17,0.845760,-0.053004,NaN,0.442175,-0.536306,-0.084743,-0.269007,-0.072623,0.801375,-0.116805,0.284308,0.481635,NaN,NaN,NaN,NaN,0.97,4817.0,183.0,176.0,0.03,59762.0,NaN,NaN,0.90,52.0,0.55,56.0,NaN,NaN,0.116,412.0,0.038,200.0,0.083,270.0,0.089,725.0,0.145,474.0,0.198,533.0,184.28,115.0,0.026,175.0,0.81,2828.228824,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.5,424.0,16.1,904.0,-7.1,503.0,14.1,511.0,11.3,192.0,6.7,192.0,0.9,1003.0,0.135,193.0,0.212,310.0,0.049,165.0,NaN,NaN,8.711,8391.0,0.574,19.223,13866.0,0.312,4.938,171.0,0.608,2.025,229.0,0.0,7.631,102470.0,0.786,78.514,102470.0,0.560,0.048,0.459,0.040,NaN,NaN,507.0,21.0,925.0,147.0,NaN,122.0,1805.0,0.00,18.0,3.0,NaN,0.155,NaN,3.0,3.5,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,010001,-0.647058,7,0.312074,NaN,0.284081,11,-0.127836,8,-1.024044,10,0.22,NaN,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.162208,5,2,1,3.0,3.0,2023,0.22,8.0,-0.041613,-2.197810,-0.019543,1.708727,0.366398,-1.543654,-1.741473,NaN,7.0,0.142857,-0.495567,-0.647058,NaN,NaN,0.207832,-0.702681,0.286040,0.105508,0.159253,0.872692,0.062022,0.219318,-0.048609,-0.198058,NaN,11.0,0.090909,0.171616,0.284081,NaN,NaN,0.024204,-0.212425,0.444297,0.745807,-0.407579,1.025843,0.314693,-0.315731,8.0,0.125000,0.202389,0.312074,NaN,NaN,0.992908,-0.904124,-0.237088,NaN,-0.634479,-0.609958,NaN,-1.779470,0.488322,0.101850,10.0,0.100000,-0.538475,-1.024044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,0.125,-0.109237,-0.127836,NaN,NaN,-0.051260,0.686658,0.020822,0.530811,-0.013939,0.693192,0.030917,0.556023,NaN,NaN,2.611408e-16,0.854510,0.924456,-1.039363,-1.763346,-1.075850,-0.175531,-1.051153,0.808598,0.688370,0.037272,-0.445032,0.339427,NaN,NaN,NaN,NaN,0.97,3795.0,205.0,323.0,0.03,51079.0,NaN,NaN,0.81,16.0,0.46,146.0,NaN,NaN,0.124,317.0,0.047,172.0,0.085,182.0,0.083,630.0,0.159,407.0,0.164,489.0,173.39,120.0,0.024,102.0,1.01,2046.895485,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.9,319.0,21.8,755.0,-1.5,436.0,14.1,254.0,10.2,214.0,4.7,214.0,1.0,688.0,0.117,165.0,0.199,202.0,0.042,98.0,NaN,NaN,10.597,10024.0,0.661,26.630,17731.0,0.300,4.548,154.0,1.099,1.845,200.0,0.0,9.412,101908.0,0.850,72.686,101451.0,0.660,0.067,0.425,0.057,NaN,NaN,434.0,15.0,1488.0,208.0,NaN,146.0,3058.0,0.09,34.0,3.0,0.737,0.142,2323.0,2.0,3.5,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,010001,0.007071,7,-0.146867,NaN,0.230867,11,0.137779,8,-0.677624,10,0.22,NaN,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.030968,5,2,1,3.0,3.0,2024,0.22,7.0,0.470514,-1.535074,0.282996,1.510467,0.129818,-0.554262,-0.748332,NaN,7.0,0.142857,-0.063411,0.007071,NaN,NaN,1.123231,-0.791585,-0.633920,0.292070,-1.032330,0.626949,-0.252865,0.584835,0.293805,0.886353,NaN,11.0,0.090909,0.138216,0.230867,NaN,NaN,0.879845,-1.162386,-0.232451,0.488068,-0.711660,NaN,-0.210159,0.003034,7.0,0.142857,-0.135101,-0.146867,NaN,NaN,0.940083,-0.942734,-1.140182,NaN,-3.129707,0.371166,NaN,0.419351,0.000412,-0.029295,10.0,0.100000,-0.335877,-0.677624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,0.125,0.119895,0.137779,NaN,NaN,-0.068391,0.704371,0.014038,0.537879,-0.021526,0.773315,0.029039,0.538522,NaN,NaN,1.093644e-15,0.870204,0.423838,-0.431525,0.583665,-0.373358,-0.400063,-0.243371,0.124487,0.479704,0.876397,0.133873,0.361496,NaN,NaN,NaN,NaN,0.95,3905.0,214.0,348.0,0.05,52960.0,NaN,NaN,0.47,17.0,0.65,127.0,NaN,NaN,0.120,278.0,0.041,132.0,0.088,107.0,0.089,549.0,0.180,400.0,0.148,398.0,184.68,134.0,0.027,49.0,1.21,2542.038500,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15.4,274.0,23.4,614.0,23.6,403.0,12.9,170.0,11.9,202.0,4.9,202.0,1.1,668.0,0.105,126.0,0.190,117.0,0.038,49.0,NaN,NaN,9.597,9149.0,0.938,24.766,17310.0,0.363,5.994,214.0,1.335,NaN,NaN,NaN,11.400,104733.0,0.965,67.066,104733.0,0.507,0.028,0.380,0.061,NaN,NaN,544.0,15.0,1410.0,178.0,NaN,79.0,2912.0,0.00,32.0,4.0,0.836,0.142,2496.0,3.0,3.5,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,010001,0.296110,7,0.344883,NaN,0.361406,11,0.042072,8,-0.484678,11,0.22,NaN,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,0.171622,5,2,1,3.0,4.0,2025,0.22,7.0,1.405923,-1.045370,1.011496,0.650904,-0.315375,0.023766,-0.732077,NaN,7.0,0.142857,0.142753,0.296110,NaN,NaN,1.024273,-0.368843,-0.448127,0.289973,-1.028886,0.627910,-0.257980,0.607499,0.859382,0.192452,NaN,11.0,0.090909,0.206001,0.361406,NaN,NaN,0.698729,0.103001,0.303670,0.739078,-0.467783,NaN,0.476446,-0.105703,7.0,0.142857,0.249634,0.344883,NaN,NaN,1.044716,-1.062058,-1.138829,NaN,-3.171398,0.449772,0.563049,0.781373,0.588011,0.080291,11.0,0.090909,-0.204464,-0.484678,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,0.125,0.036435,0.042072,NaN,NaN,-0.073484,0.730255,0.013108,0.533730,-0.019030,0.779001,0.028411,0.480473,NaN,NaN,4.899789e-17,0.866021,0.768359,-0.525017,0.140984,-1.154064,0.570761,-0.231671,-0.254181,-0.312251,0.933177,0.719371,0.020336,NaN,NaN,NaN,NaN,0.96,4115.0,217.0,345.0,0.05,52960.0,NaN,NaN,0.47,17.0,0.68,131.0,0.12,4303.0,0.108,291.0,0.038,157.0,0.079,122.0,0.105,610.0,0.189,489.0,0.137,414.0,194.78,125.0,0.030,32.0,0.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13.8,296.0,10.6,679.0,14.3,490.0,12.9,170.0,11.9,202.0,4.9,202.0,1.1,668.0,0.102,151.0,0.177,130.0,0.044,34.0,NaN,NaN,10.082,9538.0,0.496,23.712,16332.0,0.169,6.618,240.0,1.209,NaN,NaN,NaN,11.232,103195.0,0.445,65.234,103195.0,0.491,0.021,0.333,0.054,NaN,NaN,643.0,17.0,1478.0,193.0,NaN,66.0,2924.0,0.02,46.0,4.0,0.000,0.141,2712.0,3.0,3.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
tdf = main_df[main_df['Release year'] == '2027']
tdf = tdf[tdf['Facility ID'].isin(['140119', '140063', '140029'])]
print(tdf.shape)
tdf.head()

(3, 315)

,Facility ID,Std_Outcomes_Mortality_score,Outcomes_Mortality_cnt,Std_Outcomes_Safety_score,Outcomes_Safety_cnt,Std_Outcomes_Readmission_score,Outcomes_Readmission_cnt,Std_PatientExp_score,Patient_Experience_cnt,Std_Process_score,Process_cnt,std_weight_Mortality,std_weight_Safety,std_weight_Readmission,std_weight_PatientExperience,std_weight_Process,weight_Outcomes_Mortality,weight_Outcomes_Safety,weight_Outcomes_Readmission,weight_PatientExperience,weight_Process,summary_score,Total_measure_group_cnt,MortSafe_Group_cnt,report_indicator,cnt_grp,star,Release year,std_weight_safety,Outcomes_safety_cnt,std_MORT_30_AMI,std_MORT_30_CABG,std_MORT_30_COPD,std_MORT_30_HF,std_MORT_30_PN,std_MORT_30_STK,std_PSI_4_SURG_COMP,std_Hybrid_HWM,mortality_total_cnt,mortality_measure_wt,mortality_score_before_std,mortality_grp_score,mortality_mean,mortality_sd,std_EDAC_30_AMI,std_EDAC_30_HF,std_EDAC_30_PN,std_OP_32,std_OP_35_ADM,std_OP_35_ED,std_OP_36,std_READM_30_CABG,std_READM_30_COPD,std_READM_30_HIP_KNEE,std_Hybrid_HWR,readmission_total_cnt,readmission_measure_wt,readmission_score_before_std,readmission_grp_score,readmission_mean,readmission_sd,std_COMP_HIP_KNEE,std_PSI_90_SAFETY,std_HAI_1,std_HAI_2,std_HAI_3,std_HAI_4,std_HAI_5,std_HAI_6,safety_total_cnt,safety_measure_wt,safety_score_before_std,safety_grp_score,safety_mean,safety_sd,std_IMM_3,std_OP_18B,std_OP_22,std_OP_23,std_OP_29,std_SEP_1,std_SAFE_USE_OF_OPIOIDS,std_OP_13,std_OP_8,std_OP_10,process_total_cnt,process_measure_wt,process_score_before_std,process_grp_score,process_mean,process_sd,std_H_COMP_1_LINEAR_SCORE,std_H_COMP_2_LINEAR_SCORE,std_H_COMP_5_LINEAR_SCORE,std_H_COMP_6_LINEAR_SCORE,std_H_CLEAN_LINEAR_SCORE,std_H_QUIET_LINEAR_SCORE,std_H_HSP_RATING_LINEAR_SCORE,std_H_RECMND_LINEAR_SCORE,std_O-COMP-1,std_O-COMP-2,std_O-COMP-3,std_O-PATIENT-RATE,std_O-PATIENT-REC,patient_exp_total_cnt,patient_exp_measure_wt,patient_exp_score_before_std,patient_exp_grp_score,patient_exp_mean,patient_exp_sd,mortality_Mean,mortality_StdDev,readmission_Mean,readmission_StdDev,safety_Mean,safety_StdDev,process_Mean,process_StdDev,std_H_COMP_3_LINEAR_SCORE,std_H_COMP_7_LINEAR_SCORE,patient_exp_Mean,patient_exp_StdDev,std_READM_30_HOSP_WIDE,std_HCP_COVID_19,std_PC_01,std_H_COMP_1_STAR_RATING,std_H_COMP_2_STAR_RATING,std_H_COMP_3_STAR_RATING,std_H_COMP_5_STAR_RATING,std_H_COMP_6_STAR_RATING,std_H_COMP_7_STAR_RATING,std_H_GLOB_STAR_RATING,std_H_INDI_STAR_RATING,std_OP_3B,std_OP_33,std_OP_30,std_ED_2B,IMM_3,IMM_3_DEN,OP_18B,OP_18B_DEN,OP_22,OP_22_DEN,OP_23,OP_23_DEN,OP_29,OP_29_DEN,SEP_1,SEP_1_DEN,SAFE_USE_OF_OPIOIDS,SAFE_USE_OF_OPIOIDS_DEN,MORT_30_AMI,MORT_30_AMI_DEN,MORT_30_CABG,MORT_30_CABG_DEN,MORT_30_COPD,MORT_30_COPD_DEN,MORT_30_HF,MORT_30_HF_DEN,MORT_30_PN,MORT_30_PN_DEN,MORT_30_STK,MORT_30_STK_DEN,PSI_4_SURG_COMP,PSI_4_SURG_COMP_DEN,COMP_HIP_KNEE,COMP_HIP_KNEE_DEN,PSI_90_SAFETY,PSI_90_SAFETY_DEN,Hybrid_HWM,Hybrid_HWM_DEN,H_COMP_1_A_P,H_COMP_1_SN_P,H_COMP_1_U_P,H_COMP_1_LINEAR_SCORE,H_COMP_1_STAR_RATING,H_NURSE_RESPECT_A_P,H_NURSE_RESPECT_SN_P,H_NURSE_RESPECT_U_P,H_NURSE_LISTEN_A_P,H_NURSE_LISTEN_SN_P,H_NURSE_LISTEN_U_P,H_NURSE_EXPLAIN_A_P,H_NURSE_EXPLAIN_SN_P,H_NURSE_EXPLAIN_U_P,H_COMP_2_A_P,H_COMP_2_SN_P,H_COMP_2_U_P,H_COMP_2_LINEAR_SCORE,H_COMP_2_STAR_RATING,H_DOCTOR_RESPECT_A_P,H_DOCTOR_RESPECT_SN_P,H_DOCTOR_RESPECT_U_P,H_DOCTOR_LISTEN_A_P,H_DOCTOR_LISTEN_SN_P,H_DOCTOR_LISTEN_U_P,H_DOCTOR_EXPLAIN_A_P,H_DOCTOR_EXPLAIN_SN_P,H_DOCTOR_EXPLAIN_U_P,H_COMP_5_A_P,H_COMP_5_SN_P,H_COMP_5_U_P,H_COMP_5_LINEAR_SCORE,H_COMP_5_STAR_RATING,H_MED_FOR_A_P,H_MED_FOR_SN_P,H_MED_FOR_U_P,H_SIDE_EFFECTS_A_P,H_SIDE_EFFECTS_SN_P,H_SIDE_EFFECTS_U_P,H_COMP_6_N_P,H_COMP_6_Y_P,H_COMP_6_LINEAR_SCORE,H_COMP_6_STAR_RATING,H_DISCH_HELP_N_P,H_DISCH_HELP_Y_P,H_SYMPTOMS_N_P,H_SYMPTOMS_Y_P,H_CLEAN_HSP_A_P,H_CLEAN_HSP_SN_P,H_CLEAN_HSP_U_P,H_CLEAN_LINEAR_SCORE,H_CLEAN_STAR_RATING,H_QUIET_HSP_A_P,H_QUIET_HSP_SN_P,H_QUIET_HSP_U_P,H_QUIET_LINEAR_SCORE,H_QUIET_STAR_RATING,H_HSP_RATING_0_6,H_HSP_RATING_7_8,H_HSP_RATING_9_10,H_HSP_RATING_LINEAR_SCORE,H_HSP_RATING_STAR_RATING,H_RECMND_DN,H_RECMND_DY,H_RECMND_PY,H_RECMND_LINEAR_SCORE,H_RECMND_STAR_RATING,H_STAR_RATING,O-COMP-1,O-COMP-2,O-COMP-3,O-PATIENT-RATE,O-PATIENT-REC,EDAC_30_AMI,EDAC_30_AMI_DEN,EDAC_30_HF,EDAC_30_HF_DEN,EDAC_30_PN,EDAC_30_PN_DEN,OP_32,OP_32_DEN,OP_35_ADM,OP_35_ADM_DEN,OP_35_ED,OP_35_ED_DEN,OP_36,OP_36_DEN,READM_30_CABG,READM_30_CABG_DEN,READM_30_COPD,READM_30_COPD_DEN,READM_30_HIP_KNEE,READM_30_HIP_KNEE_DEN,Hybrid_HWR,Hybrid_HWR_DEN,HAI_1_DEN_PRED,HAI_1_DEN_VOL,HAI_1,HAI_2_DEN_PRED,HAI_2_DEN_VOL,HAI_2,HAI_3_DEN_PRED,HAI_3_DEN_VOL,HAI_3,HAI_4_DEN_PRED,HAI_4_DEN_VOL,HAI_4,HAI_5_DEN_PRED,HAI_5_DEN_VOL,HAI_5,HAI_6_DEN_PRED,HAI_6_DEN_VOL,HAI_6,OP_13,OP_8,OP_10,H_COMP_3_LINEAR_SCORE,H_COMP_7_LINEAR_SCORE,H_NUMB_COMP,H_RESP_RATE_P,OP_10_DEN,OP_13_DEN,OP-37_NUMB_COMP,OP_8_DEN,READM_30_HOSP_WIDE_DEN,PC_01,PC_01_DEN,H_COMP_7_STAR_RATING,HCP_COVID_19,READM_30_HOSP_WIDE,HCP_COVID_19_DEN,H_COMP_3_STAR_RATING,H_INDI_STAR_RATING,H_GLOB_STAR_RATING,OP_2,OP_2_DEN,OP_3B,OP_3B_DEN,OP_33,OP_33_DEN,OP_30,OP_30_DEN,ED_2B,ED_2B_DEN
5743,140029,0.596673,8,-0.312085,8.0,0.008753,11,0.012360,13,0.683379,10,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,0.149260,5,2,1,3.0,4.0,2027,NaN,NaN,0.549731,-0.287137,-0.210701,0.814047,0.344754,0.492327,-0.099581,1.285115,8.0,0.125000,0.361069,0.596673,-0.079043,0.737611,-0.435947,0.001869,-0.188842,0.729419,-0.124323,-0.555220,-1.516488,-0.160137,1.317316,0.362134,0.678503,11.0,0.090909,0.009844,0.008753,0.004851,0.570443,0.570783,-0.373506,-0.798418,0.651655,-1.649534,0.196259,-0.204108,-0.476975,8.0,0.125,-0.260481,-0.312085,-0.015739,0.784216,0.994479,-0.679231,-0.767933,0.401396,0.516146,1.561335,0.360321,1.029388,0.030714,0.446826,10.0,0.100000,0.389344,0.683379,0.023422,0.535459,-0.092594,-0.252971,-0.569247,0.337344,-0.582593,-0.622054,-0.243175,0.007885,0.778961,0.437911,-0.520059,1.005293,0.790351,13.0,0.076923,0.036543,0.012360,0.026098,0.844962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.94,3769.0,192.0,626.0,0.03,55098.0,0.78,18.0,0.99,181.0,0.88,137.0,0.13,3329.0,0.115,164.0,0.029,54.0,0.092,136.0,0.098,402.0,0.154,503.0,0.124,182.0,176.24,43.0,0.032,244.0,1.07,NaN,0.035,1514.0,NaN,NaN,NaN,91.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.0,NaN,NaN,NaN,NaN,78.0,NaN,NaN,NaN,NaN,87.0,NaN,NaN,NaN,NaN,87.0,NaN,NaN,99.0,96.0,97.0,96.0,95.0,17.8,157.0,5.1,455.0,11.9,529.0,12.4,793.0,11.0,156.0,5.8,156.0,1.2,329.0,0.108,52.0,0.171,148.0,0.046,200.0,0.145,2598.0,6.287,5790.0,1.113,5.963,4901.0,0.168,3.075,112.0,1.951,1.114,130.0,0.898,3.787,57979.0,0.792,38.369,49560.0,0.573,0.017,0.367,0.038,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5844,140063,1.609510,6,0.183388,5.0,0.152574,8,-0.583139,13,-0.906711,8,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,0.190908,5,2,1,3.0,4.0,2027,NaN,NaN,-0.137147,NaN,1.084421,1.868628,1.938012,0.609865,NaN,1.285115,6.0,0.166667,1.108149,1.609510,-0.079043,0.737611,NaN,-0.916709,-0.601877,-0.862292,1.137410,0.969865,0.045050,NaN,0.850491,NaN,0.113145,8.0,0.125000,0.091886,0.152574,0.004851,0.570443,NaN,-0.322121,-0.231856,0.981841,NaN,NaN,-0.469603,0.682127,5.0,0.200,0.128078,0.183388,-0.015739,0.784216,1.097372,-1.440702,-2.490563,0.453880,0.516146,-1.663877,0.003759,NaN,NaN,-0.172691,8.0,0.125000,-0.462084,-0.906711,0.023422,0.535459,-0.473033,-0.252971,-0.779496,-2.187770,-1.264779,-0.802066,-1.068601,-0.623436,0.778961,0.437911,0.450205,-0.022825,-0.258314,13.0,0.076923,-0.466632,-0.583139,0.026098,0.844962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.96,1091.0,231.0,363.0,0.06,48939.0,0.79,14.0,0.99,88.0,0.36,131.0,0.15,954.0,0.123,51.0,NaN,NaN,0.072,43.0,0.075,225.0,0.110,216.0,0.122,109.0,NaN,NaN,NaN,NaN,1.06,NaN,0.035,667.0,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81.0,NaN,NaN,NaN,NaN,77.0,NaN,NaN,NaN,NaN,84.0,NaN,NaN,NaN,NaN,84.0,NaN,NaN,99.0,96.0,98.0,94.0,92.0,NaN,NaN,34.9,265.0,24.4,224.0,13.7,949.0,9.3,83.0,4.7,83.0,1.0,421.0,NaN,NaN,0.175,50.0,NaN,NaN,0.149,1069.0,1.349,1651.0,0.741,1.505,1499.0,0.000,0.407,15.0,NaN,0.109,13.0,NaN,1.059,23735.0,0.944,19.890,23735.0,0.101,NaN,NaN,0.067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6003,140119,2.218157,8,0.236000,8.0,0.338884,11,0.300439,13,-1.855979,9,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,0.457848,5,2,1,3.0,5.0,2027,NaN,NaN,1.580049,0.669536,1.667226,2.510547,1.901801,1.726477,1.473913,0.927198,8.0,0.125000,1.557093,2.218157,-0.079043,0.737611,-0.067816,-0.358780,0.429057,1.219177,-2.128252,2.217662,0.045050,0.426251,1.900846,0.503559,-2.006944,11.0,0.090909,0.198164,0.338884,0.004851,0.570443,-0.938017,1.476356,0.581435,0.354880,0.254950,-0.107598,0.089333,-0.356644,8.0,0.125,0.169337,0.236000,-0.015739,0.784216,1.200265,-3.920365,-4.213192,NaN,0.598406,-2.408156,0.360321,-0.454123,0.767467,-0.664031,9.0,0.111111,-0.970379,-1.855979,0.023422,0.535459,0.287844,0.122116,0.061499,0.084833,-0.355198,0.818050,0.582251,0.639206,-0.162060,-0.170878,0.450205,0.491234,0.790351,13.0,0.076923,0.279958,0.300439,0.026098,0.844962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.98,14131.0,358.0,374.0,0.09,68557.0,NaN,NaN,1.00,95.0,0.24,78.0,0.13,7390.0,0.103,104.0,0.021,97.0,0.063,85.0,0.061,508.0,0.111,300.0,0.103,298.0,139.78,270.0,0.043,268.0,0.71,NaN,0.037,2393.0,NaN,NaN,NaN,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.0,NaN,NaN,NaN,NaN,86.0,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,90.0,NaN,NaN,98.0,95.0,98.0,95.0,95.0,8.8,141.0,16.8,657.0,-6.8,326.0,12.0,2305.0,13.7,889.0,3.8,889.0,1.0,1115.0,0.102,95.0,0.166,96.0,0.045,269.0,0.164,4347.0,33.748,30144.0,0.207,21.922,13620.0,0.319,7.711,276.0,0.648,2.534,276.0,1.184,8.016,157110.0,0.624,104.910,137656.0,0.524,0.042,0.310,0.090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Load general hospital information from hospitals-data-archive project

In [30]:
# CMS used July 2021 measure level results for July 2022 star rating reporting
# CMS used October 2020 measure level results for April 2021 star rating reporting

n_dir = stars_dir + 'CareCompare'
ls = ['Facility ID', 'Facility Name', 
      'Address', 'City', 'State', 'ZIP Code', 'County Name',
      'Hospital Type', 'Hospital Ownership', 'Emergency Services', 
      'Meets criteria for promoting interoperability of EHRs', 
      'Hospital overall rating', 
      'Hospital overall rating footnote',
     ]


## 2027
tdf = main_df[main_df['Release year'] == '2027']
prvdrs = tdf['Facility ID'].unique()
df_2027 = pd.read_csv(n_dir + '/hospitals_05_2026/Hospital_General_Information.csv')#, compression='gzip')
df_2027['Hospital overall rating footnote'] = df_2027['Hospital overall rating footnote'].astype(str)
df_2027['Facility ID'] = df_2027['Facility ID'].astype(str)
df_2027 = df_2027[df_2027['Facility ID'].isin(prvdrs_2027)]

cols1 = ['Provider ID', "Measure Start Date", "Measure End Date", 'Hospital Name', 'Address 1', 'City/Town', 
         'County/Parish', 'Telephone Number']
    
cols2 = ['Facility ID', "Start Date", "End Date", 'Facility Name', 'Address', 'City', 'County Name',
         'Phone Number']
    
for i, col in enumerate(cols1):
    if col in list(df_2027):
        df_2027.rename(columns={col: cols2[i]}, inplace=True)

df_2027 = df_2027.filter(items=ls, axis=1)
df_2027['file_month'] = '05'
df_2027['file_year'] = '2026'
df_2027 = df_2027.merge(tdf, how='outer')
print('Release years:', df_2027['Release year'].unique())






## 2026
tdf = main_df[main_df['Release year'] == '2026']
prvdrs = tdf['Facility ID'].unique()
df_2026 = pd.read_csv(n_dir + '/hospitals_11_2025/Hospital_General_Information.csv')#, compression='gzip')
df_2026['Hospital overall rating footnote'] = df_2026['Hospital overall rating footnote'].astype(str)
df_2026['Facility ID'] = df_2026['Facility ID'].astype(str)
df_2026 = df_2026[df_2026['Facility ID'].isin(prvdrs_2026)]

cols1 = ['Provider ID', "Measure Start Date", "Measure End Date", 'Hospital Name', 'Address 1', 'City/Town', 
         'County/Parish', 'Telephone Number']
    
cols2 = ['Facility ID', "Start Date", "End Date", 'Facility Name', 'Address', 'City', 'County Name',
         'Phone Number']
    
for i, col in enumerate(cols1):
    if col in list(df_2026):
        df_2026.rename(columns={col: cols2[i]}, inplace=True)

df_2026 = df_2026.filter(items=ls, axis=1)
df_2026['file_month'] = '10'
df_2026['file_year'] = '2025'
df_2026 = df_2026.merge(tdf, how='outer')
print('Release years:', df_2026['Release year'].unique())


## 2025
tdf = main_df[main_df['Release year'] == '2025']
prvdrs = tdf['Facility ID'].unique()
df_2025 = pd.read_csv(n_dir + '/hospitals_10_2024/Hospital_General_Information.csv')#, compression='gzip')
df_2025['Hospital overall rating footnote'] = df_2025['Hospital overall rating footnote'].astype(str)
df_2025['Facility ID'] = df_2025['Facility ID'].astype(str)
df_2025 = df_2025[df_2025['Facility ID'].isin(prvdrs_2025)]

cols1 = ['Provider ID', "Measure Start Date", "Measure End Date", 'Hospital Name', 'Address 1', 'City/Town', 
         'County/Parish', 'Telephone Number']
    
cols2 = ['Facility ID', "Start Date", "End Date", 'Facility Name', 'Address', 'City', 'County Name',
         'Phone Number']
    
for i, col in enumerate(cols1):
    if col in list(df_2025):
        df_2025.rename(columns={col: cols2[i]}, inplace=True)

df_2025 = df_2025.filter(items=ls, axis=1)
df_2025['file_month'] = '10'
df_2025['file_year'] = '2024'
df_2025 = df_2025.merge(tdf, how='outer')
print('Release years:', df_2025['Release year'].unique())


## 2024
tdf = main_df[main_df['Release year'] == '2024']
prvdrs = tdf['Facility ID'].unique()
df_2024 = pd.read_csv(n_dir + '/hospitals_01_2024/Hospital_General_Information.csv')#, compression='gzip')
df_2024['Hospital overall rating footnote'] = df_2024['Hospital overall rating footnote'].astype(str)
df_2024['Facility ID'] = df_2024['Facility ID'].astype(str)
df_2024 = df_2024[df_2024['Facility ID'].isin(prvdrs_2024)]

cols1 = ['Provider ID', "Measure Start Date", "Measure End Date", 'Hospital Name', 'Address 1', 'City/Town', 
         'County/Parish', 'Telephone Number']
    
cols2 = ['Facility ID', "Start Date", "End Date", 'Facility Name', 'Address', 'City', 'County Name',
         'Phone Number']
    
for i, col in enumerate(cols1):
    if col in list(df_2024):
        df_2024.rename(columns={col: cols2[i]}, inplace=True)

df_2024 = df_2024.filter(items=ls, axis=1)
df_2024['file_month'] = '01'
df_2024['file_year'] = '2024'
df_2024 = df_2024.merge(tdf, how='outer')
print('Release years:', df_2024['Release year'].unique())


## 2023
tdf = main_df[main_df['Release year'] == '2023']
prvdrs = tdf['Facility ID'].unique()
df_2023 = pd.read_csv(n_dir + '/hospitals_01_2023/Hospital_General_Information.csv')#, compression='gzip')
df_2023['Hospital overall rating footnote'] = df_2023['Hospital overall rating footnote'].astype(str)
df_2023['Facility ID'] = df_2023['Facility ID'].astype(str)
df_2023 = df_2023[df_2023['Facility ID'].isin(prvdrs_2023)]
df_2023 = df_2023.filter(items=ls, axis=1)
df_2023['file_month'] = '01'
df_2023['file_year'] = '2023'
df_2023 = df_2023.merge(tdf, how='outer')
print('Release years:', df_2023['Release year'].unique())


## 2022
tdf = main_df[main_df['Release year'] == '2022']
prvdrs = tdf['Facility ID'].unique()
df_2022 = pd.read_csv(n_dir + '/hospitals_07_2021/Hospital_General_Information.csv')#, compression='gzip')
df_2022['Hospital overall rating footnote'] = df_2022['Hospital overall rating footnote'].astype(str)
df_2022['Facility ID'] = df_2022['Facility ID'].astype(str)
df_2022 = df_2022[df_2022['Facility ID'].isin(prvdrs_2022)]
df_2022 = df_2022.filter(items=ls, axis=1)
df_2022['file_month'] = '07'
df_2022['file_year'] = '2021'
df_2022 = df_2022.merge(tdf, how='outer')
print('Release years:', df_2022['Release year'].unique())


## 2021
tdf = main_df[main_df['Release year'] == '2021']
prvdrs = tdf['Facility ID'].unique()
df_2021 = pd.read_csv(n_dir + '/hospitals_10_2020/Hospital_General_Information.csv')#, compression='gzip')
df_2021['Hospital overall rating footnote'] = df_2021['Hospital overall rating footnote'].astype(str)
df_2021['Facility ID'] = df_2021['Facility ID'].astype(str)
df_2021 = df_2021[df_2021['Facility ID'].isin(prvdrs_2021)]
df_2021 = df_2021.filter(items=ls, axis=1)
df_2021['file_month'] = '10'
df_2021['file_year'] = '2020'
df_2021 = df_2021.merge(tdf, how='outer')
print('Release years:', df_2021['Release year'].unique())

Release years: ['2027']
Release years: ['2026']
Release years: ['2025']
Release years: ['2024']
Release years: ['2023']
Release years: ['2022']
Release years: ['2021']

In [31]:
print(df_2027.shape)
print(df_2026.shape)
print(df_2025.shape)
print(df_2024.shape)
print(df_2023.shape)
print(df_2022.shape)
print(df_2021.shape)

(3206, 328)
(3203, 328)
(2891, 329)
(2847, 329)
(3076, 329)
(3121, 329)
(3355, 329)

In [32]:
mdf = df_2027.merge(df_2026, how='outer')
mdf = mdf.merge(df_2025, how='outer')
mdf = mdf.merge(df_2024, how='outer')
mdf = mdf.merge(df_2023, how='outer')
mdf = mdf.merge(df_2022, how='outer')
mdf = mdf.merge(df_2021, how='outer')

mdf = mdf[~mdf['Release year'].isin([np.nan, float('NaN')])]
print(mdf.shape)
print('Release years:', sorted(mdf['Release year'].unique()))
mdf.head()

(21699, 329)
Release years: ['2021', '2022', '2023', '2024', '2025', '2026', '2027']

,Facility ID,Facility Name,Address,City,State,ZIP Code,County Name,Hospital Type,Hospital Ownership,Emergency Services,Hospital overall rating,Hospital overall rating footnote,file_month,file_year,Std_Outcomes_Mortality_score,Outcomes_Mortality_cnt,Std_Outcomes_Safety_score,Outcomes_Safety_cnt,Std_Outcomes_Readmission_score,Outcomes_Readmission_cnt,Std_PatientExp_score,Patient_Experience_cnt,Std_Process_score,Process_cnt,std_weight_Mortality,std_weight_Safety,std_weight_Readmission,std_weight_PatientExperience,std_weight_Process,weight_Outcomes_Mortality,weight_Outcomes_Safety,weight_Outcomes_Readmission,weight_PatientExperience,weight_Process,summary_score,Total_measure_group_cnt,MortSafe_Group_cnt,report_indicator,cnt_grp,star,Release year,std_weight_safety,Outcomes_safety_cnt,std_MORT_30_AMI,std_MORT_30_CABG,std_MORT_30_COPD,std_MORT_30_HF,std_MORT_30_PN,std_MORT_30_STK,std_PSI_4_SURG_COMP,std_Hybrid_HWM,mortality_total_cnt,mortality_measure_wt,mortality_score_before_std,mortality_grp_score,mortality_mean,mortality_sd,std_EDAC_30_AMI,std_EDAC_30_HF,std_EDAC_30_PN,std_OP_32,std_OP_35_ADM,std_OP_35_ED,std_OP_36,std_READM_30_CABG,std_READM_30_COPD,std_READM_30_HIP_KNEE,std_Hybrid_HWR,readmission_total_cnt,readmission_measure_wt,readmission_score_before_std,readmission_grp_score,readmission_mean,readmission_sd,std_COMP_HIP_KNEE,std_PSI_90_SAFETY,std_HAI_1,std_HAI_2,std_HAI_3,std_HAI_4,std_HAI_5,std_HAI_6,safety_total_cnt,safety_measure_wt,safety_score_before_std,safety_grp_score,safety_mean,safety_sd,std_IMM_3,std_OP_18B,std_OP_22,std_OP_23,std_OP_29,std_SEP_1,std_SAFE_USE_OF_OPIOIDS,std_OP_13,std_OP_8,std_OP_10,process_total_cnt,process_measure_wt,process_score_before_std,process_grp_score,process_mean,process_sd,std_H_COMP_1_LINEAR_SCORE,std_H_COMP_2_LINEAR_SCORE,std_H_COMP_5_LINEAR_SCORE,std_H_COMP_6_LINEAR_SCORE,std_H_CLEAN_LINEAR_SCORE,std_H_QUIET_LINEAR_SCORE,std_H_HSP_RATING_LINEAR_SCORE,std_H_RECMND_LINEAR_SCORE,std_O-COMP-1,std_O-COMP-2,std_O-COMP-3,std_O-PATIENT-RATE,std_O-PATIENT-REC,patient_exp_total_cnt,patient_exp_measure_wt,patient_exp_score_before_std,patient_exp_grp_score,patient_exp_mean,patient_exp_sd,mortality_Mean,mortality_StdDev,readmission_Mean,readmission_StdDev,safety_Mean,safety_StdDev,process_Mean,process_StdDev,std_H_COMP_3_LINEAR_SCORE,std_H_COMP_7_LINEAR_SCORE,patient_exp_Mean,patient_exp_StdDev,std_READM_30_HOSP_WIDE,std_HCP_COVID_19,std_PC_01,std_H_COMP_1_STAR_RATING,std_H_COMP_2_STAR_RATING,std_H_COMP_3_STAR_RATING,std_H_COMP_5_STAR_RATING,std_H_COMP_6_STAR_RATING,std_H_COMP_7_STAR_RATING,std_H_GLOB_STAR_RATING,std_H_INDI_STAR_RATING,std_OP_3B,std_OP_33,std_OP_30,std_ED_2B,IMM_3,IMM_3_DEN,OP_18B,OP_18B_DEN,OP_22,OP_22_DEN,OP_23,OP_23_DEN,OP_29,OP_29_DEN,SEP_1,SEP_1_DEN,SAFE_USE_OF_OPIOIDS,SAFE_USE_OF_OPIOIDS_DEN,MORT_30_AMI,MORT_30_AMI_DEN,MORT_30_CABG,MORT_30_CABG_DEN,MORT_30_COPD,MORT_30_COPD_DEN,MORT_30_HF,MORT_30_HF_DEN,MORT_30_PN,MORT_30_PN_DEN,MORT_30_STK,MORT_30_STK_DEN,PSI_4_SURG_COMP,PSI_4_SURG_COMP_DEN,COMP_HIP_KNEE,COMP_HIP_KNEE_DEN,PSI_90_SAFETY,PSI_90_SAFETY_DEN,Hybrid_HWM,Hybrid_HWM_DEN,H_COMP_1_A_P,H_COMP_1_SN_P,H_COMP_1_U_P,H_COMP_1_LINEAR_SCORE,H_COMP_1_STAR_RATING,H_NURSE_RESPECT_A_P,H_NURSE_RESPECT_SN_P,H_NURSE_RESPECT_U_P,H_NURSE_LISTEN_A_P,H_NURSE_LISTEN_SN_P,H_NURSE_LISTEN_U_P,H_NURSE_EXPLAIN_A_P,H_NURSE_EXPLAIN_SN_P,H_NURSE_EXPLAIN_U_P,H_COMP_2_A_P,H_COMP_2_SN_P,H_COMP_2_U_P,H_COMP_2_LINEAR_SCORE,H_COMP_2_STAR_RATING,H_DOCTOR_RESPECT_A_P,H_DOCTOR_RESPECT_SN_P,H_DOCTOR_RESPECT_U_P,H_DOCTOR_LISTEN_A_P,H_DOCTOR_LISTEN_SN_P,H_DOCTOR_LISTEN_U_P,H_DOCTOR_EXPLAIN_A_P,H_DOCTOR_EXPLAIN_SN_P,H_DOCTOR_EXPLAIN_U_P,H_COMP_5_A_P,H_COMP_5_SN_P,H_COMP_5_U_P,H_COMP_5_LINEAR_SCORE,H_COMP_5_STAR_RATING,H_MED_FOR_A_P,H_MED_FOR_SN_P,H_MED_FOR_U_P,H_SIDE_EFFECTS_A_P,H_SIDE_EFFECTS_SN_P,H_SIDE_EFFECTS_U_P,H_COMP_6_N_P,H_COMP_6_Y_P,H_COMP_6_LINEAR_SCORE,H_COMP_6_STAR_RATING,H_DISCH_HELP_N_P,H_DISCH_HELP_Y_P,H_SYMPTOMS_N_P,H_SYMPTOMS_Y_P,H_CLEAN_HSP_A_P,H_CLEAN_HSP_SN_P,H_CLEAN_HSP_U_P,H_CLEAN_LINEAR_SCORE,H_CLEAN_STAR_RATING,H_QUIET_HSP_A_P,H_QUIET_HSP_SN_P,H_QUIET_HSP_U_P,H_QUIET_LINEAR_SCORE,H_QUIET_STAR_RATING,H_HSP_RATING_0_6,H_HSP_RATING_7_8,H_HSP_RATING_9_10,H_HSP_RATING_LINEAR_SCORE,H_HSP_RATING_STAR_RATING,H_RECMND_DN,H_RECMND_DY,H_RECMND_PY,H_RECMND_LINEAR_SCORE,H_RECMND_STAR_RATING,H_STAR_RATING,O-COMP-1,O-COMP-2,O-COMP-3,O-PATIENT-RATE,O-PATIENT-REC,EDAC_30_AMI,EDAC_30_AMI_DEN,EDAC_30_HF,EDAC_30_HF_DEN,EDAC_30_PN,EDAC_30_PN_DEN,OP_32,OP_32_DEN,OP_35_ADM,OP_35_ADM_DEN,OP_35_ED,OP_35_ED_DEN,OP_36,OP_36_DEN,READM_30_CABG,READM_30_CABG_DEN,READM_30_COPD,READM_30_COPD_DEN,READM_30_HIP_KNEE,READM_30_HIP_KNEE_DEN,Hybrid_HWR,Hybrid_HWR_DEN,HAI_1_DEN_PRED,HAI_1_DEN_VOL,HAI_1,HAI_2_DEN_PRED,HAI_2_DEN_VOL,HAI_2,HAI_3_DEN_PRED,HAI_3_DEN_VOL,HAI_3,HAI_4_DEN_PRED,HAI_4_DEN_VOL,HAI_4,HAI_5_DEN_PRED,HAI_5_DEN_VOL,HAI_5,HAI_6_DEN_PRED,HAI_6_DEN_VOL,HAI_6,OP_13,OP_8,OP_10,H_COMP_3_LINEAR_SCORE,H_COMP_7_LINEAR_SCORE,H_NUMB_COMP,H_RESP_RATE_P,OP_10_DEN,OP_13_DEN,OP-37_NUMB_COMP,OP_8_DEN,READM_30_HOSP_WIDE_DEN,PC_01,PC_01_DEN,H_COMP_7_STAR_RATING,HCP_COVID_19,READM_30_HOSP_WIDE,HCP_COVID_19_DEN,H_COMP_3_STAR_RATING,H_INDI_STAR_RATING,H_GLOB_STAR_RATING,OP_2,OP_2_DEN,OP_3B,OP_3B_DEN,OP_33,OP_33_DEN,OP_30,OP_30_DEN,ED_2B,ED_2B_DEN,Meets criteria for promoting interoperability of EHRs
0,010001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301.0,HOUSTON,Acute Care Hospitals,Government - Hospital District or Authority,Yes,2,nan,10,2020,-0.752932,7,0.556127,NaN,-0.070355,11,0.071425,8,-0.050316,11,0.22,NaN,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.049100,5,2,1,3.0,3.0,2021,0.22,8.0,0.730853,-2.055159,0.069106,0.103403,-0.022557,-1.941449,-0.327016,NaN,7.0,0.142857,-0.491831,-0.752932,NaN,NaN,-0.027028,-0.705673,1.039984,2.185101,1.182600,-1.185780,1.207127,-1.542989,-1.037529,-1.164917,NaN,11.0,0.090909,-0.010885,-0.070355,NaN,NaN,0.303431,0.319230,-0.078888,0.680925,0.244905,1.037183,0.403644,0.098335,8.0,0.125000,0.376096,0.556127,NaN,NaN,0.644574,-0.761776,-0.979501,NaN,-0.459111,0.031191,NaN,0.684379,0.140655,-0.102729,11.0,0.090909,0.007553,-0.050316,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,0.125000,0.060398,0.071425,NaN,NaN,-0.004941,0.646660,0.027901,0.551294,0.009921,0.658437,0.037755,0.600242,NaN,NaN,-1.104271e-16,0.845613,-0.070634,NaN,0.473469,-0.537213,-0.085263,-0.269656,-0.073296,0.801144,-0.115323,0.284361,0.478432,NaN,NaN,0.466001,-0.054072,0.97,4817.0,178.0,349.0,0.03,57844.0,NaN,NaN,0.81,64.0,0.60,102.0,NaN,NaN,0.119,586.0,0.047,281.0,0.084,374.0,0.113,858.0,0.157,554.0,0.166,644.0,170.87,165.0,0.023,250.0,0.93,3896.300852,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,620.0,21.6,1106.0,-20.6,594.0,13.4,606.0,10.8,190.0,7.1,190.0,0.8,993.0,0.149,268.0,0.207,443.0,0.046,258.0,NaN,NaN,8.086,7846.0,0.742,18.498,13268.0,0.324,4.615,165.0,0.650,1.884,216.0,0.0,7.305,102765.0,0.548,76.294,102765.0,0.537,0.028,0.389,0.072,NaN,NaN,507.0,21.0,2117.0,211.0,NaN,211.0,4474.0,0.00,24.0,3.0,NaN,0.156,NaN,3.0,3.5,3.5,NaN,NaN,NaN,NaN,NaN,NaN,0.98,162.0,103.0,655.0,Y
1,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301.0,HOUSTON,Acute Care Hospitals,Government - Hospital District or Authority,Yes,3,nan,01,2023,-0.647058,7,0.312074,NaN,0.284081,11,-0.127836,8,-1.024044,10,0.22,NaN,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.162208,5,2,1,3.0,3.0,2023,0.22,8.0,-0.041613,-2.197810,-0.019543,1.708727,0.366398,-1.543654,-1.741473,NaN,7.0,0.142857,-0.495567,-0.647058,NaN,NaN,0.207832,-0.702681,0.286040,0.105508,0.159253,0.872692,0.062022,0.219318,-0.048609,-0.198058,NaN,11.0,0.090909,0.171616,0.284081,NaN,NaN,0.024204,-0.212425,0.444297,0.745807,-0.407579,1.025843,0.314693,-0.315731,8.0,0.125000,0.202389,0.312074,NaN,NaN,0.992908,-0.904124,-0.237088,NaN,-0.634479,-0.609958,NaN,-1.779470,0.488322,0.101850,10.0,0.100000,-0.538475,-1.024044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,0.125000,-0.109237,-0.127836,NaN,NaN,-0.051260,0.686658,0.020822,0.530811,-0.013939,0.693192,0.030917,0.556023,NaN,NaN,2.611408e-16,0.854510,0.924456,-1.039363,-1.763346,-1.075850,-0.175531,-1.051153,0.808598,0.688370,0.037272,-0.445032,0.339427,NaN,NaN,NaN,NaN,0.97,3795.0,205.0,323.0,0.03,51079.0,NaN,NaN,0.81,16.0,0.46,146.0,NaN,NaN,0.124,317.0,0.047,172.0,0.085,182.0,0.083,630.0,0.159,407.0,0.164,489.0,173.39,120.0,0.024,102.0,1.01,2046.895485,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.9,319.0,21.8,755.0,-1.5,436.0,14.1,254.0,10.2,214.0,4.7,214.0,1.0,688.0,0.117,165.0,0.199,202.0,0.042,98.0,NaN,NaN,10.597,10024.0,0.661,26.630,17731.0,0.300,4.548,154.0,1.099,1.845,200.0,0.0,9.412,101908.0,0.850,72.686,101451.0,0.660,0.067,0.425,0.057,NaN,NaN,434.0,15.0,1488.0,208.0,NaN,146.0,3058.0,0.09,34.0,3.0,0.737,0.142,2323.0,2.0,3.5,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y
2,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301.0,HOUSTON,Acute Care Hospitals,Government - Hospital District or Authority,Yes,3,nan,01,2024,0.007071,7,-0.146867,NaN,0.230867,11,0.137779,8,-0.677624,10,0.22,NaN,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.030968,5,2,1,3.0,3.0,2024,0.22,7.0,0.470514,-1.535074,0.282996,1.510467,0.129818,-0.554262,-0.748332,NaN,7.0,0.142857,-0.063411,0.007071,NaN,NaN,1.123231,-0.791585,-0.633920,0.292070,-1.032330,0.626949,-0.252865,0.584835,0.293805,0.886353,NaN,11.0,0.090909,0.138216,0.230867,NaN,NaN,0.879845,-1.162386,-0.232451,0.488068,-0.711660,NaN,-0.210159,0.003034,7.0,0.142857,-0.135101,-0.146867,NaN,NaN,0.940083,-0.942734,-1.140182,NaN,-3.129707,0.371166,NaN,0.419351,0.000412,-0.029295,10.0,0.100000,-0.335877,-0.677624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,0.125000,0.119895,0.137779,NaN,NaN,-0.068391,0.704371,0.014038,0.537879,-0.021526,0.773315,0.029039,0.538522,NaN,NaN,1.093644e-15,0.870204,0.423838,-0.431525,0.583665,-0.373358,-0.400063,-0.243371,0.124487,0.479704,0.876397,0.133873,0.361496,NaN,NaN,NaN,NaN,0.95,3905.0,214.0,348.0,0.05,52960.0,NaN,NaN,0.47,17.0,0.65,127.0,NaN,NaN,0.120,278.0,0.041,132.0,0.088,107.0,0.089,549.0,0.180,400.0,0.148,398.0,184.68,134.0,0.027,49.0,1.21,2542.038500,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15.4,274.0,23.4,614.0,23.6,403.0,12.9,170.0,11.9,202.0,4.9,202.0,1.1,668.0,0.105,126.0,0.190,117.0,0.038,49.0,NaN,NaN,9.597,9149.0,0.938,24.766,17310.0,0.363,5.994,214.0,1.335,NaN,NaN,NaN,11.400,104733.0,0.965,67.066,104733.0,0.507,0.028,0.380,0.061,NaN,NaN,544.0,15.0,1410.0,178.0,NaN,79.0,2912.0,0.00,32.0,4.0,0.836,0.142,2496.0,3.0,3.5,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y
3,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301.0,HOUSTON,Acute Care Hospitals,Government - Hospital District or Authority,Yes,3,nan,10,2024,0.296110,7,0.344883,NaN,0.361406,11,0.042072,8,-0.484678,11,0.22,NaN,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,0.171622,5,2,1,3.0,4.0,2025,0.22,7.0,1.405923,-1.045370,1.011496,0.650904,-0.315375,0.023766,-0.732077,NaN,7.0,0.142857,0.142753,0.296110,NaN,NaN,1.024273,-0.368843,-0.448127,0.289973,-1.028886,0.627910,-0.257980,0.607499,0.859382,0.192452,NaN,11.0,0.090909,0.206001,0.361406,NaN,NaN,0.698729,0.103001,0.303670,0.739078,-0.467783,NaN,0.476446,-0.105703,7.0,0.142857,0.249634,0.344883,NaN,NaN,1.044716,-1.062058,-1.138829,NaN,-3.171398,0.449772,0.563049,0.781373,0.588011,0.080291,11.0,0.090909,-0.204464,-0.484678,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,0.125000,0.036435,0.042072,NaN,NaN,-0.073484,0.730255,0.013108,0.533730,-0.019030,0.779001,0.028411,0.480473,NaN,NaN,4.899789e-17,0.866021,0.768359,-0.525017,0.140984,-1.154064,0.570761,-0.231671,-0.254181,-0.312251,0.933177,0.719371,0.020336,NaN,NaN,NaN,NaN,0.96,4115.0,217.0,345.0,0.05,52960.0,NaN,NaN,0.47,17.0,0.68,131.0,0.12,4303.0,0.108,291.0,0.038,157.0,0.079,122.0,0.105,610.0,0.189,489.0,0.137,414.0,194.78,125.0,0.030,32.0,0.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13.8,296.0,10.6,679.0,14.3,490.0,12.9,170.0,11.9,202.0,4.9,202.0,1.1,668.0,0.102,151.0,0.177,130.0,0.044,34.0,NaN,NaN,10.082,9538.0,0.496,23.712,16332.0,0.169,6.618,240.0,1.209,NaN,NaN,NaN,11.232,103195.0,0.445,65.234,103195.0,0.491,0.021,0.333,0.054,NaN,NaN,643.0,17.0,1478.0,193.0,NaN,66.0,2924.0,0.02,46.0,4.0,0.000,0.141,2712.0,3.0,3.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y
4,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301.0,HOUSTON,Acute Care Hospitals,Government - Hospital District or Authority,Yes,4,nan,05,2026,-0.254703,8,0.548349,7.0,0.328216,11,-0.038263,13,-0.562494,9,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,0.060893,5,2,1,3.0,3.0,2027,NaN,NaN,0.635591,-0.406721,-0.340213,0.630641,-0.741557,-0.154133,-1.254456,-0.504468,8.0,0.125000,-0.266915,-0.254703,-0.079043,0.737611,0.930229,0.192983,-0.370577,0.362101,0.617873,0.415289,-0.735719,0.523982,0.266961,0.079285,-0.169533,11.0,0.090909,0.192079,0.328216,0.004851,0.570443,0.570783,0.243115,0.458071,0.598589,0.773824,NaN,0.452642,-0.197022,7.0,0.142857,0.414286,0.548349,-0.015739,0.784216,0.943032,-1.167354,-0.767933,NaN,-2.527459,0.134799,0.182040,-0.216761,0.793318,0.126387,9.0,0.111111,-0.277770,-0.562494,0.023422,0.535459,-0.473033,0.497202,0.271748,0.084833,-0.355198,0.998063,0.307109,0.849646,-0.16206,-1.997243,-0.520059,-0.022825,0.440796,13.0,0.076923,-0.006232,-0.038263,0.026098,0.844962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.93,4625.0,217.0,395.0,0.03,62163.0,NaN,NaN,0.62,39.0,0.65,141.0,0.14,4583.0,0.114,270.0,0.030,144.0,0.094,112.0,0.102,583.0,0.184,517.0,0.135,395.0,203.00,118.0,0.032,27.0,0.95,NaN,0.045,1835.0,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.0,NaN,NaN,NaN,NaN,87.0,NaN,NaN,NaN,NaN,89.0,NaN,NaN,NaN,NaN,91.0,NaN,NaN,98.0,92.0,97.0,94.0,94.0,-15.6,273.0,-1.1,652.0,17.4,507.0,12.7,234.0,10.0,302.0,5.1,302.0,1.1,651.0,0.101,137.0,0.180,122.0,0.048,25.0,0.151,2824.0,10.399,9871.0,0.288,25.693,18164.0,0.195,6.830,238.0,0.293,0.871,91.0,NaN,9.613,114863.0,0.416,71.953,113805.0,0.459,0.038,0.308,0.053,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
df = pd.read_pickle('~/GitHub/HCRIS-databuilder/GenDat4App_p4.pkl')

df2 = df.set_index(('Curated Name and Num', 'Curated Name and Num', 'Curated Name and Num', 'Curated Name and Num'))
df2.columns = df2.columns.droplevel([0,1,2])
df2 = df2.reset_index()

df2.head()

,"(Curated Name and Num, Curated Name and Num, Curated Name and Num, Curated Name and Num)",Hospital Provider Number (PRVDR_NUM),Beginning FFY,Report_Period_Begin_Yr,Lat,Lon,Type of Control of Hospital (See Table I) (S2_1_C1_21),Hospital type (modified),Beds Total Facility (S3_1_C2_27),Hospital State (S2_1_C2_2),Urban (1) or Rural (2) (S2_1_C1_27),Is this a teaching hospital or\naffiliated with a teaching hospital? (Y/N) (S2_1_C1_56)
0,SOUTHEAST ALABAMA MEDICAL CENTER (010001),010001,2011,2010,31.214058,-85.361725,Governmental-County,General Short Term (Acute Care Hospitals),420.0,AL,1.0,N
1,SOUTHEAST ALABAMA MEDICAL CENTER (010001),010001,2012,2011,31.214058,-85.361725,Governmental-County,General Short Term (Acute Care Hospitals),420.0,AL,1.0,N
2,SOUTHEAST ALABAMA MEDICAL CENTER (010001),010001,2013,2012,31.214058,-85.361725,Governmental-County,General Short Term (Acute Care Hospitals),420.0,AL,1.0,N
3,SOUTHEAST ALABAMA MEDICAL CENTER (010001),010001,2014,2013,31.214058,-85.361725,Governmental-County,General Short Term (Acute Care Hospitals),410.0,AL,1.0,N
4,SOUTHEAST ALABAMA MEDICAL CENTER (010001),010001,2015,2014,31.214058,-85.361725,Governmental-County,General Short Term (Acute Care Hospitals),400.0,AL,2.0,N

In [34]:
df2.rename(columns={'Hospital Provider Number (PRVDR_NUM)': 'Facility ID',
                    'Beds Total Facility (S3_1_C2_27)': 'Beds',
                    #'Urban (1) or Rural (2) (S2_1_C1_27)': 'Urban (1) or Rural (2)',
                    #'Is this a teaching hospital or\naffiliated with a teaching hospital? (Y/N) (S2_1_C1_56)': 'Teaching hospital or affiliated with a teaching hospital?',
                   }, inplace=True)
df2 = df2.filter(items=['Facility ID', 'Beds', 'Lat', 'Lon', #'Urban (1) or Rural (2)',
                        #'Teaching hospital or affiliated with a teaching hospital?',
                       ], axis=1)

df2['Beds'] = df2.groupby(['Facility ID'])['Beds'].transform('mean')
df2['Beds'] = np.round(df2['Beds'], 0)

prvdrs = main_df['Facility ID'].unique()
df2 = df2[df2['Facility ID'].isin(prvdrs)]

print(len(prvdrs))
print(len(df2['Facility ID'].unique()))

df2.drop_duplicates(inplace=True)
print(df2.shape)
df2.head()

3651
3526
(3526, 4)

   Facility ID        Beds        Lat         Lon
0       010001  371.642857  31.214058  -85.361725
14      010005  189.142857        NaN         NaN
28      010006  295.666667  34.802756  -87.652191
43      010007   62.714286  31.291972  -86.255415
57      010008        49.0  31.692595  -86.266156

In [35]:
hoarc = sorted(main_df['Facility ID'].unique())
hcris = sorted(df2['Facility ID'].unique())

if hoarc == hcris: 
    print('same')
else:
    ls1 = np.setdiff1d(hoarc, hcris)
    print(len(ls1), 'hospitals in hospitals data archive that are not in hcris:')
    for i in ls1:
        print(i, "and other 'F' hospitals")
        break

    ls2 = np.setdiff1d(hcris, hoarc)
    print(len(ls2), 'hospitals in hcris that are not in hospitals data archive')

125 hospitals in hospitals data archive that are not in hcris:
01014F and other 'F' hospitals
0 hospitals in hcris that are not in hospitals data archive

In [36]:
print('df2.shape:', df2.shape)
print('mdf.shape:', mdf.shape)

main_df = mdf.merge(df2, how='outer', on=['Facility ID'])
main_df = main_df[~main_df['Facility ID'].isin([np.nan, float('NaN')])]

print('main_df.shape:', main_df.shape)
main_df.drop_duplicates(inplace=True)
print('main_df.shape:', main_df.shape)

df2.shape: (3526, 4)
mdf.shape: (21699, 329)
main_df.shape: (21699, 332)
main_df.shape: (21699, 332)

In [37]:
zips1 = main_df['ZIP Code'].tolist()
zips2 = []
for z in zips1:
    try:
        z = int(z)
        z = str(z)
        zips2.append(z)
    except:
        zips2.append(np.nan)
        
main_df['ZIP Code'] = zips2
print(main_df.shape)
main_df.head()

(21699, 332)

,Facility ID,Facility Name,Address,City,State,ZIP Code,County Name,Hospital Type,Hospital Ownership,Emergency Services,Hospital overall rating,Hospital overall rating footnote,file_month,file_year,Std_Outcomes_Mortality_score,Outcomes_Mortality_cnt,Std_Outcomes_Safety_score,Outcomes_Safety_cnt,Std_Outcomes_Readmission_score,Outcomes_Readmission_cnt,Std_PatientExp_score,Patient_Experience_cnt,Std_Process_score,Process_cnt,std_weight_Mortality,std_weight_Safety,std_weight_Readmission,std_weight_PatientExperience,std_weight_Process,weight_Outcomes_Mortality,weight_Outcomes_Safety,weight_Outcomes_Readmission,weight_PatientExperience,weight_Process,summary_score,Total_measure_group_cnt,MortSafe_Group_cnt,report_indicator,cnt_grp,star,Release year,std_weight_safety,Outcomes_safety_cnt,std_MORT_30_AMI,std_MORT_30_CABG,std_MORT_30_COPD,std_MORT_30_HF,std_MORT_30_PN,std_MORT_30_STK,std_PSI_4_SURG_COMP,std_Hybrid_HWM,mortality_total_cnt,mortality_measure_wt,mortality_score_before_std,mortality_grp_score,mortality_mean,mortality_sd,std_EDAC_30_AMI,std_EDAC_30_HF,std_EDAC_30_PN,std_OP_32,std_OP_35_ADM,std_OP_35_ED,std_OP_36,std_READM_30_CABG,std_READM_30_COPD,std_READM_30_HIP_KNEE,std_Hybrid_HWR,readmission_total_cnt,readmission_measure_wt,readmission_score_before_std,readmission_grp_score,readmission_mean,readmission_sd,std_COMP_HIP_KNEE,std_PSI_90_SAFETY,std_HAI_1,std_HAI_2,std_HAI_3,std_HAI_4,std_HAI_5,std_HAI_6,safety_total_cnt,safety_measure_wt,safety_score_before_std,safety_grp_score,safety_mean,safety_sd,std_IMM_3,std_OP_18B,std_OP_22,std_OP_23,std_OP_29,std_SEP_1,std_SAFE_USE_OF_OPIOIDS,std_OP_13,std_OP_8,std_OP_10,process_total_cnt,process_measure_wt,process_score_before_std,process_grp_score,process_mean,process_sd,std_H_COMP_1_LINEAR_SCORE,std_H_COMP_2_LINEAR_SCORE,std_H_COMP_5_LINEAR_SCORE,std_H_COMP_6_LINEAR_SCORE,std_H_CLEAN_LINEAR_SCORE,std_H_QUIET_LINEAR_SCORE,std_H_HSP_RATING_LINEAR_SCORE,std_H_RECMND_LINEAR_SCORE,std_O-COMP-1,std_O-COMP-2,std_O-COMP-3,std_O-PATIENT-RATE,std_O-PATIENT-REC,patient_exp_total_cnt,patient_exp_measure_wt,patient_exp_score_before_std,patient_exp_grp_score,patient_exp_mean,patient_exp_sd,mortality_Mean,mortality_StdDev,readmission_Mean,readmission_StdDev,safety_Mean,safety_StdDev,process_Mean,process_StdDev,std_H_COMP_3_LINEAR_SCORE,std_H_COMP_7_LINEAR_SCORE,patient_exp_Mean,patient_exp_StdDev,std_READM_30_HOSP_WIDE,std_HCP_COVID_19,std_PC_01,std_H_COMP_1_STAR_RATING,std_H_COMP_2_STAR_RATING,std_H_COMP_3_STAR_RATING,std_H_COMP_5_STAR_RATING,std_H_COMP_6_STAR_RATING,std_H_COMP_7_STAR_RATING,std_H_GLOB_STAR_RATING,std_H_INDI_STAR_RATING,std_OP_3B,std_OP_33,std_OP_30,std_ED_2B,IMM_3,IMM_3_DEN,OP_18B,OP_18B_DEN,OP_22,OP_22_DEN,OP_23,OP_23_DEN,OP_29,OP_29_DEN,SEP_1,SEP_1_DEN,SAFE_USE_OF_OPIOIDS,SAFE_USE_OF_OPIOIDS_DEN,MORT_30_AMI,MORT_30_AMI_DEN,MORT_30_CABG,MORT_30_CABG_DEN,MORT_30_COPD,MORT_30_COPD_DEN,MORT_30_HF,MORT_30_HF_DEN,MORT_30_PN,MORT_30_PN_DEN,MORT_30_STK,MORT_30_STK_DEN,PSI_4_SURG_COMP,PSI_4_SURG_COMP_DEN,COMP_HIP_KNEE,COMP_HIP_KNEE_DEN,PSI_90_SAFETY,PSI_90_SAFETY_DEN,Hybrid_HWM,Hybrid_HWM_DEN,H_COMP_1_A_P,H_COMP_1_SN_P,H_COMP_1_U_P,H_COMP_1_LINEAR_SCORE,H_COMP_1_STAR_RATING,H_NURSE_RESPECT_A_P,H_NURSE_RESPECT_SN_P,H_NURSE_RESPECT_U_P,H_NURSE_LISTEN_A_P,H_NURSE_LISTEN_SN_P,H_NURSE_LISTEN_U_P,H_NURSE_EXPLAIN_A_P,H_NURSE_EXPLAIN_SN_P,H_NURSE_EXPLAIN_U_P,H_COMP_2_A_P,H_COMP_2_SN_P,H_COMP_2_U_P,H_COMP_2_LINEAR_SCORE,H_COMP_2_STAR_RATING,H_DOCTOR_RESPECT_A_P,H_DOCTOR_RESPECT_SN_P,H_DOCTOR_RESPECT_U_P,H_DOCTOR_LISTEN_A_P,H_DOCTOR_LISTEN_SN_P,H_DOCTOR_LISTEN_U_P,H_DOCTOR_EXPLAIN_A_P,H_DOCTOR_EXPLAIN_SN_P,H_DOCTOR_EXPLAIN_U_P,H_COMP_5_A_P,H_COMP_5_SN_P,H_COMP_5_U_P,H_COMP_5_LINEAR_SCORE,H_COMP_5_STAR_RATING,H_MED_FOR_A_P,H_MED_FOR_SN_P,H_MED_FOR_U_P,H_SIDE_EFFECTS_A_P,H_SIDE_EFFECTS_SN_P,H_SIDE_EFFECTS_U_P,H_COMP_6_N_P,H_COMP_6_Y_P,H_COMP_6_LINEAR_SCORE,H_COMP_6_STAR_RATING,H_DISCH_HELP_N_P,H_DISCH_HELP_Y_P,H_SYMPTOMS_N_P,H_SYMPTOMS_Y_P,H_CLEAN_HSP_A_P,H_CLEAN_HSP_SN_P,H_CLEAN_HSP_U_P,H_CLEAN_LINEAR_SCORE,H_CLEAN_STAR_RATING,H_QUIET_HSP_A_P,H_QUIET_HSP_SN_P,H_QUIET_HSP_U_P,H_QUIET_LINEAR_SCORE,H_QUIET_STAR_RATING,H_HSP_RATING_0_6,H_HSP_RATING_7_8,H_HSP_RATING_9_10,H_HSP_RATING_LINEAR_SCORE,H_HSP_RATING_STAR_RATING,H_RECMND_DN,H_RECMND_DY,H_RECMND_PY,H_RECMND_LINEAR_SCORE,H_RECMND_STAR_RATING,H_STAR_RATING,O-COMP-1,O-COMP-2,O-COMP-3,O-PATIENT-RATE,O-PATIENT-REC,EDAC_30_AMI,EDAC_30_AMI_DEN,EDAC_30_HF,EDAC_30_HF_DEN,EDAC_30_PN,EDAC_30_PN_DEN,OP_32,OP_32_DEN,OP_35_ADM,OP_35_ADM_DEN,OP_35_ED,OP_35_ED_DEN,OP_36,OP_36_DEN,READM_30_CABG,READM_30_CABG_DEN,READM_30_COPD,READM_30_COPD_DEN,READM_30_HIP_KNEE,READM_30_HIP_KNEE_DEN,Hybrid_HWR,Hybrid_HWR_DEN,HAI_1_DEN_PRED,HAI_1_DEN_VOL,HAI_1,HAI_2_DEN_PRED,HAI_2_DEN_VOL,HAI_2,HAI_3_DEN_PRED,HAI_3_DEN_VOL,HAI_3,HAI_4_DEN_PRED,HAI_4_DEN_VOL,HAI_4,HAI_5_DEN_PRED,HAI_5_DEN_VOL,HAI_5,HAI_6_DEN_PRED,HAI_6_DEN_VOL,HAI_6,OP_13,OP_8,OP_10,H_COMP_3_LINEAR_SCORE,H_COMP_7_LINEAR_SCORE,H_NUMB_COMP,H_RESP_RATE_P,OP_10_DEN,OP_13_DEN,OP-37_NUMB_COMP,OP_8_DEN,READM_30_HOSP_WIDE_DEN,PC_01,PC_01_DEN,H_COMP_7_STAR_RATING,HCP_COVID_19,READM_30_HOSP_WIDE,HCP_COVID_19_DEN,H_COMP_3_STAR_RATING,H_INDI_STAR_RATING,H_GLOB_STAR_RATING,OP_2,OP_2_DEN,OP_3B,OP_3B_DEN,OP_33,OP_33_DEN,OP_30,OP_30_DEN,ED_2B,ED_2B_DEN,Meets criteria for promoting interoperability of EHRs,Beds,Lat,Lon
0,010001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,Acute Care Hospitals,Government - Hospital District or Authority,Yes,2,nan,10,2020,-0.752932,7,0.556127,NaN,-0.070355,11,0.071425,8,-0.050316,11,0.22,NaN,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.049100,5,2,1,3.0,3.0,2021,0.22,8.0,0.730853,-2.055159,0.069106,0.103403,-0.022557,-1.941449,-0.327016,NaN,7.0,0.142857,-0.491831,-0.752932,NaN,NaN,-0.027028,-0.705673,1.039984,2.185101,1.182600,-1.185780,1.207127,-1.542989,-1.037529,-1.164917,NaN,11.0,0.090909,-0.010885,-0.070355,NaN,NaN,0.303431,0.319230,-0.078888,0.680925,0.244905,1.037183,0.403644,0.098335,8.0,0.125000,0.376096,0.556127,NaN,NaN,0.644574,-0.761776,-0.979501,NaN,-0.459111,0.031191,NaN,0.684379,0.140655,-0.102729,11.0,0.090909,0.007553,-0.050316,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,0.125000,0.060398,0.071425,NaN,NaN,-0.004941,0.646660,0.027901,0.551294,0.009921,0.658437,0.037755,0.600242,NaN,NaN,-1.104271e-16,0.845613,-0.070634,NaN,0.473469,-0.537213,-0.085263,-0.269656,-0.073296,0.801144,-0.115323,0.284361,0.478432,NaN,NaN,0.466001,-0.054072,0.97,4817.0,178.0,349.0,0.03,57844.0,NaN,NaN,0.81,64.0,0.60,102.0,NaN,NaN,0.119,586.0,0.047,281.0,0.084,374.0,0.113,858.0,0.157,554.0,0.166,644.0,170.87,165.0,0.023,250.0,0.93,3896.300852,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,620.0,21.6,1106.0,-20.6,594.0,13.4,606.0,10.8,190.0,7.1,190.0,0.8,993.0,0.149,268.0,0.207,443.0,0.046,258.0,NaN,NaN,8.086,7846.0,0.742,18.498,13268.0,0.324,4.615,165.0,0.650,1.884,216.0,0.0,7.305,102765.0,0.548,76.294,102765.0,0.537,0.028,0.389,0.072,NaN,NaN,507.0,21.0,2117.0,211.0,NaN,211.0,4474.0,0.00,24.0,3.0,NaN,0.156,NaN,3.0,3.5,3.5,NaN,NaN,NaN,NaN,NaN,NaN,0.98,162.0,103.0,655.0,Y,371.642857,31.214058,-85.361725
1,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,Acute Care Hospitals,Government - Hospital District or Authority,Yes,3,nan,01,2023,-0.647058,7,0.312074,NaN,0.284081,11,-0.127836,8,-1.024044,10,0.22,NaN,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.162208,5,2,1,3.0,3.0,2023,0.22,8.0,-0.041613,-2.197810,-0.019543,1.708727,0.366398,-1.543654,-1.741473,NaN,7.0,0.142857,-0.495567,-0.647058,NaN,NaN,0.207832,-0.702681,0.286040,0.105508,0.159253,0.872692,0.062022,0.219318,-0.048609,-0.198058,NaN,11.0,0.090909,0.171616,0.284081,NaN,NaN,0.024204,-0.212425,0.444297,0.745807,-0.407579,1.025843,0.314693,-0.315731,8.0,0.125000,0.202389,0.312074,NaN,NaN,0.992908,-0.904124,-0.237088,NaN,-0.634479,-0.609958,NaN,-1.779470,0.488322,0.101850,10.0,0.100000,-0.538475,-1.024044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,0.125000,-0.109237,-0.127836,NaN,NaN,-0.051260,0.686658,0.020822,0.530811,-0.013939,0.693192,0.030917,0.556023,NaN,NaN,2.611408e-16,0.854510,0.924456,-1.039363,-1.763346,-1.075850,-0.175531,-1.051153,0.808598,0.688370,0.037272,-0.445032,0.339427,NaN,NaN,NaN,NaN,0.97,3795.0,205.0,323.0,0.03,51079.0,NaN,NaN,0.81,16.0,0.46,146.0,NaN,NaN,0.124,317.0,0.047,172.0,0.085,182.0,0.083,630.0,0.159,407.0,0.164,489.0,173.39,120.0,0.024,102.0,1.01,2046.895485,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.9,319.0,21.8,755.0,-1.5,436.0,14.1,254.0,10.2,214.0,4.7,214.0,1.0,688.0,0.117,165.0,0.199,202.0,0.042,98.0,NaN,NaN,10.597,10024.0,0.661,26.630,17731.0,0.300,4.548,154.0,1.099,1.845,200.0,0.0,9.412,101908.0,0.850,72.686,101451.0,0.660,0.067,0.425,0.057,NaN,NaN,434.0,15.0,1488.0,208.0,NaN,146.0,3058.0,0.09,34.0,3.0,0.737,0.142,2323.0,2.0,3.5,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,371.642857,31.214058,-85.361725
2,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,Acute Care Hospitals,Government - Hospital District or Authority,Yes,3,nan,01,2024,0.007071,7,-0.146867,NaN,0.230867,11,0.137779,8,-0.677624,10,0.22,NaN,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.030968,5,2,1,3.0,3.0,2024,0.22,7.0,0.470514,-1.535074,0.282996,1.510467,0.129818,-0.554262,-0.748332,NaN,7.0,0.142857,-0.063411,0.007071,NaN,NaN,1.123231,-0.791585,-0.633920,0.292070,-1.032330,0.626949,-0.252865,0.584835,0.293805,0.886353,NaN,11.0,0.090909,0.138216,0.230867,NaN,NaN,0.879845,-1.162386,-0.232451,0.488068,-0.711660,NaN,-0.210159,0.003034,7.0,0.142857,-0.135101,-0.146867,NaN,NaN,0.940083,-0.942734,-1.140182,NaN,-3.129707,0.371166,NaN,0.419351,0.000412,-0.029295,10.0,0.100000,-0.335877,-0.677624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,0.125000,0.119895,0.137779,NaN,NaN,-0.068391,0.704371,0.014038,0.537879,-0.021526,0.773315,0.029039,0.538522,NaN,NaN,1.093644e-15,0.870204,0.423838,-0.431525,0.583665,-0.373358,-0.400063,-0.243371,0.124487,0.479704,0.876397,0.133873,0.361496,NaN,NaN,NaN,NaN,0.95,3905.0,214.0,348.0,0.05,52960.0,NaN,NaN,0.47,17.0,0.65,127.0,NaN,NaN,0.120,278.0,0.041,132.0,0.088,107.0,0.089,549.0,0.180,400.0,0.148,398.0,184.68,134.0,0.027,49.0,1.21,2542.038500,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15.4,274.0,23.4,614.0,23.6,403.0,12.9,170.0,11.9,202.0,4.9,202.0,1.1,668.0,0.105,126.0,0.190,117.0,0.038,49.0,NaN,NaN,9.597,9149.0,0.938,24.766,17310.0,0.363,5.994,214.0,1.335,NaN,NaN,NaN,11.400,104733.0,0.965,67.066,104733.0,0.507,0.028,0.380,0.061,NaN,NaN,544.0,15.0,1410.0,178.0,NaN,79.0,2912.0,0.00,32.0,4.0,0.836,0.142,2496.0,3.0,3.5,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,371.642857,31.214058,-85.361725
3,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,Acute Care Hospitals,Government - Hospital District or Authority,Yes,3,nan,10,2024,0.296110,7,0.344883,NaN,0.361406,11,0.042072,8,-0.484678,11,0.22,NaN,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,0.171622,5,2,1,3.0,4.0,2025,0.22,7.0,1.405923,-1.045370,1.011496,0.650904,-0.315375,0.023766,-0.732077,NaN,7.0,0.142857,0.142753,0.296110,NaN,NaN,1.024273,-0.368843,-0.448127,0.289973,-1.028886,0.627910,-0.257980,0.607499,0.859382,0.192452,NaN,11.0,0.090909,0.206001,0.361406,NaN,NaN,0.698729,0.103001,0.303670,0.739078,-0.467783,NaN,0.476446,-0.105703,7.0,0.142857,0.249634,0.344883,NaN,NaN,1.044716,-1.062058,-1.138829,NaN,-3.171398,0.449772,0.563049,0.781373,0.588011,0.080291,11.0,0.090909,-0.204464,-0.484678,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,0.125000,0.036435,0.042072,NaN,NaN,-0.073484,0.730255,0.013108,0.533730,-0.019030,0.779001,0.028411,0.480473,NaN,NaN,4.899789e-17,0.866021,0.768359,-0.525017,0.140984,-1.154064,0.570761,-0.231671,-0.254181,-0.312251,0.933177,0.719371,0.020336,NaN,NaN,NaN,NaN,0.96,4115.0,217.0,345.0,0.05,52960.0,NaN,NaN,0.47,17.0,0.68,131.0,0.12,4303.0,0.108,291.0,0.038,157.0,0.079,122.0,0.105,610.0,0.189,489.0,0.137,414.0,194.78,125.0,0.030,32.0,0.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13.8,296.0,10.6,679.0,14.3,490.0,12.9,170.0,11.9,202.0,4.9,202.0,1.1,668.0,0.102,151.0,0.177,130.0,0.044,34.0,NaN,NaN,10.082,9538.0,0.496,23.712,16332.0,0.169,6.618,240.0,1.209,NaN,NaN,NaN,11.232,103195.0,0.445,65.234,103195.0,0.491,0.021,0.333,0.054,NaN,NaN,643.0,17.0,1478.0,193.0,NaN,66.0,2924.0,0.02,46.0,4.0,0.000,0.141,2712.0,3.0,3.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,371.642857,31.214058,-85.361725
4,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,Acute Care Hospitals,Government - Hospital District or Authority,Yes,4,nan,05,2026,-0.254703,8,0.548349,7.0,0.328216,11,-0.038263,13,-0.562494,9,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,0.060893,5,2,1,3.0,3.0,2027,NaN,NaN,0.635591,-0.406721,-0.340213,0.630641,-0.741557,-0.154133,-1.254456,-0.504468,8.0,0.125000,-0.266915,-0.254703,-0.079043,0.737611,0.930229,0.192983,-0.370577,0.362101,0.617873,0.415289,-0.735719,0.523982,0.266961,0.079285,-0.169533,11.0,0.090909,0.192079,0.328216,0.004851,0.570443,0.570783,0.243115,0.458071,0.598589,0.773824,NaN,0.452642,-0.197022,7.0,0.142857,0.414286,0.548349,-0.015739,0.784216,0.943032,-1.167354,-0.767933,NaN,-2.527459,0.134799,0.182040,-0.216761,0.793318,0.126387,9.0,0.111111,-0.277770,-0.562494,0.023422,0.535459,-0.473033,0.497202,0.271748,0.084833,-0.355198,0.998063,0.307109,0.849646,-0.16206,-1.997243,-0.520059,-0.022825,0.440796,13.0,0.076923,-0.006232,-0.038263,0.026098,0.844962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.93,4625.0,217.0,395.0,0.03,62163.0,NaN,NaN,0.62,39.0,0.65,141.0,0.14,4583.0,0.114,270.0,0.030,144.0,0.094,112.0,0.102,583.0,0.184,517.0,0.135,395.0,203.00,118.0,0.032,27.0,0.95,NaN,0.045,1835.0,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.0,NaN,NaN,NaN,NaN,87.0,NaN,NaN,NaN,NaN,89.0,NaN,NaN,NaN,NaN,91.0,NaN,NaN,98.0,92.0,97.0,94.0,94.0,-15.6,273.0,-1.1,652.0,17.4,507.0,12.7,234.0,10.0,302.0,5.1,302.0,1.1,651.0,0.101,137.0,0.180,122.0,0.048,25.0,0.151,2824.0,10.399,9871.0,0.288,25.693,18164.0,0.195,6.830,238.0,0.293,0.871,91.0,NaN,9.613,114863.0,0.416,71.953,113805.0,0.459,0.038,0.308,0.053,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,371.642857,31.214058,-85.361725

In [38]:
print('main_df.shape:', main_df.shape)
main_df.drop_duplicates(inplace=True)
print('main_df.shape:', main_df.shape)

main_df.shape: (21699, 332)
main_df.shape: (21699, 332)

In [39]:

main_df.replace({'Facility Name': {'COPLEY MEMORIAL HOSPITAL': 'RUSH COPLEY'}}, inplace = True)
main_df['Name and Num'] = main_df['Facility Name'] + ' (' + main_df['Facility ID'] + ')'
main_df = main_df[~main_df['Name and Num'].isin([np.nan, float('NaN')])]
main_df['State'] = main_df['State'].replace(np.nan, 'Not given')
main_df['Hospital Type'] = main_df['Hospital Type'].replace(np.nan, 'Not given')
main_df['Hospital Ownership'] = main_df['Hospital Ownership'].replace(np.nan, 'Not given')

print('main_df.shape:', main_df.shape)
main_df.drop_duplicates(inplace=True)
print('main_df.shape:', main_df.shape)


drop_ls = [
    'Emergency Services',
    'Meets criteria for promoting interoperability of EHRs',
    'Hospital overall rating',
    'Hospital overall rating footnote',
    'mortality_total_cnt',
    'mortality_score_before_std',
    'mortality_Mean',
    'mortality_StdDev',
    'mortality_grp_score',
    'readmission_total_cnt',
    'readmission_score_before_std',
    'readmission_Mean',
    'readmission_StdDev',
    'readmission_grp_score',
    'safety_total_cnt',
    'safety_score_before_std',
    'safety_Mean',
    'safety_StdDev',
    'safety_grp_score',
    'process_total_cnt',
    'process_score_before_std',
    'process_Mean',
    'process_StdDev',
    'process_grp_score',
    'patient_exp_total_cnt',
    'patient_exp_score_before_std',
    'patient_exp_Mean',
    'patient_exp_StdDev',
    'patient_exp_grp_score',
    #'Urban (1) or Rural (2)',
    #'Teaching hospital or affiliated with a teaching hospital?',
]

for lab in list(main_df):
    if '_DEN' in lab:
        drop_ls.append(lab)
        
print(main_df.shape)
main_df.drop(labels=drop_ls, axis=1, inplace=True)
print(main_df.shape)
main_df.head()

main_df.shape: (21585, 333)
main_df.shape: (21585, 333)
(21585, 333)
(21585, 253)

,Facility ID,Facility Name,Address,City,State,ZIP Code,County Name,Hospital Type,Hospital Ownership,file_month,file_year,Std_Outcomes_Mortality_score,Outcomes_Mortality_cnt,Std_Outcomes_Safety_score,Outcomes_Safety_cnt,Std_Outcomes_Readmission_score,Outcomes_Readmission_cnt,Std_PatientExp_score,Patient_Experience_cnt,Std_Process_score,Process_cnt,std_weight_Mortality,std_weight_Safety,std_weight_Readmission,std_weight_PatientExperience,std_weight_Process,weight_Outcomes_Mortality,weight_Outcomes_Safety,weight_Outcomes_Readmission,weight_PatientExperience,weight_Process,summary_score,Total_measure_group_cnt,MortSafe_Group_cnt,report_indicator,cnt_grp,star,Release year,std_weight_safety,Outcomes_safety_cnt,std_MORT_30_AMI,std_MORT_30_CABG,std_MORT_30_COPD,std_MORT_30_HF,std_MORT_30_PN,std_MORT_30_STK,std_PSI_4_SURG_COMP,std_Hybrid_HWM,mortality_measure_wt,mortality_mean,mortality_sd,std_EDAC_30_AMI,std_EDAC_30_HF,std_EDAC_30_PN,std_OP_32,std_OP_35_ADM,std_OP_35_ED,std_OP_36,std_READM_30_CABG,std_READM_30_COPD,std_READM_30_HIP_KNEE,std_Hybrid_HWR,readmission_measure_wt,readmission_mean,readmission_sd,std_COMP_HIP_KNEE,std_PSI_90_SAFETY,std_HAI_1,std_HAI_2,std_HAI_3,std_HAI_4,std_HAI_5,std_HAI_6,safety_measure_wt,safety_mean,safety_sd,std_IMM_3,std_OP_18B,std_OP_22,std_OP_23,std_OP_29,std_SEP_1,std_SAFE_USE_OF_OPIOIDS,std_OP_13,std_OP_8,std_OP_10,process_measure_wt,process_mean,process_sd,std_H_COMP_1_LINEAR_SCORE,std_H_COMP_2_LINEAR_SCORE,std_H_COMP_5_LINEAR_SCORE,std_H_COMP_6_LINEAR_SCORE,std_H_CLEAN_LINEAR_SCORE,std_H_QUIET_LINEAR_SCORE,std_H_HSP_RATING_LINEAR_SCORE,std_H_RECMND_LINEAR_SCORE,std_O-COMP-1,std_O-COMP-2,std_O-COMP-3,std_O-PATIENT-RATE,std_O-PATIENT-REC,patient_exp_measure_wt,patient_exp_mean,patient_exp_sd,std_H_COMP_3_LINEAR_SCORE,std_H_COMP_7_LINEAR_SCORE,std_READM_30_HOSP_WIDE,std_HCP_COVID_19,std_PC_01,std_H_COMP_1_STAR_RATING,std_H_COMP_2_STAR_RATING,std_H_COMP_3_STAR_RATING,std_H_COMP_5_STAR_RATING,std_H_COMP_6_STAR_RATING,std_H_COMP_7_STAR_RATING,std_H_GLOB_STAR_RATING,std_H_INDI_STAR_RATING,std_OP_3B,std_OP_33,std_OP_30,std_ED_2B,IMM_3,OP_18B,OP_22,OP_23,OP_29,SEP_1,SAFE_USE_OF_OPIOIDS,MORT_30_AMI,MORT_30_CABG,MORT_30_COPD,MORT_30_HF,MORT_30_PN,MORT_30_STK,PSI_4_SURG_COMP,COMP_HIP_KNEE,PSI_90_SAFETY,Hybrid_HWM,H_COMP_1_A_P,H_COMP_1_SN_P,H_COMP_1_U_P,H_COMP_1_LINEAR_SCORE,H_COMP_1_STAR_RATING,H_NURSE_RESPECT_A_P,H_NURSE_RESPECT_SN_P,H_NURSE_RESPECT_U_P,H_NURSE_LISTEN_A_P,H_NURSE_LISTEN_SN_P,H_NURSE_LISTEN_U_P,H_NURSE_EXPLAIN_A_P,H_NURSE_EXPLAIN_SN_P,H_NURSE_EXPLAIN_U_P,H_COMP_2_A_P,H_COMP_2_SN_P,H_COMP_2_U_P,H_COMP_2_LINEAR_SCORE,H_COMP_2_STAR_RATING,H_DOCTOR_RESPECT_A_P,H_DOCTOR_RESPECT_SN_P,H_DOCTOR_RESPECT_U_P,H_DOCTOR_LISTEN_A_P,H_DOCTOR_LISTEN_SN_P,H_DOCTOR_LISTEN_U_P,H_DOCTOR_EXPLAIN_A_P,H_DOCTOR_EXPLAIN_SN_P,H_DOCTOR_EXPLAIN_U_P,H_COMP_5_A_P,H_COMP_5_SN_P,H_COMP_5_U_P,H_COMP_5_LINEAR_SCORE,H_COMP_5_STAR_RATING,H_MED_FOR_A_P,H_MED_FOR_SN_P,H_MED_FOR_U_P,H_SIDE_EFFECTS_A_P,H_SIDE_EFFECTS_SN_P,H_SIDE_EFFECTS_U_P,H_COMP_6_N_P,H_COMP_6_Y_P,H_COMP_6_LINEAR_SCORE,H_COMP_6_STAR_RATING,H_DISCH_HELP_N_P,H_DISCH_HELP_Y_P,H_SYMPTOMS_N_P,H_SYMPTOMS_Y_P,H_CLEAN_HSP_A_P,H_CLEAN_HSP_SN_P,H_CLEAN_HSP_U_P,H_CLEAN_LINEAR_SCORE,H_CLEAN_STAR_RATING,H_QUIET_HSP_A_P,H_QUIET_HSP_SN_P,H_QUIET_HSP_U_P,H_QUIET_LINEAR_SCORE,H_QUIET_STAR_RATING,H_HSP_RATING_0_6,H_HSP_RATING_7_8,H_HSP_RATING_9_10,H_HSP_RATING_LINEAR_SCORE,H_HSP_RATING_STAR_RATING,H_RECMND_DN,H_RECMND_DY,H_RECMND_PY,H_RECMND_LINEAR_SCORE,H_RECMND_STAR_RATING,H_STAR_RATING,O-COMP-1,O-COMP-2,O-COMP-3,O-PATIENT-RATE,O-PATIENT-REC,EDAC_30_AMI,EDAC_30_HF,EDAC_30_PN,OP_32,OP_35_ADM,OP_35_ED,OP_36,READM_30_CABG,READM_30_COPD,READM_30_HIP_KNEE,Hybrid_HWR,HAI_1,HAI_2,HAI_3,HAI_4,HAI_5,HAI_6,OP_13,OP_8,OP_10,H_COMP_3_LINEAR_SCORE,H_COMP_7_LINEAR_SCORE,H_NUMB_COMP,H_RESP_RATE_P,OP-37_NUMB_COMP,PC_01,H_COMP_7_STAR_RATING,HCP_COVID_19,READM_30_HOSP_WIDE,H_COMP_3_STAR_RATING,H_INDI_STAR_RATING,H_GLOB_STAR_RATING,OP_2,OP_3B,OP_33,OP_30,ED_2B,Beds,Lat,Lon,Name and Num
0,010001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,Acute Care Hospitals,Government - Hospital District or Authority,10,2020,-0.752932,7,0.556127,NaN,-0.070355,11,0.071425,8,-0.050316,11,0.22,NaN,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.049100,5,2,1,3.0,3.0,2021,0.22,8.0,0.730853,-2.055159,0.069106,0.103403,-0.022557,-1.941449,-0.327016,NaN,0.142857,NaN,NaN,-0.027028,-0.705673,1.039984,2.185101,1.182600,-1.185780,1.207127,-1.542989,-1.037529,-1.164917,NaN,0.090909,NaN,NaN,0.303431,0.319230,-0.078888,0.680925,0.244905,1.037183,0.403644,0.098335,0.125000,NaN,NaN,0.644574,-0.761776,-0.979501,NaN,-0.459111,0.031191,NaN,0.684379,0.140655,-0.102729,0.090909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.125000,NaN,NaN,NaN,NaN,-0.070634,NaN,0.473469,-0.537213,-0.085263,-0.269656,-0.073296,0.801144,-0.115323,0.284361,0.478432,NaN,NaN,0.466001,-0.054072,0.97,178.0,0.03,NaN,0.81,0.60,NaN,0.119,0.047,0.084,0.113,0.157,0.166,170.87,0.023,0.93,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,21.6,-20.6,13.4,10.8,7.1,0.8,0.149,0.207,0.046,NaN,0.742,0.324,0.650,0.0,0.548,0.537,0.028,0.389,0.072,NaN,NaN,507.0,21.0,NaN,0.00,3.0,NaN,0.156,3.0,3.5,3.5,NaN,NaN,NaN,0.98,103.0,371.642857,31.214058,-85.361725,SOUTHEAST ALABAMA MEDICAL CENTER (010001)
1,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,Acute Care Hospitals,Government - Hospital District or Authority,01,2023,-0.647058,7,0.312074,NaN,0.284081,11,-0.127836,8,-1.024044,10,0.22,NaN,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.162208,5,2,1,3.0,3.0,2023,0.22,8.0,-0.041613,-2.197810,-0.019543,1.708727,0.366398,-1.543654,-1.741473,NaN,0.142857,NaN,NaN,0.207832,-0.702681,0.286040,0.105508,0.159253,0.872692,0.062022,0.219318,-0.048609,-0.198058,NaN,0.090909,NaN,NaN,0.024204,-0.212425,0.444297,0.745807,-0.407579,1.025843,0.314693,-0.315731,0.125000,NaN,NaN,0.992908,-0.904124,-0.237088,NaN,-0.634479,-0.609958,NaN,-1.779470,0.488322,0.101850,0.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.125000,NaN,NaN,NaN,NaN,0.924456,-1.039363,-1.763346,-1.075850,-0.175531,-1.051153,0.808598,0.688370,0.037272,-0.445032,0.339427,NaN,NaN,NaN,NaN,0.97,205.0,0.03,NaN,0.81,0.46,NaN,0.124,0.047,0.085,0.083,0.159,0.164,173.39,0.024,1.01,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.9,21.8,-1.5,14.1,10.2,4.7,1.0,0.117,0.199,0.042,NaN,0.661,0.300,1.099,0.0,0.850,0.660,0.067,0.425,0.057,NaN,NaN,434.0,15.0,NaN,0.09,3.0,0.737,0.142,2.0,3.5,3.0,NaN,NaN,NaN,NaN,NaN,371.642857,31.214058,-85.361725,SOUTHEAST HEALTH MEDICAL CENTER (010001)
2,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,Acute Care Hospitals,Government - Hospital District or Authority,01,2024,0.007071,7,-0.146867,NaN,0.230867,11,0.137779,8,-0.677624,10,0.22,NaN,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,-0.030968,5,2,1,3.0,3.0,2024,0.22,7.0,0.470514,-1.535074,0.282996,1.510467,0.129818,-0.554262,-0.748332,NaN,0.142857,NaN,NaN,1.123231,-0.791585,-0.633920,0.292070,-1.032330,0.626949,-0.252865,0.584835,0.293805,0.886353,NaN,0.090909,NaN,NaN,0.879845,-1.162386,-0.232451,0.488068,-0.711660,NaN,-0.210159,0.003034,0.142857,NaN,NaN,0.940083,-0.942734,-1.140182,NaN,-3.129707,0.371166,NaN,0.419351,0.000412,-0.029295,0.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.125000,NaN,NaN,NaN,NaN,0.423838,-0.431525,0.583665,-0.373358,-0.400063,-0.243371,0.124487,0.479704,0.876397,0.133873,0.361496,NaN,NaN,NaN,NaN,0.95,214.0,0.05,NaN,0.47,0.65,NaN,0.120,0.041,0.088,0.089,0.180,0.148,184.68,0.027,1.21,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15.4,23.4,23.6,12.9,11.9,4.9,1.1,0.105,0.190,0.038,NaN,0.938,0.363,1.335,NaN,0.965,0.507,0.028,0.380,0.061,NaN,NaN,544.0,15.0,NaN,0.00,4.0,0.836,0.142,3.0,3.5,3.5,NaN,NaN,NaN,NaN,NaN,371.642857,31.214058,-85.361725,SOUTHEAST HEALTH MEDICAL CENTER (010001)
3,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,Acute Care Hospitals,Government - Hospital District or Authority,10,2024,0.296110,7,0.344883,NaN,0.361406,11,0.042072,8,-0.484678,11,0.22,NaN,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,0.171622,5,2,1,3.0,4.0,2025,0.22,7.0,1.405923,-1.045370,1.011496,0.650904,-0.315375,0.023766,-0.732077,NaN,0.142857,NaN,NaN,1.024273,-0.368843,-0.448127,0.289973,-1.028886,0.627910,-0.257980,0.607499,0.859382,0.192452,NaN,0.090909,NaN,NaN,0.698729,0.103001,0.303670,0.739078,-0.467783,NaN,0.476446,-0.105703,0.142857,NaN,NaN,1.044716,-1.062058,-1.138829,NaN,-3.171398,0.449772,0.563049,0.781373,0.588011,0.080291,0.090909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.125000,NaN,NaN,NaN,NaN,0.768359,-0.525017,0.140984,-1.154064,0.570761,-0.231671,-0.254181,-0.312251,0.933177,0.719371,0.020336,NaN,NaN,NaN,NaN,0.96,217.0,0.05,NaN,0.47,0.68,0.12,0.108,0.038,0.079,0.105,0.189,0.137,194.78,0.030,0.98,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13.8,10.6,14.3,12.9,11.9,4.9,1.1,0.102,0.177,0.044,NaN,0.496,0.169,1.209,NaN,0.445,0.491,0.021,0.333,0.054,NaN,NaN,643.0,17.0,NaN,0.02,4.0,0.000,0.141,3.0,3.0,4.0,NaN,NaN,NaN,NaN,NaN,371.642857,31.214058,-85.361725,SOUTHEAST HEALTH MEDICAL CENTER (010001)
4,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,Acute Care Hospitals,Government - Hospital District or Authority,05,2026,-0.254703,8,0.548349,7.0,0.328216,11,-0.038263,13,-0.562494,9,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,0.060893,5,2,1,3.0,3.0,2027,NaN,NaN,0.635591,-0.406721,-0.340213,0.630641,-0.741557,-0.154133,-1.254456,-0.504468,0.125000,-0.079043,0.737611,0.930229,0.192983,-0.370577,0.362101,0.617873,0.415289,-0.735719,0.523982,0.266961,0.079285,-0.169533,0.090909,0.004851,0.570443,0.570783,0.243115,0.458071,0.598589,0.773824,NaN,0.452642,-0.197022,0.142857,-0.015739,0.784216,0.943032,-1.167354,-0.767933,NaN,-2.527459,0.134799,0.182040,-0.216761,0.793318,0.126387,0.111111,0.023422,0.535459,-0.473033,0.497202,0.271748,0.084833,-0.355198,0.998063,0.307109,0.849646,-0.16206,-1.997243,-0.520059,-0.022825,0.440796,0.076923,0.026098,0.844962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.93,217.0,0.03,NaN,0.62,0.65,0.14,0.114,0.030,0.094,0.102,0.184,0.135,203.00,0.032,0.95,0.045,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.0,NaN,NaN,NaN,NaN,87.0,NaN,NaN,NaN,NaN,89.0,NaN,NaN,NaN,NaN,91.0,NaN,NaN,98.0,92.0,97.0,94.0,94.0,-15.6,-1.1,17.4,12.7,10.0,5.1,1.1,0.101,0.180,0.048,0.151,0.288,0.195,0.293,NaN,0.416,0.459,0.038,0.308,0.053,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,371.642857,31.214058,-85.361725,SOUTHEAST HEALTH MEDICAL CENTER (010001)

In [40]:
tdf = main_df[main_df['Release year'] == '2026']
tdf = tdf[tdf['Facility ID'] == '140063']
print(tdf.shape)
tdf.head()

(1, 253)

,Facility ID,Facility Name,Address,City,State,ZIP Code,County Name,Hospital Type,Hospital Ownership,file_month,file_year,Std_Outcomes_Mortality_score,Outcomes_Mortality_cnt,Std_Outcomes_Safety_score,Outcomes_Safety_cnt,Std_Outcomes_Readmission_score,Outcomes_Readmission_cnt,Std_PatientExp_score,Patient_Experience_cnt,Std_Process_score,Process_cnt,std_weight_Mortality,std_weight_Safety,std_weight_Readmission,std_weight_PatientExperience,std_weight_Process,weight_Outcomes_Mortality,weight_Outcomes_Safety,weight_Outcomes_Readmission,weight_PatientExperience,weight_Process,summary_score,Total_measure_group_cnt,MortSafe_Group_cnt,report_indicator,cnt_grp,star,Release year,std_weight_safety,Outcomes_safety_cnt,std_MORT_30_AMI,std_MORT_30_CABG,std_MORT_30_COPD,std_MORT_30_HF,std_MORT_30_PN,std_MORT_30_STK,std_PSI_4_SURG_COMP,std_Hybrid_HWM,mortality_measure_wt,mortality_mean,mortality_sd,std_EDAC_30_AMI,std_EDAC_30_HF,std_EDAC_30_PN,std_OP_32,std_OP_35_ADM,std_OP_35_ED,std_OP_36,std_READM_30_CABG,std_READM_30_COPD,std_READM_30_HIP_KNEE,std_Hybrid_HWR,readmission_measure_wt,readmission_mean,readmission_sd,std_COMP_HIP_KNEE,std_PSI_90_SAFETY,std_HAI_1,std_HAI_2,std_HAI_3,std_HAI_4,std_HAI_5,std_HAI_6,safety_measure_wt,safety_mean,safety_sd,std_IMM_3,std_OP_18B,std_OP_22,std_OP_23,std_OP_29,std_SEP_1,std_SAFE_USE_OF_OPIOIDS,std_OP_13,std_OP_8,std_OP_10,process_measure_wt,process_mean,process_sd,std_H_COMP_1_LINEAR_SCORE,std_H_COMP_2_LINEAR_SCORE,std_H_COMP_5_LINEAR_SCORE,std_H_COMP_6_LINEAR_SCORE,std_H_CLEAN_LINEAR_SCORE,std_H_QUIET_LINEAR_SCORE,std_H_HSP_RATING_LINEAR_SCORE,std_H_RECMND_LINEAR_SCORE,std_O-COMP-1,std_O-COMP-2,std_O-COMP-3,std_O-PATIENT-RATE,std_O-PATIENT-REC,patient_exp_measure_wt,patient_exp_mean,patient_exp_sd,std_H_COMP_3_LINEAR_SCORE,std_H_COMP_7_LINEAR_SCORE,std_READM_30_HOSP_WIDE,std_HCP_COVID_19,std_PC_01,std_H_COMP_1_STAR_RATING,std_H_COMP_2_STAR_RATING,std_H_COMP_3_STAR_RATING,std_H_COMP_5_STAR_RATING,std_H_COMP_6_STAR_RATING,std_H_COMP_7_STAR_RATING,std_H_GLOB_STAR_RATING,std_H_INDI_STAR_RATING,std_OP_3B,std_OP_33,std_OP_30,std_ED_2B,IMM_3,OP_18B,OP_22,OP_23,OP_29,SEP_1,SAFE_USE_OF_OPIOIDS,MORT_30_AMI,MORT_30_CABG,MORT_30_COPD,MORT_30_HF,MORT_30_PN,MORT_30_STK,PSI_4_SURG_COMP,COMP_HIP_KNEE,PSI_90_SAFETY,Hybrid_HWM,H_COMP_1_A_P,H_COMP_1_SN_P,H_COMP_1_U_P,H_COMP_1_LINEAR_SCORE,H_COMP_1_STAR_RATING,H_NURSE_RESPECT_A_P,H_NURSE_RESPECT_SN_P,H_NURSE_RESPECT_U_P,H_NURSE_LISTEN_A_P,H_NURSE_LISTEN_SN_P,H_NURSE_LISTEN_U_P,H_NURSE_EXPLAIN_A_P,H_NURSE_EXPLAIN_SN_P,H_NURSE_EXPLAIN_U_P,H_COMP_2_A_P,H_COMP_2_SN_P,H_COMP_2_U_P,H_COMP_2_LINEAR_SCORE,H_COMP_2_STAR_RATING,H_DOCTOR_RESPECT_A_P,H_DOCTOR_RESPECT_SN_P,H_DOCTOR_RESPECT_U_P,H_DOCTOR_LISTEN_A_P,H_DOCTOR_LISTEN_SN_P,H_DOCTOR_LISTEN_U_P,H_DOCTOR_EXPLAIN_A_P,H_DOCTOR_EXPLAIN_SN_P,H_DOCTOR_EXPLAIN_U_P,H_COMP_5_A_P,H_COMP_5_SN_P,H_COMP_5_U_P,H_COMP_5_LINEAR_SCORE,H_COMP_5_STAR_RATING,H_MED_FOR_A_P,H_MED_FOR_SN_P,H_MED_FOR_U_P,H_SIDE_EFFECTS_A_P,H_SIDE_EFFECTS_SN_P,H_SIDE_EFFECTS_U_P,H_COMP_6_N_P,H_COMP_6_Y_P,H_COMP_6_LINEAR_SCORE,H_COMP_6_STAR_RATING,H_DISCH_HELP_N_P,H_DISCH_HELP_Y_P,H_SYMPTOMS_N_P,H_SYMPTOMS_Y_P,H_CLEAN_HSP_A_P,H_CLEAN_HSP_SN_P,H_CLEAN_HSP_U_P,H_CLEAN_LINEAR_SCORE,H_CLEAN_STAR_RATING,H_QUIET_HSP_A_P,H_QUIET_HSP_SN_P,H_QUIET_HSP_U_P,H_QUIET_LINEAR_SCORE,H_QUIET_STAR_RATING,H_HSP_RATING_0_6,H_HSP_RATING_7_8,H_HSP_RATING_9_10,H_HSP_RATING_LINEAR_SCORE,H_HSP_RATING_STAR_RATING,H_RECMND_DN,H_RECMND_DY,H_RECMND_PY,H_RECMND_LINEAR_SCORE,H_RECMND_STAR_RATING,H_STAR_RATING,O-COMP-1,O-COMP-2,O-COMP-3,O-PATIENT-RATE,O-PATIENT-REC,EDAC_30_AMI,EDAC_30_HF,EDAC_30_PN,OP_32,OP_35_ADM,OP_35_ED,OP_36,READM_30_CABG,READM_30_COPD,READM_30_HIP_KNEE,Hybrid_HWR,HAI_1,HAI_2,HAI_3,HAI_4,HAI_5,HAI_6,OP_13,OP_8,OP_10,H_COMP_3_LINEAR_SCORE,H_COMP_7_LINEAR_SCORE,H_NUMB_COMP,H_RESP_RATE_P,OP-37_NUMB_COMP,PC_01,H_COMP_7_STAR_RATING,HCP_COVID_19,READM_30_HOSP_WIDE,H_COMP_3_STAR_RATING,H_INDI_STAR_RATING,H_GLOB_STAR_RATING,OP_2,OP_3B,OP_33,OP_30,ED_2B,Beds,Lat,Lon,Name and Num
5840,140063,RUSH OAK PARK HOSPITAL,520 S MAPLE AVE,OAK PARK,IL,60304,COOK,Acute Care Hospitals,Voluntary non-profit - Church,10,2025,1.607526,6,-0.397378,5.0,0.557798,8,-0.569012,15,-0.902249,8,0.22,0.22,0.22,0.22,0.12,0.22,0.22,0.22,0.22,0.12,0.155495,5,2,1,3.0,4.0,2026,NaN,NaN,-0.137152,NaN,1.08204,1.867428,1.938433,0.607862,NaN,1.285927,0.166667,NaN,NaN,NaN,-0.917151,-0.600916,0.842209,0.679505,0.881257,0.662844,NaN,0.851009,NaN,0.115191,0.125,NaN,NaN,NaN,-0.323151,-1.303193,0.94747,NaN,NaN,-1.496084,0.39723,0.2,NaN,NaN,1.098394,-1.472679,-2.308114,0.752411,0.468503,-1.931279,0.004698,NaN,NaN,-0.173592,0.125,NaN,NaN,-0.445368,-0.649489,-0.44518,-1.384659,-1.053893,-0.738322,-0.811105,-0.402008,0.803203,-0.082826,0.533043,-0.468851,-0.19754,0.066667,NaN,NaN,-0.49557,-0.907334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.96,234.0,0.08,0.85,0.98,0.31,0.15,0.123,NaN,0.072,0.075,0.11,0.122,NaN,NaN,1.06,0.035,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82.0,NaN,NaN,NaN,NaN,78.0,NaN,NaN,NaN,NaN,85.0,NaN,NaN,NaN,NaN,85.0,NaN,NaN,99.0,95.0,98.0,93.0,92.0,NaN,34.9,24.4,12.3,9.8,4.8,0.8,NaN,0.175,NaN,0.149,1.548,0.0,NaN,NaN,1.59,0.234,NaN,NaN,0.067,81.0,78.0,543.0,14.0,140.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,214.866667,41.879026,-87.803818,RUSH OAK PARK HOSPITAL (140063)

In [41]:
print('main_df.shape:', main_df.shape)
main_df.drop_duplicates(inplace=True)
print('main_df.shape:', main_df.shape)

main_df.shape: (21585, 253)
main_df.shape: (21585, 253)

In [42]:
## save main_df to file
main_df.to_pickle(stars_dir + 'FilesForApp/hosp_stars_dat.pkl')